using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Encyclopedia.Pages;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Encyclopedia;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x02000045 RID: 69
	public class EncyclopediaFactionPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaFactionPageVM_Dependency_10_EncyclopediaDivider__DependendPrefab : EncyclopediaDividerButtonWidget
	{
		// Token: 0x06001165 RID: 4453 RVA: 0x000801DB File Offset: 0x0007E3DB
		public EncyclopediaFactionPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaFactionPageVM_Dependency_10_EncyclopediaDivider__DependendPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06001166 RID: 4454 RVA: 0x000801E4 File Offset: 0x0007E3E4
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new NavigationScopeTargeter(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new NavigationAutoScrollWidget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_2 = new ListPanel(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_2_0 = new BrushWidget(base.Context);
			this._widget_2.AddChild(this._widget_2_0);
			this._widget_2_1 = new TextWidget(base.Context);
			this._widget_2.AddChild(this._widget_2_1);
			this._widget_2_2 = new ImageWidget(base.Context);
			this._widget_2.AddChild(this._widget_2_2);
		}

		// Token: 0x06001167 RID: 4455 RVA: 0x000802C4 File Offset: 0x0007E4C4
		public void SetIds()
		{
			this._widget_2.Id = "PlacementListPanel";
			this._widget_2_0.Id = "CollapseIndicator";
			this._widget_2_1.Id = "Text";
		}

		// Token: 0x06001168 RID: 4456 RVA: 0x000802F8 File Offset: 0x0007E4F8
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.CoverChildren;
			base.CollapseIndicator = this._widget_2_0;
			base.ItemListWidget = this._widget.FindChild(new BindingPath("..\\SettlementsGrid"));
			base.UpdateChildrenStates = true;
			base.DoNotPassEventsToChildren = true;
			base.ExtendCursorAreaLeft = 5f;
			base.ExtendCursorAreaRight = 5f;
			base.ExtendCursorAreaTop = 5f;
			base.ExtendCursorAreaBottom = 5f;
			base.GamepadNavigationIndex = 0;
			this._widget_0.ScopeID = "EncyclopediaDividerScope";
			this._widget_0.ScopeParent = this._widget;
			this._widget_0.NavigateFromScopeEdges = true;
			this._widget_0.UseDiscoveryAreaAsScopeEdges = true;
			this._widget_1.TrackedWidget = this._widget;
			this._widget_1.AutoScrollTopOffset = 35;
			this._widget_1.AutoScrollBottomOffset = 35;
			this._widget_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_2.UpdateChildrenStates = true;
			this._widget_2_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_2_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_2_0.SuggestedHeight = 19f;
			this._widget_2_0.SuggestedWidth = 19f;
			this._widget_2_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_2_0.PositionYOffset = -3f;
			this._widget_2_0.Brush = base.Context.GetBrush("SPOptions.GameKeysgroup.ExpandIndicator");
			this._widget_2_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_2_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_2_1.Brush = base.Context.GetBrush("Encyclopedia.SubPage.Header.Text");
			this._widget_2_1.MarginLeft = 10f;
			this._widget_2_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_2_2.SuggestedHeight = 2f;
			this._widget_2_2.VerticalAlignment = VerticalAlignment.Center;
			this._widget_2_2.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_2_2.MarginLeft = 15f;
			this._widget_2_2.Brush = base.Context.GetBrush("SPOptions.CollapserLine");
		}

		// Token: 0x06001169 RID: 4457 RVA: 0x00080520 File Offset: 0x0007E720
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2_1;
				this._datasource_Root = null;
			}
		}

		// Token: 0x0600116A RID: 4458 RVA: 0x000806DD File Offset: 0x0007E8DD
		public void SetDataSource(EncyclopediaFactionPageVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x0600116B RID: 4459 RVA: 0x000806E6 File Offset: 0x0007E8E6
		private void PropertyChangedListenerOf_widget_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_1(propertyName);
		}

		// Token: 0x0600116C RID: 4460 RVA: 0x000806EF File Offset: 0x0007E8EF
		private void boolPropertyChangedListenerOf_widget_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_1(propertyName);
		}

		// Token: 0x0600116D RID: 4461 RVA: 0x000806F8 File Offset: 0x0007E8F8
		private void floatPropertyChangedListenerOf_widget_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_1(propertyName);
		}

		// Token: 0x0600116E RID: 4462 RVA: 0x00080701 File Offset: 0x0007E901
		private void Vec2PropertyChangedListenerOf_widget_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_1(propertyName);
		}

		// Token: 0x0600116F RID: 4463 RVA: 0x0008070A File Offset: 0x0007E90A
		private void Vector2PropertyChangedListenerOf_widget_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_1(propertyName);
		}

		// Token: 0x06001170 RID: 4464 RVA: 0x00080713 File Offset: 0x0007E913
		private void doublePropertyChangedListenerOf_widget_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_1(propertyName);
		}

		// Token: 0x06001171 RID: 4465 RVA: 0x0008071C File Offset: 0x0007E91C
		private void intPropertyChangedListenerOf_widget_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_1(propertyName);
		}

		// Token: 0x06001172 RID: 4466 RVA: 0x00080725 File Offset: 0x0007E925
		private void uintPropertyChangedListenerOf_widget_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_1(propertyName);
		}

		// Token: 0x06001173 RID: 4467 RVA: 0x0008072E File Offset: 0x0007E92E
		private void ColorPropertyChangedListenerOf_widget_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_1(propertyName);
		}

		// Token: 0x06001174 RID: 4468 RVA: 0x00080737 File Offset: 0x0007E937
		private void HandleWidgetPropertyChangeOf_widget_2_1(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.SettlementsText = this._widget_2_1.Text;
				return;
			}
		}

		// Token: 0x06001175 RID: 4469 RVA: 0x0008075D File Offset: 0x0007E95D
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001176 RID: 4470 RVA: 0x0008076B File Offset: 0x0007E96B
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001177 RID: 4471 RVA: 0x0008077A File Offset: 0x0007E97A
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001178 RID: 4472 RVA: 0x00080789 File Offset: 0x0007E989
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001179 RID: 4473 RVA: 0x00080798 File Offset: 0x0007E998
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600117A RID: 4474 RVA: 0x000807A7 File Offset: 0x0007E9A7
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600117B RID: 4475 RVA: 0x000807B6 File Offset: 0x0007E9B6
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600117C RID: 4476 RVA: 0x000807C5 File Offset: 0x0007E9C5
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600117D RID: 4477 RVA: 0x000807D4 File Offset: 0x0007E9D4
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600117E RID: 4478 RVA: 0x000807E3 File Offset: 0x0007E9E3
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "SettlementsText")
			{
				this._widget_2_1.Text = this._datasource_Root.SettlementsText;
				return;
			}
		}

		// Token: 0x0600117F RID: 4479 RVA: 0x0008080C File Offset: 0x0007EA0C
		private void RefreshDataSource_datasource_Root(EncyclopediaFactionPageVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2_1;
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2_1.Text = this._datasource_Root.SettlementsText;
				this._widget_2_1.PropertyChanged += this.PropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_2_1;
				this._widget_2_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_2_1;
			}
		}

		// Token: 0x04000367 RID: 871
		private EncyclopediaDividerButtonWidget _widget;

		// Token: 0x04000368 RID: 872
		private NavigationScopeTargeter _widget_0;

		// Token: 0x04000369 RID: 873
		private NavigationAutoScrollWidget _widget_1;

		// Token: 0x0400036A RID: 874
		private ListPanel _widget_2;

		// Token: 0x0400036B RID: 875
		private BrushWidget _widget_2_0;

		// Token: 0x0400036C RID: 876
		private TextWidget _widget_2_1;

		// Token: 0x0400036D RID: 877
		private ImageWidget _widget_2_2;

		// Token: 0x0400036E RID: 878
		private EncyclopediaFactionPageVM _datasource_Root;
	}
}
