const fs=require('fs');
let c=fs.readFileSync('VoteDealBehavior.cs','utf-8');

// 1. using Settlements
c=c.replace('using TaleWorlds.CampaignSystem.Election;',
           'using TaleWorlds.CampaignSystem.Election;\r\nusing TaleWorlds.CampaignSystem.Settlements;');

// 2. Harmony propose_agenda injection
c=c.replace(
'\t\t\tbool voteDealRuleInjected = (__result.Extras ?? "").IndexOf("【附加规则:vote_deal】", StringComparison.OrdinalIgnoreCase) >= 0;\r\n\t\t\tif (voteDealRuleInjected)\r\n\t\t\t{\r\n\t\t\t\tstring runtimeInstruction = BuildRuntimeVoteDealInstruction(contextTarget);\r\n\t\t\t\tif (!string.IsNullOrWhiteSpace(runtimeInstruction))\r\n\t\t\t\t{\r\n\t\t\t\t\t__result.Extras = (__result.Extras ?? "") + "\n" + runtimeInstruction;\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\tstring ctx = BuildPendingDecisionsContext(contextTarget);',
'\t\t\tbool voteDealRuleInjected = (__result.Extras ?? "").IndexOf("【附加规则:vote_deal】", StringComparison.OrdinalIgnoreCase) >= 0;\r\n\t\t\tif (voteDealRuleInjected)\r\n\t\t\t{\r\n\t\t\t\tstring runtimeInstruction = BuildRuntimeVoteDealInstruction(contextTarget);\r\n\t\t\t\tif (!string.IsNullOrWhiteSpace(runtimeInstruction))\r\n\t\t\t\t{\r\n\t\t\t\t\t__result.Extras = (__result.Extras ?? "") + "\n" + runtimeInstruction;\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\tbool pa = (__result.Extras ?? "").IndexOf("【附加规则:propose_agenda】", StringComparison.OrdinalIgnoreCase) >= 0;\r\n\t\t\tif (pa)\r\n\t\t\t{\r\n\t\t\t\tstring pr = BuildProposeRuntimeInstruction(contextTarget);\r\n\t\t\t\tif (!string.IsNullOrWhiteSpace(pr))\r\n\t\t\t\t\t__result.Extras = (__result.Extras ?? "") + "\n" + pr;\r\n\t\t\t}\r\n\t\t\tstring ctx = BuildPendingDecisionsContext(contextTarget);'
);

// 3. Insert propose code before VoteDealBehavior class close
// Class closes at: \t}\r\n\r\n\t// ═══════════...
const mk = '	}

		// ════════════════════════════════════════════════════════════════════════';
let idx = c.indexOf(mk);
if (idx < 0) { console.log('MARKER NOT FOUND'); process.exit(1); }

const L = [];
function A(s) { L.push('\t\t' + s); }
function B() { L.push(''); }

B(); A('// ── Propose Agenda ──────────────────────────────────────────────'); B();
A('private static readonly Regex ProposeTagRx = new Regex(');
A('\t@"\\[ACTION:PROPOSE:[^\\]\\r\\n]*\\]", RegexOptions.IgnoreCase | RegexOptions.Compiled);');
A('private static readonly string[] ProposeTypes =');
A('\t{ "WAR", "PEACE", "POLICY", "EXPEL", "ALLIANCE", "TRADE", "FIEF" };'); B();
A('public static void ProcessProposeDispatch(Hero npc, ref string text)');
A('{');
A('\tif (npc == null || string.IsNullOrEmpty(text) || !text.Contains("PROPOSE")) return;');
A('\tvar b = Instance ?? Campaign.Current?.GetCampaignBehavior<VoteDealBehavior>();');
A('\tif (b == null) return;');
A('\tint mc = 0;');
A('\ttext = ProposeTagRx.Replace(text, m => {');
A('\t\tvar t = m.Value;');
A('\t\tvar r = ProcessProposeTag(npc, t);');
A('\t\tmc++;');
A('\t\treturn r;');
A('\t});');
A('\tif (mc > 0) { text = ProposeTagRx.Replace(text, "", 1); text = text.Trim(); }');
A('}'); B();
A('private static string ProcessProposeTag(Hero npc, string tag)');
A('{');
A('\ttry');
A('\t{');
A('\t\tvar p = (tag ?? "").Trim();');
A('\t\tif (p.StartsWith("[ACTION:PROPOSE:", StringComparison.OrdinalIgnoreCase))');
A('\t\t\tp = p.Substring("[ACTION:PROPOSE:".Length).TrimEnd(\']\');');
A('\t\tif (string.IsNullOrWhiteSpace(p)) return "";');
A('\t\tvar ps = p.Split(new[] { \':\' }, 3);');
A('\t\tif (ps.Length < 2) return "";');
A('\t\tvar tp = (ps[0] ?? "").Trim().ToUpperInvariant();');
A('\t\tvar tn = (ps[1] ?? "").Trim();');
A('\t\tvar dr = ps.Length >= 3 ? (ps[2] ?? "").Trim().ToUpperInvariant() : "";');
A('\t\tif (!((IList<string>)ProposeTypes).Contains(tp)) return "";');
A('\t\treturn ExecutePropose(npc, tp, tn, dr);');
A('\t}');
A('\tcatch (Exception ex) { Logger.Log("ProposeAgenda", "Tag:" + ex.Message); return ""; }');
A('}'); B();
A('private static string ExecutePropose(Hero npc, string type, string tgt, string dir)');
A('{');
A('\ttry');
A('\t{');
A('\t\tClan cl = npc?.Clan;');
A('\t\tKingdom kd = cl?.Kingdom;');
A('\t\tif (cl == null || kd == null || cl.IsUnderMercenaryService || npc != cl.Leader) return "";');
A('\t\tvar dm = Campaign.Current.Models.DiplomacyModel;');
A('\t\tKingdomDecision d = null;');
A('\t\tswitch (type)');
A('\t\t{');
A('\t\t\tcase "WAR":');
A('\t\t\t{');
A('\t\t\t\tvar tg = FindFactionByName(tgt);');
A('\t\t\t\tif (tg == null || !tg.IsKingdomFaction) return "";');
A('\t\t\t\tif (FactionManager.IsAtWarAgainstFaction(kd, tg)) return "";');
A('\t\t\t\tint cst = dm.GetInfluenceCostOfProposingWar(cl);');
A('\t\t\t\tif (cl.Influence < cst) return "";');
A('\t\t\t\td = new DeclareWarDecision(cl, (Kingdom)tg);');
A('\t\t\t\tbreak;');
A('\t\t\t}');
A('\t\t\tcase "PEACE":');
A('\t\t\t{');
A('\t\t\t\tvar tg = FindFactionByName(tgt);');
A('\t\t\t\tif (tg == null || !tg.IsKingdomFaction) return "";');
A('\t\t\t\tif (!FactionManager.IsAtWarAgainstFaction(kd, tg)) return "";');
A('\t\t\t\tint cst = dm.GetInfluenceCostOfProposingPeace(cl);');
A('\t\t\t\tif (cl.Influence < cst) return "";');
A('\t\t\t\td = new MakePeaceKingdomDecision(cl, (Kingdom)tg);');
A('\t\t\t\tbreak;');
A('\t\t\t}');
A('\t\t\tcase "POLICY":');
A('\t\t\t{');
A('\t\t\t\tvar po = FindPolicyByName(tgt);');
A('\t\t\t\tif (po == null) return "";');
A('\t\t\t\tbool ia = kd.ActivePolicies.Contains(po);');
A('\t\t\t\tbool ad = dir == "ADOPT", ab = dir == "ABOLISH";');
A('\t\t\t\tif (!ad && !ab) { ad = !ia; ab = ia; }');
A('\t\t\t\tif ((ad && ia) || (ab && !ia)) return "";');
A('\t\t\t\tint cst = dm.GetInfluenceCostOfPolicyProposalAndDisavowal(cl);');
A('\t\t\t\tif (cl.Influence < cst) return "";');
A('\t\t\t\td = new KingdomPolicyDecision(cl, po, ab);');
A('\t\t\t\tbreak;');
A('\t\t\t}');
A('\t\t\tcase "EXPEL":');
A('\t\t\t{');
A('\t\t\t\tvar tc = FindClanByName(tgt, kd);');
A('\t\t\t\tif (tc == null || tc == kd.RulingClan || tc == cl) return "";');
A('\t\t\t\td = new ExpelClanFromKingdomDecision(cl, tc);');
A('\t\t\t\tif (cl.Influence < d.GetInfluenceCost(cl)) return "";');
A('\t\t\t\tbreak;');
A('\t\t\t}');
A('\t\t\tcase "ALLIANCE":');
A('\t\t\t{');
A('\t\t\t\tvar tg = FindFactionByName(tgt);');
A('\t\t\t\tif (tg == null || !tg.IsKingdomFaction) return "";');
A('\t\t\t\tif (!FactionManager.IsNeutralWithFaction(kd, tg)) return "";');
A('\t\t\t\td = new StartAllianceDecision(cl, (Kingdom)tg);');
A('\t\t\t\tif (cl.Influence < d.GetInfluenceCost(cl)) return "";');
A('\t\t\t\tbreak;');
A('\t\t\t}');
A('\t\t\tcase "TRADE":');
A('\t\t\t{');
A('\t\t\t\tvar tg = FindFactionByName(tgt);');
A('\t\t\t\tif (tg == null || !tg.IsKingdomFaction) return "";');
A('\t\t\t\tif (FactionManager.IsAtWarAgainstFaction(kd, tg)) return "";');
A('\t\t\t\td = new TradeAgreementDecision(cl, (Kingdom)tg);');
A('\t\t\t\tif (cl.Influence < d.GetInfluenceCost(cl)) return "";');
A('\t\t\t\tbreak;');
A('\t\t\t}');
A('\t\t\tcase "FIEF":');
A('\t\t\t{');
A('\t\t\t\tTown tw = FindTownByName(tgt, kd);');
A('\t\t\t\tif (tw == null) return "";');
A('\t\t\t\tint cst = dm.GetInfluenceCostOfAnnexation(cl);');
A('\t\t\t\tif (cl.Influence < cst) return "";');
A('\t\t\t\td = new SettlementClaimantPreliminaryDecision(cl, tw.Settlement);');
A('\t\t\t\tbreak;');
A('\t\t\t}');
A('\t\t}');
A('\t\tif (d == null) return "";');
A('\t\tkd.AddDecision(d, false);');
A('\t\tstring cn = cl.Name?.ToString() ?? "?";');
A('\t\tAnimusForgeQuickInfo.ShowForDuration(cn + "家族 提出新议程", 6000, npc.CharacterObject);');
A('\t\tLogger.Log("ProposeAgenda", "OK:" + type + " " + tgt);');
A('\t\treturn "";');
A('\t}');
A('\tcatch (Exception ex) { Logger.Log("ProposeAgenda", "Exec:" + ex.Message); return ""; }');
A('}'); B();

// Entity search
A('private static IFaction FindFactionByName(string name)');
A('{');
A('\tif (string.IsNullOrWhiteSpace(name)) return null;');
A('\tname = name.Trim();');
A('\tforeach (Kingdom k in Kingdom.All)');
A('\t{');
A('\t\tif (string.Equals(k.Name?.ToString() ?? "", name, StringComparison.OrdinalIgnoreCase)) return k;');
A('\t\tif (string.Equals(k.StringId, name, StringComparison.OrdinalIgnoreCase)) return k;');
A('\t}');
A('\tforeach (Kingdom k in Kingdom.All)');
A('\t{');
A('\t\tstring kn = k.Name?.ToString() ?? "";');
A('\t\tif (!string.IsNullOrWhiteSpace(kn) && kn.Contains(name)) return k;');
A('\t}');
A('\treturn null;');
A('}'); B();
A('private static PolicyObject FindPolicyByName(string name)');
A('{');
A('\tif (string.IsNullOrWhiteSpace(name)) return null;');
A('\tname = name.Trim();');
A('\tforeach (PolicyObject p in PolicyObject.All)');
A('\t{');
A('\t\tif (string.Equals(p.Name?.ToString() ?? "", name, StringComparison.OrdinalIgnoreCase)) return p;');
A('\t\tif (string.Equals(p.StringId, name, StringComparison.OrdinalIgnoreCase)) return p;');
A('\t}');
A('\tforeach (PolicyObject p in PolicyObject.All)');
A('\t{');
A('\t\tstring pn = p.Name?.ToString() ?? "";');
A('\t\tif (!string.IsNullOrWhiteSpace(pn) && pn.Contains(name)) return p;');
A('\t}');
A('\treturn null;');
A('}'); B();
A('private static Clan FindClanByName(string name, Kingdom kingdom)');
A('{');
A('\tif (string.IsNullOrWhiteSpace(name) || kingdom == null) return null;');
A('\tname = name.Trim();');
A('\tforeach (Clan cl in kingdom.Clans)');
A('\t{');
A('\t\tif (string.Equals(cl.Name?.ToString() ?? "", name, StringComparison.OrdinalIgnoreCase)) return cl;');
A('\t\tif (string.Equals(cl.StringId, name, StringComparison.OrdinalIgnoreCase)) return cl;');
A('\t}');
A('\tforeach (Clan cl in kingdom.Clans)');
A('\t{');
A('\t\tstring cn = cl.Name?.ToString() ?? "";');
A('\t\tif (!string.IsNullOrWhiteSpace(cn) && cn.Contains(name)) return cl;');
A('\t}');
A('\treturn null;');
A('}'); B();
A('private static Town FindTownByName(string name, Kingdom kingdom)');
A('{');
A('\tif (string.IsNullOrWhiteSpace(name) || kingdom == null) return null;');
A('\tname = name.Trim();');
A('\tforeach (Town t in kingdom.Fiefs)');
A('\t{');
A('\t\tif (string.Equals(t.Name?.ToString() ?? "", name, StringComparison.OrdinalIgnoreCase)) return t;');
A('\t\tif (string.Equals(t.StringId, name, StringComparison.OrdinalIgnoreCase)) return t;');
A('\t}');
A('\tforeach (Town t in kingdom.Fiefs)');
A('\t{');
A('\t\tstring tn = t.Name?.ToString() ?? "";');
A('\t\tif (!string.IsNullOrWhiteSpace(tn) && tn.Contains(name)) return t;');
A('\t}');
A('\treturn null;');
A('}'); B();

// Context builders
A('public static string BuildProposePostprocessContext(Hero npc)');
A('{');
A('\ttry');
A('\t{');
A('\t\tif (!CanPropose(npc)) return "";');
A('\t\tvar sb = new StringBuilder();');
A('\t\tsb.AppendLine("【议程提议后处理】同意后输出[ACTION:PROPOSE:类型:目标名:方向]。类型=WAR/PEACE/POLICY/EXPEL/ALLIANCE/TRADE/FIEF。方向仅POLICY用ADOPT/ABOLISH。");');
A('\t\treturn sb.ToString().TrimEnd();');
A('\t}');
A('\tcatch { return ""; }');
A('}'); B();
A('public static bool CanPropose(Hero npc)');
A('{');
A('\ttry');
A('\t{');
A('\t\tvar cl = npc?.Clan;');
A('\t\treturn cl != null && cl.Kingdom != null && !cl.IsUnderMercenaryService && npc == cl.Leader;');
A('\t}');
A('\tcatch { return false; }');
A('}'); B();
A('public static string BuildProposeRuntimeInstruction(Hero npc)');
A('{');
A('\ttry');
A('\t{');
A('\t\tClan cl = npc?.Clan;');
A('\t\tKingdom kd = cl?.Kingdom;');
A('\t\tstring pn = MyBehavior.BuildPlayerPublicDisplayNameForExternal() ?? "玩家";');
A('\t\tvar tk = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) { ["playerName"] = pn };');
A('\t\tstring sk = kd == null ? "no_kingdom" : cl.IsUnderMercenaryService ? "mercenary" : npc != cl.Leader ? "not_clan_leader" : "";');
A('\t\tvar rl = new List<string>();');
A('\t\tif (!string.IsNullOrWhiteSpace(sk))');
A('\t\t{');
A('\t\t\tvar st = AIConfigHandler.ResolveRuleRuntimeText("propose_agenda", sk, forConstraint: false, tokens: tk);');
A('\t\t\tif (!string.IsNullOrWhiteSpace(st)) rl.Add(st);');
A('\t\t\treturn string.Join("\\n", rl);');
A('\t\t}');
A('\t\tif (kd != null && !cl.IsUnderMercenaryService && npc == cl.Leader)');
A('\t\t{');
A('\t\t\tint ti = 6;');
A('\t\t\ttry { ti = RewardSystemBehavior.GetTrustLevelIndex(RewardSystemBehavior.Instance?.GetEffectiveTrust(npc) ?? 0); } catch { }');
A('\t\t\tvar tt = AIConfigHandler.ResolveRuleRuntimeText("propose_agenda", "level_" + ti, forConstraint: false, tokens: tk);');
A('\t\t\tif (!string.IsNullOrWhiteSpace(tt)) rl.Add(tt);');
A('\t\t\tif (kd.RulingClan?.Leader == npc)');
A('\t\t\t{');
A('\t\t\t\tvar kt = AIConfigHandler.ResolveRuleRuntimeText("propose_agenda", "is_king", forConstraint: false, tokens: tk);');
A('\t\t\t\tif (!string.IsNullOrWhiteSpace(kt)) rl.Add(kt);');
A('\t\t\t}');
A('\t\t}');
A('\t\treturn string.Join("\\n", rl);');
A('\t}');
A('\tcatch (Exception ex) { Logger.Log("ProposeAgenda", "RT:" + ex.Message); return ""; }');
A('}');

c = c.slice(0, idx) + L.join('\r\n') + '\r\n' + c.slice(idx);
let d = 0;
for (const ch of c) { if (ch === '{') d++; if (ch === '}') d--; }
fs.writeFileSync('VoteDealBehavior.cs', c, 'utf-8');
console.log('Lines: ' + L.length + ', Brace balance: ' + d + ', Total lines: ' + c.split('\r\n').length);
