using System.ComponentModel;
using System.Numerics;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Multiplayer.Perks;
using TaleWorlds.MountAndBlade.Multiplayer.ViewModelCollection.ClassLoadout;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated0;

public class MultiplayerDuel__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_MultiplayerDuelVM_Dependency_7_ItemTemplate : MultiplayerPerkItemToggleWidget
{
	private MultiplayerPerkItemToggleWidget _widget;

	private BrushWidget _widget_0;

	private BrushWidget _widget_0_0;

	private MPPerkVM _datasource_Root;

	public MultiplayerDuel__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_MultiplayerDuelVM_Dependency_7_ItemTemplate(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		//IL_000e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0018: Expected O, but got Unknown
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_003a: Expected O, but got Unknown
		_widget = (MultiplayerPerkItemToggleWidget)(object)this;
		_widget_0 = new BrushWidget(((Widget)this).Context);
		((Widget)_widget).AddChild((Widget)(object)_widget_0);
		_widget_0_0 = new BrushWidget(((Widget)this).Context);
		((Widget)_widget_0).AddChild((Widget)(object)_widget_0_0);
	}

	public void SetIds()
	{
		((Widget)_widget_0).Id = "Icon";
	}

	public void SetAttributes()
	{
		//IL_0058: Unknown result type (might be due to invalid IL or missing references)
		//IL_0062: Expected O, but got Unknown
		((Widget)this).WidthSizePolicy = (SizePolicy)0;
		((Widget)this).HeightSizePolicy = (SizePolicy)0;
		((Widget)this).SuggestedWidth = 60f;
		((Widget)this).SuggestedHeight = 50f;
		((Widget)this).HorizontalAlignment = (HorizontalAlignment)1;
		((Widget)this).MarginTop = 0f;
		((BrushWidget)this).Brush = ((Widget)this).Context.GetBrush("MPClassLoadout.Perks.Button");
		_003F val = this;
		Widget obj = ((Widget)_widget).FindChild(new BindingPath("..\\..\\..\\PerksPanel"));
		((MultiplayerPerkItemToggleWidget)val).ContainerPanel = (MultiplayerPerkContainerPanelWidget)(object)((obj is MultiplayerPerkContainerPanelWidget) ? obj : null);
		((MultiplayerPerkItemToggleWidget)this).IconWidget = _widget_0;
		((MultiplayerPerkItemToggleWidget)this).IsSelectable = false;
		((Widget)_widget_0).WidthSizePolicy = (SizePolicy)0;
		((Widget)_widget_0).HeightSizePolicy = (SizePolicy)0;
		((Widget)_widget_0).SuggestedWidth = 40f;
		((Widget)_widget_0).SuggestedHeight = 40f;
		((Widget)_widget_0).HorizontalAlignment = (HorizontalAlignment)1;
		((Widget)_widget_0).MarginTop = 10f;
		_widget_0.Brush = ((Widget)this).Context.GetBrush("MPClassLoadout.Perks.Icon");
		((Widget)_widget_0_0).WidthSizePolicy = (SizePolicy)0;
		((Widget)_widget_0_0).HeightSizePolicy = (SizePolicy)0;
		((Widget)_widget_0_0).SuggestedWidth = 47f;
		((Widget)_widget_0_0).SuggestedHeight = 47f;
		((Widget)_widget_0_0).HorizontalAlignment = (HorizontalAlignment)1;
		((Widget)_widget_0_0).VerticalAlignment = (VerticalAlignment)1;
		_widget_0_0.Brush = ((Widget)this).Context.GetBrush("MPClassLoadout.Perks.Frame");
	}

	public void DestroyDataSource()
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget).PropertyChanged -= PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).intPropertyChanged -= intPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			_datasource_Root = null;
		}
	}

	public void SetDataSource(MPPerkVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget(string propertyName)
	{
		if (propertyName == "IconType")
		{
			_datasource_Root.IconType = _widget.IconType;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithBoolValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithFloatValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithUIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithColorValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithDoubleValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithVec2ValueEventArgs)(ref e)).PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		if (propertyName == "IconType")
		{
			_widget.IconType = _datasource_Root.IconType;
		}
	}

	private void RefreshDataSource_datasource_Root(MPPerkVM newDataSource)
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_01e6: Unknown result type (might be due to invalid IL or missing references)
		//IL_01f0: Expected O, but got Unknown
		//IL_01fd: Unknown result type (might be due to invalid IL or missing references)
		//IL_0207: Expected O, but got Unknown
		//IL_0214: Unknown result type (might be due to invalid IL or missing references)
		//IL_021e: Expected O, but got Unknown
		//IL_022b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0235: Expected O, but got Unknown
		//IL_0242: Unknown result type (might be due to invalid IL or missing references)
		//IL_024c: Expected O, but got Unknown
		//IL_0259: Unknown result type (might be due to invalid IL or missing references)
		//IL_0263: Expected O, but got Unknown
		//IL_0270: Unknown result type (might be due to invalid IL or missing references)
		//IL_027a: Expected O, but got Unknown
		//IL_0287: Unknown result type (might be due to invalid IL or missing references)
		//IL_0291: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget).PropertyChanged -= PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).intPropertyChanged -= intPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			_widget.IconType = _datasource_Root.IconType;
			((PropertyOwnerObject)_widget).PropertyChanged += PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).boolPropertyChanged += boolPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).floatPropertyChanged += floatPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).doublePropertyChanged += doublePropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).intPropertyChanged += intPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).uintPropertyChanged += uintPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget;
		}
	}
}
