<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PlayerExportsEditor.Core\PlayerExportsEditor.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>AnimusForgePlayerExportsEditor</AssemblyName>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <Product>AnimusForge PlayerExports Editor</Product>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
