using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.GameMenus;
using TaleWorlds.CampaignSystem.GameState;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000358 RID: 856
	public class ArtisanCantSellProductsAtAFairPriceIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x06003297 RID: 12951 RVA: 0x000CFA15 File Offset: 0x000CDC15
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x06003298 RID: 12952 RVA: 0x000CFA30 File Offset: 0x000CDC30
		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnStartIssue), typeof(ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssue), IssueBase.IssueFrequency.Common, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssue), IssueBase.IssueFrequency.Common));
		}

		// Token: 0x06003299 RID: 12953 RVA: 0x000CFA94 File Offset: 0x000CDC94
		private bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.IsArtisan && ArtisanCantSellProductsAtAFairPriceIssueBehavior.SelectCounterOfferHero(issueGiver) != null && ArtisanCantSellProductsAtAFairPriceIssueBehavior.SelectTargetSettlement(issueGiver) != null;
		}

		// Token: 0x0600329A RID: 12954 RVA: 0x000CFAB4 File Offset: 0x000CDCB4
		private static Hero SelectCounterOfferHero(Hero issueGiver)
		{
			return issueGiver.CurrentSettlement.Notables.FirstOrDefault((Hero x) => x.CharacterObject.IsHero && x.CanHaveCampaignIssues() && x.CharacterObject.HeroObject != issueGiver && x.CharacterObject.HeroObject.IsMerchant);
		}

		// Token: 0x0600329B RID: 12955 RVA: 0x000CFAF0 File Offset: 0x000CDCF0
		private static Settlement SelectTargetSettlement(Hero issueGiver)
		{
			Settlement issueSettlement = issueGiver.CurrentSettlement;
			MobileParty.NavigationType navigationType = (issueSettlement.OwnerClan.HasNavalNavigationCapability ? MobileParty.NavigationType.All : MobileParty.NavigationType.Default);
			float maximumDistanceForSettlementSelection = Campaign.Current.GetAverageDistanceBetweenClosestTwoTownsWithNavigationType(navigationType) * 2.25f;
			return SettlementHelper.FindNearestSettlementToMobileParty(MobileParty.MainParty, navigationType, delegate(Settlement x)
			{
				if (x.IsTown && x != issueSettlement)
				{
					if (x.Notables.Any((Hero y) => y.CanHaveCampaignIssues()))
					{
						return Campaign.Current.Models.MapDistanceModel.GetDistance(x, issueSettlement, false, false, navigationType) < maximumDistanceForSettlementSelection;
					}
				}
				return false;
			});
		}

		// Token: 0x0600329C RID: 12956 RVA: 0x000CFB63 File Offset: 0x000CDD63
		private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
		{
			return new ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssue(issueOwner);
		}

		// Token: 0x0600329D RID: 12957 RVA: 0x000CFB6B File Offset: 0x000CDD6B
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x04000E78 RID: 3704
		private const IssueBase.IssueFrequency ArtisanCantSellProductsAtAFairPriceIssueFrequency = IssueBase.IssueFrequency.Common;

		// Token: 0x020006DC RID: 1756
		public class ArtisanCantSellProductsAtAFairPriceIssue : IssueBase
		{
			// Token: 0x06005366 RID: 21350 RVA: 0x0018962A File Offset: 0x0018782A
			internal static void AutoGeneratedStaticCollectObjectsArtisanCantSellProductsAtAFairPriceIssue(object o, List<object> collectedObjects)
			{
				((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005367 RID: 21351 RVA: 0x00189638 File Offset: 0x00187838
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._rawMaterialsToBeDelivered);
				collectedObjects.Add(this._targetSettlement);
				collectedObjects.Add(this._targetHero);
				collectedObjects.Add(this.CounterOfferHero);
			}

			// Token: 0x06005368 RID: 21352 RVA: 0x00189671 File Offset: 0x00187871
			internal static object AutoGeneratedGetMemberValueCounterOfferHero(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssue)o).CounterOfferHero;
			}

			// Token: 0x06005369 RID: 21353 RVA: 0x0018967E File Offset: 0x0018787E
			internal static object AutoGeneratedGetMemberValue_rawMaterialsToBeDelivered(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssue)o)._rawMaterialsToBeDelivered;
			}

			// Token: 0x0600536A RID: 21354 RVA: 0x0018968B File Offset: 0x0018788B
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssue)o)._targetSettlement;
			}

			// Token: 0x0600536B RID: 21355 RVA: 0x00189698 File Offset: 0x00187898
			internal static object AutoGeneratedGetMemberValue_targetHero(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssue)o)._targetHero;
			}

			// Token: 0x17000F84 RID: 3972
			// (get) Token: 0x0600536C RID: 21356 RVA: 0x001896A5 File Offset: 0x001878A5
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Duration;
				}
			}

			// Token: 0x17000F85 RID: 3973
			// (get) Token: 0x0600536D RID: 21357 RVA: 0x001896A8 File Offset: 0x001878A8
			// (set) Token: 0x0600536E RID: 21358 RVA: 0x001896B0 File Offset: 0x001878B0
			[SaveableProperty(30)]
			public override Hero CounterOfferHero { get; protected set; }

			// Token: 0x17000F86 RID: 3974
			// (get) Token: 0x0600536F RID: 21359 RVA: 0x001896B9 File Offset: 0x001878B9
			private int RawMaterialCountToBeDelivered
			{
				get
				{
					return (int)(60f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17000F87 RID: 3975
			// (get) Token: 0x06005370 RID: 21360 RVA: 0x001896C8 File Offset: 0x001878C8
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 3 + MathF.Ceiling(6f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17000F88 RID: 3976
			// (get) Token: 0x06005371 RID: 21361 RVA: 0x001896DD File Offset: 0x001878DD
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 3 + MathF.Ceiling(5f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17000F89 RID: 3977
			// (get) Token: 0x06005372 RID: 21362 RVA: 0x001896F2 File Offset: 0x001878F2
			protected override int RewardGold
			{
				get
				{
					return (int)(500f + 1500f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17000F8A RID: 3978
			// (get) Token: 0x06005373 RID: 21363 RVA: 0x00189707 File Offset: 0x00187907
			public override int NeededInfluenceForLordSolution
			{
				get
				{
					return 10 + MathF.Round(40f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17000F8B RID: 3979
			// (get) Token: 0x06005374 RID: 21364 RVA: 0x00189720 File Offset: 0x00187920
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=4M6jlZVa}{ISSUE_GIVER.LINK} an artisan from {ISSUE_GIVER_SETTLEMENT} has complained to you about not being able to sell their goods at the price they want because of local laws. {?ISSUE_GIVER.GENDER}She{?}He{\\?} will pay {REWARD}{GOLD_ICON} for you to take the goods to another town. You have tasked {COMPANION.LINK} and {ALTERNATIVE_SOLUTION_TROOP_COUNT} men to smuggle {?ISSUE_GIVER.GENDER}her{?}his{\\?} goods to a “friend” in {TARGET_TOWN}. They will return to you in {RETURN_DAYS} days with a sizable sum of {REWARD}{GOLD_ICON}.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("ISSUE_GIVER_SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("TARGET_TOWN", this._targetSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("ALTERNATIVE_SOLUTION_TROOP_COUNT", this.AlternativeSolutionSentTroops.TotalManCount - 1);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					textObject.SetTextVariable("REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			// Token: 0x17000F8C RID: 3980
			// (get) Token: 0x06005375 RID: 21365 RVA: 0x001897EB File Offset: 0x001879EB
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(400f + 1700f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17000F8D RID: 3981
			// (get) Token: 0x06005376 RID: 21366 RVA: 0x00189800 File Offset: 0x00187A00
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17000F8E RID: 3982
			// (get) Token: 0x06005377 RID: 21367 RVA: 0x00189803 File Offset: 0x00187A03
			public override bool IsThereLordSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17000F8F RID: 3983
			// (get) Token: 0x06005378 RID: 21368 RVA: 0x00189806 File Offset: 0x00187A06
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=Vg7Ftrdl}You might say that... I work from dawn to late into the night but even so I can barely put bread on the table. Why's that? Because I can't sell my product at a fair price. The law says that I can only sell to local merchants, and at a fixed rate too, so that even when other prices are high I'm still making the same.[if:convo_annoyed]", null);
				}
			}

			// Token: 0x17000F90 RID: 3984
			// (get) Token: 0x06005379 RID: 21369 RVA: 0x00189813 File Offset: 0x00187A13
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=ioF9aJBJ}How can I help?", null);
				}
			}

			// Token: 0x17000F91 RID: 3985
			// (get) Token: 0x0600537A RID: 21370 RVA: 0x00189820 File Offset: 0x00187A20
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=bOyjQ4yr}If you can deliver {REQUESTED_AMOUNT} {.%}{?(REQUESTED_AMOUNT > 1)}{PLURAL(RAW_MATERIALS)}{?}{RAW_MATERIALS}{\\?}{.%} to my contact {TARGET_HERO.LINK}, who you can find in {TARGET_SETTLEMENT}, that would help me survive for a time. The merchants of the town could be furious and lodge legal complaints of course, but hopefully you won't have to deal with that part.", null);
					StringHelpers.SetCharacterProperties("TARGET_HERO", this._targetHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("REQUESTED_AMOUNT", this.RawMaterialCountToBeDelivered);
					textObject.SetTextVariable("RAW_MATERIALS", this._rawMaterialsToBeDelivered.Name);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x17000F92 RID: 3986
			// (get) Token: 0x0600537B RID: 21371 RVA: 0x00189894 File Offset: 0x00187A94
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=Gzx35bRY}If you aren't going towards {TARGET_SETTLEMENT}, maybe you could have some of your men take my goods and bring back the profit? It shouldn't take more than {ALTERNATIVE_SOLUTION_MEN_AMOUNT} men and one of your trusted lieutenants with decent grasp of trade. They can go and be back in about {RETURN_DAYS} days.[if:convo_annoyed]", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("ALTERNATIVE_SOLUTION_MEN_AMOUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			// Token: 0x17000F93 RID: 3987
			// (get) Token: 0x0600537C RID: 21372 RVA: 0x001898E8 File Offset: 0x00187AE8
			public override TextObject IssueLordSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=tgj9BuCL}You could change this law, my {?PLAYER.GENDER}lady{?}lord{\\?}. All of us would be grateful. and we're willing to donate {REWARD}{GOLD_ICON} to show our thanks...", null);
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					textObject.SetTextVariable("REWARD", this.RewardGold);
					return textObject;
				}
			}

			// Token: 0x17000F94 RID: 3988
			// (get) Token: 0x0600537D RID: 21373 RVA: 0x00189937 File Offset: 0x00187B37
			public override TextObject IssueLordSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=azHy8uwl}I will issue a decree to remove the restrictions on the sale of goods.", null);
				}
			}

			// Token: 0x17000F95 RID: 3989
			// (get) Token: 0x0600537E RID: 21374 RVA: 0x00189944 File Offset: 0x00187B44
			public override TextObject IssueLordSolutionResponseByIssueGiver
			{
				get
				{
					return new TextObject("{=hAyFpmxq}My {?PLAYER.GENDER}lady{?}lord{\\?}, that would be very good. The merchants won't like it but hard-working artisans like me will be grateful to you.", null);
				}
			}

			// Token: 0x17000F96 RID: 3990
			// (get) Token: 0x0600537F RID: 21375 RVA: 0x00189951 File Offset: 0x00187B51
			public override TextObject IssueLordSolutionCounterOfferExplanationByOtherNpc
			{
				get
				{
					return new TextObject("{=nbeCbTH6}My {?PLAYER.GENDER}lady{?}lord{\\?}, we heard that you wish to issue a decree permitting artisans to behave like merchants. This will undo an arrangement here that's worked for generations. Please reconsider this.", null);
				}
			}

			// Token: 0x17000F97 RID: 3991
			// (get) Token: 0x06005380 RID: 21376 RVA: 0x0018995E File Offset: 0x00187B5E
			public override TextObject IssueLordSolutionCounterOfferBriefByOtherNpc
			{
				get
				{
					return new TextObject("{=KSeIOHDh}(One of the merchants in the town comes to talk as you are preparing to depart.)", null);
				}
			}

			// Token: 0x17000F98 RID: 3992
			// (get) Token: 0x06005381 RID: 21377 RVA: 0x0018996B File Offset: 0x00187B6B
			public override TextObject IssueLordSolutionCounterOfferAcceptByPlayer
			{
				get
				{
					return new TextObject("{=dpFFo2U2}I understand. I'll hold off on the decree, then.", null);
				}
			}

			// Token: 0x17000F99 RID: 3993
			// (get) Token: 0x06005382 RID: 21378 RVA: 0x00189978 File Offset: 0x00187B78
			public override TextObject IssueLordSolutionCounterOfferAcceptResponseByOtherNpc
			{
				get
				{
					return new TextObject("{=6ZTNuF30}That's the right call. Thank you for listening to the voice of reason.", null);
				}
			}

			// Token: 0x17000F9A RID: 3994
			// (get) Token: 0x06005383 RID: 21379 RVA: 0x00189985 File Offset: 0x00187B85
			public override TextObject IssueLordSolutionCounterOfferDeclineByPlayer
			{
				get
				{
					return new TextObject("{=K1J6Xqht}Sorry, I have to do it.", null);
				}
			}

			// Token: 0x17000F9B RID: 3995
			// (get) Token: 0x06005384 RID: 21380 RVA: 0x00189992 File Offset: 0x00187B92
			public override TextObject IssueLordSolutionCounterOfferDeclineResponseByOtherNpc
			{
				get
				{
					return new TextObject("{=YjsRb88D}That's your right, my {?PLAYER.GENDER}lady{?}lord{\\?}. But if you can't get the support of the merchants here when you next need it, well, don't say no one said anything.", null);
				}
			}

			// Token: 0x17000F9C RID: 3996
			// (get) Token: 0x06005385 RID: 21381 RVA: 0x0018999F File Offset: 0x00187B9F
			protected override TextObject LordSolutionStartLog
			{
				get
				{
					return new TextObject("{=FT9V47bd}You issued a decree to remove the restrictions on the sale of goods, as the artisans had requested.", null);
				}
			}

			// Token: 0x17000F9D RID: 3997
			// (get) Token: 0x06005386 RID: 21382 RVA: 0x001899AC File Offset: 0x00187BAC
			protected override TextObject LordSolutionCounterOfferAcceptLog
			{
				get
				{
					TextObject textObject = new TextObject("{=SpIn5pr4}After listening to the town merchants, you decided to keep the restrictions on the sale of goods. Your decision made the merchants happy but disappointed the {QUEST_GIVER.LINK}.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17000F9E RID: 3998
			// (get) Token: 0x06005387 RID: 21383 RVA: 0x001899E0 File Offset: 0x00187BE0
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=ueUsg9OL}I can take your goods to {TARGET_HERO.LINK} in {TARGET_SETTLEMENT} myself.", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					StringHelpers.SetCharacterProperties("TARGET_HERO", this._targetHero.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17000F9F RID: 3999
			// (get) Token: 0x06005388 RID: 21384 RVA: 0x00189A29 File Offset: 0x00187C29
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=qfClYYjK}Artisans Can't Sell Their Products in {ISSUE_GIVER_SETTLEMENT}", null);
					textObject.SetTextVariable("ISSUE_GIVER_SETTLEMENT", base.IssueSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17000FA0 RID: 4000
			// (get) Token: 0x06005389 RID: 21385 RVA: 0x00189A4D File Offset: 0x00187C4D
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=3KpgHPlo}The laws of {ISSUE_GIVER_SETTLEMENT} dictate that artisans sell their goods at a fixed rate to the merchants in town. And now they complain the price set by the merchants is not fair.", null);
					textObject.SetTextVariable("ISSUE_GIVER_SETTLEMENT", base.IssueOwner.CurrentSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17000FA1 RID: 4001
			// (get) Token: 0x0600538A RID: 21386 RVA: 0x00189A78 File Offset: 0x00187C78
			public override TextObject IssueAsRumorInSettlement
			{
				get
				{
					TextObject textObject = new TextObject("{=TuIyqMWG}The artisans and the merchants are at each other's throats right now. I bet {QUEST_GIVER.NAME} is planning something.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17000FA2 RID: 4002
			// (get) Token: 0x0600538B RID: 21387 RVA: 0x00189AAA File Offset: 0x00187CAA
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=srbMyPXl}You can have one of my companions and {REQUIRED_TROOP_AMOUNT} of my men to take your goods to {TARGET_TOWN}", null);
					textObject.SetTextVariable("REQUIRED_TROOP_AMOUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("TARGET_TOWN", this._targetSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x17000FA3 RID: 4003
			// (get) Token: 0x0600538C RID: 21388 RVA: 0x00189AE0 File Offset: 0x00187CE0
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					TextObject textObject = new TextObject("{=GE4DqFyl}I am still waiting for news from {TARGET_SETTLEMENT}. Thanks again for sparing your men.", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x17000FA4 RID: 4004
			// (get) Token: 0x0600538D RID: 21389 RVA: 0x00189B04 File Offset: 0x00187D04
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=EnS6NwaH}Thank you my {?PLAYER.GENDER}lady{?}lord{\\?}. I am sure your men will take care of the problem.", null);
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			// Token: 0x0600538E RID: 21390 RVA: 0x00189B30 File Offset: 0x00187D30
			public ArtisanCantSellProductsAtAFairPriceIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
				this._targetSettlement = ArtisanCantSellProductsAtAFairPriceIssueBehavior.SelectTargetSettlement(issueOwner);
				this._targetHero = this._targetSettlement.Notables.GetRandomElementWithPredicate((Hero x) => x.CanHaveCampaignIssues());
				this._rawMaterialsToBeDelivered = Campaign.Current.ObjectManager.GetObject<ItemObject>(this._possibleDeliveryItems.GetRandomElement<string>());
				this.CounterOfferHero = ArtisanCantSellProductsAtAFairPriceIssueBehavior.SelectCounterOfferHero(issueOwner);
			}

			// Token: 0x0600538F RID: 21391 RVA: 0x00189C13 File Offset: 0x00187E13
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.SettlementProsperity)
				{
					return -0.2f;
				}
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.2f;
				}
				return 0f;
			}

			// Token: 0x06005390 RID: 21392 RVA: 0x00189C36 File Offset: 0x00187E36
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Charm) >= hero.GetSkillValue(DefaultSkills.Trade)) ? DefaultSkills.Charm : DefaultSkills.Trade, 120);
			}

			// Token: 0x06005391 RID: 21393 RVA: 0x00189C64 File Offset: 0x00187E64
			protected override void LordSolutionConsequenceWithAcceptCounterOffer()
			{
				foreach (Hero hero in base.IssueOwner.CurrentSettlement.Notables)
				{
					if (hero.IsMerchant)
					{
						ChangeRelationAction.ApplyPlayerRelation(hero, (int)(2f * base.IssueDifficultyMultiplier), true, true);
					}
				}
				this.RelationshipChangeWithIssueOwner = (int)(-5f * base.IssueDifficultyMultiplier);
				TraitLevelingHelper.OnIssueSolvedThroughBetrayal(base.IssueOwner, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, MathF.Round(-50f * base.IssueDifficultyMultiplier))
				});
				this.ApplyFailureEffects();
			}

			// Token: 0x06005392 RID: 21394 RVA: 0x00189D20 File Offset: 0x00187F20
			protected override void LordSolutionConsequenceWithRefuseCounterOffer()
			{
				this.ApplyLordSolutionSuccessRewards();
			}

			// Token: 0x06005393 RID: 21395 RVA: 0x00189D28 File Offset: 0x00187F28
			public override bool LordSolutionCondition(out TextObject explanation)
			{
				if (base.IssueOwner.CurrentSettlement.OwnerClan == Clan.PlayerClan)
				{
					explanation = null;
					return true;
				}
				explanation = new TextObject("{=9y0zpKUF}You need to be the owner of this settlement!", null);
				return false;
			}

			// Token: 0x06005394 RID: 21396 RVA: 0x00189D54 File Offset: 0x00187F54
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 0, false);
			}

			// Token: 0x06005395 RID: 21397 RVA: 0x00189D6E File Offset: 0x00187F6E
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 0, false);
			}

			// Token: 0x06005396 RID: 21398 RVA: 0x00189D7F File Offset: 0x00187F7F
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				this.ApplySuccessRewards();
			}

			// Token: 0x06005397 RID: 21399 RVA: 0x00189D88 File Offset: 0x00187F88
			private void ApplySuccessRewards()
			{
				base.IssueOwner.AddPower(10f);
				this.RelationshipChangeWithIssueOwner = 5;
				foreach (Hero hero in from x in base.IssueOwner.CurrentSettlement.Notables
					where x.IsMerchant
					select x)
				{
					hero.AddPower((float)((int)(-10f * base.IssueDifficultyMultiplier)));
					ChangeRelationAction.ApplyPlayerRelation(hero, -10, true, true);
				}
				base.IssueOwner.CurrentSettlement.Town.Prosperity += 30f;
			}

			// Token: 0x06005398 RID: 21400 RVA: 0x00189E50 File Offset: 0x00188050
			private void ApplyLordSolutionSuccessRewards()
			{
				base.IssueOwner.AddPower(10f);
				this.RelationshipChangeWithIssueOwner = 10;
				this.CounterOfferHero.AddPower(-10f);
				foreach (Hero hero in base.IssueOwner.CurrentSettlement.Notables)
				{
					if (hero.IsMerchant)
					{
						if (hero != this.CounterOfferHero)
						{
							ChangeRelationAction.ApplyPlayerRelation(hero, -5, true, true);
						}
						else
						{
							ChangeRelationAction.ApplyPlayerRelation(hero, -10, true, true);
						}
					}
				}
				base.IssueOwner.CurrentSettlement.Town.Prosperity += 30f;
			}

			// Token: 0x06005399 RID: 21401 RVA: 0x00189F18 File Offset: 0x00188118
			private void ApplyFailureEffects()
			{
				base.IssueOwner.AddPower(-10f);
				foreach (Hero hero in from x in base.IssueOwner.CurrentSettlement.Notables
					where x.IsMerchant
					select x)
				{
					hero.AddPower(3f);
				}
				base.IssueOwner.CurrentSettlement.Town.Prosperity -= 10f;
			}

			// Token: 0x0600539A RID: 21402 RVA: 0x00189FC8 File Offset: 0x001881C8
			protected override void OnGameLoad()
			{
			}

			// Token: 0x0600539B RID: 21403 RVA: 0x00189FCA File Offset: 0x001881CA
			protected override void HourlyTick()
			{
			}

			// Token: 0x0600539C RID: 21404 RVA: 0x00189FCC File Offset: 0x001881CC
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(18f), this._targetSettlement, this._rawMaterialsToBeDelivered, this.RawMaterialCountToBeDelivered, this.RewardGold, this._targetHero, this.CounterOfferHero);
			}

			// Token: 0x0600539D RID: 21405 RVA: 0x0018A013 File Offset: 0x00188213
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.Common;
			}

			// Token: 0x0600539E RID: 21406 RVA: 0x0018A016 File Offset: 0x00188216
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill)
			{
				relationHero = null;
				flags = IssueBase.PreconditionFlags.None;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				relationHero = issueGiver;
				skill = null;
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x0600539F RID: 21407 RVA: 0x0018A040 File Offset: 0x00188240
			public override bool IssueStayAliveConditions()
			{
				return this.CounterOfferHero != null && this._targetHero.IsActive && this.CounterOfferHero.IsActive && this.CounterOfferHero.CurrentSettlement == base.IssueSettlement;
			}

			// Token: 0x060053A0 RID: 21408 RVA: 0x0018A079 File Offset: 0x00188279
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x04001B6E RID: 7022
			private const int BaseRewardGold = 500;

			// Token: 0x04001B6F RID: 7023
			private const int IssueDuration = 30;

			// Token: 0x04001B70 RID: 7024
			private const int QuestTimeLimit = 18;

			// Token: 0x04001B71 RID: 7025
			private const int RequiredSkillLevelForCompanion = 120;

			// Token: 0x04001B72 RID: 7026
			[CachedData]
			private readonly MBList<string> _possibleDeliveryItems = new MBList<string> { "olives", "clay", "flax", "grape", "wool", "hardwood", "hides" };

			// Token: 0x04001B73 RID: 7027
			[SaveableField(10)]
			private ItemObject _rawMaterialsToBeDelivered;

			// Token: 0x04001B74 RID: 7028
			[SaveableField(20)]
			private Settlement _targetSettlement;

			// Token: 0x04001B76 RID: 7030
			[SaveableField(40)]
			private Hero _targetHero;
		}

		// Token: 0x020006DD RID: 1757
		public class ArtisanCantSellProductsAtAFairPriceIssueQuest : QuestBase
		{
			// Token: 0x060053A1 RID: 21409 RVA: 0x0018A07B File Offset: 0x0018827B
			internal static void AutoGeneratedStaticCollectObjectsArtisanCantSellProductsAtAFairPriceIssueQuest(object o, List<object> collectedObjects)
			{
				((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x060053A2 RID: 21410 RVA: 0x0018A08C File Offset: 0x0018828C
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._rawMaterialsToBeDelivered);
				collectedObjects.Add(this._targetSettlement);
				collectedObjects.Add(this._counterOfferHero);
				collectedObjects.Add(this._targetHero);
				collectedObjects.Add(this._playerStartsQuestLog);
			}

			// Token: 0x060053A3 RID: 21411 RVA: 0x0018A0DC File Offset: 0x001882DC
			internal static object AutoGeneratedGetMemberValue_rawMaterialsToBeDelivered(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest)o)._rawMaterialsToBeDelivered;
			}

			// Token: 0x060053A4 RID: 21412 RVA: 0x0018A0E9 File Offset: 0x001882E9
			internal static object AutoGeneratedGetMemberValue_amountOfRawGoodsToBeDelivered(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest)o)._amountOfRawGoodsToBeDelivered;
			}

			// Token: 0x060053A5 RID: 21413 RVA: 0x0018A0FB File Offset: 0x001882FB
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest)o)._targetSettlement;
			}

			// Token: 0x060053A6 RID: 21414 RVA: 0x0018A108 File Offset: 0x00188308
			internal static object AutoGeneratedGetMemberValue_deliveredRawGoods(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest)o)._deliveredRawGoods;
			}

			// Token: 0x060053A7 RID: 21415 RVA: 0x0018A11A File Offset: 0x0018831A
			internal static object AutoGeneratedGetMemberValue_counterOfferHero(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest)o)._counterOfferHero;
			}

			// Token: 0x060053A8 RID: 21416 RVA: 0x0018A127 File Offset: 0x00188327
			internal static object AutoGeneratedGetMemberValue_targetHero(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest)o)._targetHero;
			}

			// Token: 0x060053A9 RID: 21417 RVA: 0x0018A134 File Offset: 0x00188334
			internal static object AutoGeneratedGetMemberValue_counterOfferGiven(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest)o)._counterOfferGiven;
			}

			// Token: 0x060053AA RID: 21418 RVA: 0x0018A146 File Offset: 0x00188346
			internal static object AutoGeneratedGetMemberValue_counterOfferRefused(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest)o)._counterOfferRefused;
			}

			// Token: 0x060053AB RID: 21419 RVA: 0x0018A158 File Offset: 0x00188358
			internal static object AutoGeneratedGetMemberValue_rewardGold(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest)o)._rewardGold;
			}

			// Token: 0x060053AC RID: 21420 RVA: 0x0018A16A File Offset: 0x0018836A
			internal static object AutoGeneratedGetMemberValue_playerStartsQuestLog(object o)
			{
				return ((ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest)o)._playerStartsQuestLog;
			}

			// Token: 0x17000FA5 RID: 4005
			// (get) Token: 0x060053AD RID: 21421 RVA: 0x0018A177 File Offset: 0x00188377
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17000FA6 RID: 4006
			// (get) Token: 0x060053AE RID: 21422 RVA: 0x0018A17A File Offset: 0x0018837A
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=sfW7oT9e}Artisan Can't Sell Products", null);
				}
			}

			// Token: 0x17000FA7 RID: 4007
			// (get) Token: 0x060053AF RID: 21423 RVA: 0x0018A188 File Offset: 0x00188388
			private TextObject PlayerStartsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=N0E8gd5H}{QUEST_GIVER.LINK} an artisan from {QUEST_GIVER_SETTLEMENT} has complained to you about not being able to sell their goods at the price they want because of the unfair local laws. {?QUEST_GIVER.GENDER}She{?}He{\\?} will pay {REWARD_AMOUNT}{GOLD_ICON} for you to take the goods to another town. You agreed to take {?QUEST_GIVER.GENDER}her{?}his{\\?} goods to {TARGET_HERO.LINK} in {TARGET_SETTLEMENT}.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("TARGET_HERO", this._targetHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_SETTLEMENT", base.QuestGiver.CurrentSettlement.Name);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("REWARD_AMOUNT", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			// Token: 0x17000FA8 RID: 4008
			// (get) Token: 0x060053B0 RID: 21424 RVA: 0x0018A228 File Offset: 0x00188428
			private TextObject SuccessQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=7fr8QDYi}{QUEST_GIVER.LINK} sends {?QUEST_GIVER.GENDER}her{?}his{\\?} regards for a fine job done with the {REWARD}{GOLD_ICON} {?QUEST_GIVER.GENDER}she{?}he{\\?} promised.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("REWARD", this._rewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			// Token: 0x17000FA9 RID: 4009
			// (get) Token: 0x060053B1 RID: 21425 RVA: 0x0018A280 File Offset: 0x00188480
			private TextObject FailQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=um4UaneZ}You have failed to deliver {REQUESTED_AMOUNT} {.%}{?(REQUESTED_AMOUNT > 1)}{PLURAL(RAW_MATERIALS)}{?}{RAW_MATERIALS}{\\?}{.%} to {TARGET_SETTLEMENT} in time as {QUEST_GIVER.LINK} asked you.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("REMAINING_AMOUNT", this._amountOfRawGoodsToBeDelivered - this._deliveredRawGoods);
					textObject.SetTextVariable("REQUESTED_AMOUNT", this._amountOfRawGoodsToBeDelivered);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("RAW_MATERIALS", this._rawMaterialsToBeDelivered.Name);
					return textObject;
				}
			}

			// Token: 0x17000FAA RID: 4010
			// (get) Token: 0x060053B2 RID: 21426 RVA: 0x0018A30C File Offset: 0x0018850C
			private TextObject FailQuestLogCounterOfferText
			{
				get
				{
					TextObject textObject = new TextObject("{=pskiLikd}After listening to the town merchants, you decided to keep the restrictions on the sale of goods. Your decision made the merchants happy but disappointed {QUEST_GIVER.LINK}.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17000FAB RID: 4011
			// (get) Token: 0x060053B3 RID: 21427 RVA: 0x0018A340 File Offset: 0x00188540
			private TextObject OnQuestCancelledDueToWarLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=vaUlAZba}Your clan is now at war with {QUEST_GIVER.LINK}. Your agreement with {QUEST_GIVER.LINK} was canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17000FAC RID: 4012
			// (get) Token: 0x060053B4 RID: 21428 RVA: 0x0018A374 File Offset: 0x00188574
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x060053B5 RID: 21429 RVA: 0x0018A3A8 File Offset: 0x001885A8
			public ArtisanCantSellProductsAtAFairPriceIssueQuest(string questId, Hero questGiver, CampaignTime duration, Settlement targetSettlement, ItemObject rawGoodsToBeDelivered, int amountOfRawGoodsToBeDelivered, int rewardGold, Hero targetHero, Hero counterOfferHero)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._targetSettlement = targetSettlement;
				this._rawMaterialsToBeDelivered = rawGoodsToBeDelivered;
				this._amountOfRawGoodsToBeDelivered = amountOfRawGoodsToBeDelivered;
				this._deliveredRawGoods = 0;
				this._counterOfferHero = counterOfferHero;
				this._targetHero = targetHero;
				this._rewardGold = rewardGold;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x060053B6 RID: 21430 RVA: 0x0018A403 File Offset: 0x00188603
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetCounterOfferDialogFlow(), this);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetDeliveryDialogFlow(), this);
			}

			// Token: 0x060053B7 RID: 21431 RVA: 0x0018A437 File Offset: 0x00188637
			protected override void HourlyTick()
			{
			}

			// Token: 0x060053B8 RID: 21432 RVA: 0x0018A43C File Offset: 0x0018863C
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=7KshRCtM}Excellent. I'll have the goods delivered to you right away.[if:convo_nonchalant]", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(new TextObject("{=6qKJ6Uzr}I believe the goods have been delivered to you.", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=6ZCAQ1S9}Great. I will be heading out soon.", null), null, null, null)
					.NpcLine(new TextObject("{=3SBDbPjD}Good to hear that! Safe journeys.", null), null, null, null, null)
					.CloseDialog()
					.PlayerOption(new TextObject("{=JOaD2BlP}In due time. Let's not be too hasty here.", null), null, null, null)
					.NpcLine(new TextObject("{=ppi6eVos}As you wish.", null), null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x060053B9 RID: 21433 RVA: 0x0018A538 File Offset: 0x00188738
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				TextObject textObject = new TextObject("{=L700FNht}Delivered {RAW_MATERIAL}", null);
				textObject.SetTextVariable("RAW_MATERIAL", this._rawMaterialsToBeDelivered.Name);
				this._playerStartsQuestLog = base.AddDiscreteLog(this.PlayerStartsQuestLogText, textObject, this._deliveredRawGoods, this._amountOfRawGoodsToBeDelivered, null, true);
				PartyBase.MainParty.ItemRoster.AddToCounts(this._rawMaterialsToBeDelivered, this._amountOfRawGoodsToBeDelivered);
				base.AddTrackedObject(this._targetSettlement);
				base.AddTrackedObject(this._targetHero);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetCounterOfferDialogFlow(), this);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetDeliveryDialogFlow(), this);
			}

			// Token: 0x060053BA RID: 21434 RVA: 0x0018A5EF File Offset: 0x001887EF
			private int GetAvailableRequestedItemCountOnPlayer(ItemObject item)
			{
				return PartyBase.MainParty.ItemRoster.GetItemNumber(item);
			}

			// Token: 0x060053BB RID: 21435 RVA: 0x0018A604 File Offset: 0x00188804
			private void BeforeGameMenuOpened(MenuCallbackArgs args)
			{
				if (!this._counterOfferGiven && this._counterOfferHero != null && Campaign.Current.GameMenuManager.NextLocation == null && GameStateManager.Current.ActiveState is MapState)
				{
					CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter, null, false, false, false, false, false, false), new ConversationCharacterData(this._counterOfferHero.CharacterObject, null, false, false, false, false, false, false));
					this._counterOfferGiven = true;
				}
			}

			// Token: 0x060053BC RID: 21436 RVA: 0x0018A678 File Offset: 0x00188878
			private DialogFlow GetCounterOfferDialogFlow()
			{
				if (base.QuestGiver.CurrentSettlement.Owner != Hero.MainHero)
				{
					TextObject textObject = new TextObject("{=riYecgOn}We have heard rumors that you have purchased goods from {QUEST_GIVER.NAME}. Well, our laws require that only merchants resident in the city can buy goods directly from the artisans.[if:convo_annoyed][ib:hip]", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					TextObject npcText = new TextObject("{=5AvvGkk4}I'm sure what you did was an honest mistake, but there are laws. Hand over the contraband to me, and this will be the end of it.", null);
					if (this._counterOfferHero.CharacterObject.GetPersona() == DefaultTraits.PersonaCurt)
					{
						npcText = new TextObject("{=PyjCZGlG}This town has laws about unauthorized trade. Turn over the goods to me now.", null);
					}
					return DialogFlow.CreateDialogFlow("start", 125).NpcLine(new TextObject("{=KSeIOHDh}(One of the merchants in the town comes to talk as you are preparing to depart.)", null), null, null, null, null).Condition(() => this._counterOfferHero == Hero.OneToOneConversationHero && !this._counterOfferRefused)
						.NpcLine(textObject, null, null, null, null)
						.NpcLine(npcText, null, null, null, null)
						.BeginPlayerOptions(null, false)
						.PlayerOption(new TextObject("{=mWLA9sfT}I don't want to break the law. You can take the goods.", null), null, null, null)
						.NpcLine(new TextObject("{=xeboujso}That's the right call. You seem a responsible type.[if:convo_nonchalant]", null), null, null, null, null)
						.Consequence(delegate
						{
							Campaign.Current.ConversationManager.ConversationEndOneShot += this.QuestFailedWithRefusal;
						})
						.CloseDialog()
						.PlayerOption(new TextObject("{=fe0uGUZb}That's just robbery under the cover of law. I'm not giving you anything.", null), null, null, null)
						.NpcLine(new TextObject("{=U9z7rvX5}Respectfully, you're making a big mistake and I think you're going to regret it.[if:convo_furious]", null), null, null, null, null)
						.Consequence(delegate
						{
							Campaign.Current.ConversationManager.ConversationEndOneShot += this.RefuseCounterOfferConsequences;
						})
						.CloseDialog()
						.EndPlayerOptions();
				}
				TextObject textObject2 = new TextObject("{=DidANRmb}My {?PLAYER.GENDER}lady{?}lord{\\?}, we have heard rumors that you have purchased goods from {QUEST_GIVER.NAME}.[ib:demure] Surely this cannot be true. Our laws require that only merchants resident in the city can buy goods directly from the artisans.", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject2, false);
				TextObject npcText2 = new TextObject("{=bbz2eyAO}Perhaps, my {?PLAYER.GENDER}lady{?}lord{\\?}, it was a mistake? If you were to relinquish the goods, it would avoid a situation that might appear, well, a bit unseemly.", null);
				return DialogFlow.CreateDialogFlow("start", 125).NpcLine(new TextObject("{=KSeIOHDh}(One of the merchants in the town comes to talk as you are preparing to depart.)", null), null, null, null, null).Condition(() => this._counterOfferHero == Hero.OneToOneConversationHero && !this._counterOfferRefused)
					.NpcLine(textObject2, null, null, null, null)
					.NpcLine(npcText2, null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=EKvwhGtE}I suppose the laws of this town bind me as well. You can take the goods.", null), null, null, null)
					.NpcLine(new TextObject("{=dSy9Hawq}A just decision, my {?PLAYER.GENDER}lady{?}lord{\\?}.", null), null, null, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += this.QuestFailedWithRefusal;
					})
					.CloseDialog()
					.PlayerOption(new TextObject("{=IUCkbHkT}I decide how the law here is applied, merchant.", null), null, null, null)
					.NpcLine(new TextObject("{=RYOuDxdu}Respectfully, my {?PLAYER.GENDER}lady{?}lord{\\?}, I must protest this. But of course you are free to do what you will.", null), null, null, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += this.RefuseCounterOfferConsequences;
					})
					.CloseDialog()
					.EndPlayerOptions();
			}

			// Token: 0x060053BD RID: 21437 RVA: 0x0018A8BC File Offset: 0x00188ABC
			private DialogFlow GetDeliveryDialogFlow()
			{
				TextObject textObject = new TextObject("{=8nwZXNTk}About the task {QUEST_GIVER.LINK} gave me...", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
				TextObject textObject2 = new TextObject("{=mr7SgjAq}Yes... {QUEST_GIVER.LINK} sent word to us. We are expecting the {.%}{RAW_MATERIALS}{.%} that {?QUEST_GIVER.GENDER}she{?}he{\\?} had.", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject2, false);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject2, false);
				textObject2.SetTextVariable("RAW_MATERIALS", this._rawMaterialsToBeDelivered.Name);
				TextObject npcSecondLine = new TextObject("{=g7hZw8LI}Have you brought {REQUESTED_AMOUNT} {.%}{?(REQUESTED_AMOUNT > 1)}{PLURAL(RAW_MATERIALS)}{?}{RAW_MATERIALS}{\\?}{.%}? I have a fat purse of {REWARD}{GOLD_ICON} for you as promised.", null);
				npcSecondLine.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
				npcSecondLine.SetTextVariable("REWARD", this._rewardGold);
				npcSecondLine.SetTextVariable("REQUESTED_AMOUNT", this._amountOfRawGoodsToBeDelivered - this._deliveredRawGoods);
				npcSecondLine.SetTextVariable("RAW_MATERIALS", this._rawMaterialsToBeDelivered.Name);
				TextObject text = new TextObject("{=jidYZW2s}Most of the goods are here, but I lost some of them along the way. I have {AVAILABLE_AMOUNT} with me.", null);
				TextObject textObject3 = new TextObject("{=bPcO3Km2}Yes, things come up, but my agreement with {QUEST_GIVER.LINK} was for a fixed amount of goods. I don't want to negotiate a new deal. Please come back when you can get the full amount.[if:convo_nervous2][ib:closed]", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject3, false);
				TextObject playerDeliverItemsFully = new TextObject("{=yKz5e5H4}Yes. I have the goods right here. I brought {REQUESTED_AMOUNT} {.%}{?(REQUESTED_AMOUNT > 1)}{PLURAL(RAW_MATERIALS)}{?}{RAW_MATERIALS}{\\?}{.%} as we agreed.", null);
				playerDeliverItemsFully.SetTextVariable("REQUESTED_AMOUNT", this._amountOfRawGoodsToBeDelivered - this._deliveredRawGoods);
				playerDeliverItemsFully.SetTextVariable("RAW_MATERIALS", this._rawMaterialsToBeDelivered.Name);
				TextObject textObject4 = new TextObject("{=S60sDU3j}Very good! Here is your money. Thank you.[if:convo_grateful]", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject4, false);
				TextObject text2 = new TextObject("{=4uKTfTg9}Sorry. I don't have anything for you this time.", null);
				TextObject npcText = new TextObject("{=JTfaqKyX}Well, try to bring it soon.[if:convo_thinking][ib:closed]", null);
				TextObject text3 = new TextObject("{=GVJS9ewr}You know, these goods are worth more to me than what you'll paying. I will keep them.", null);
				TextObject textObject5 = new TextObject("{=kWZ3cskl}What? That's a breach of contract. {QUEST_GIVER.LINK} will certainly hear about this...[if:convo_grave][ib:aggressive]", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject5, false);
				return DialogFlow.CreateDialogFlow("hero_main_options", 125).PlayerLine(textObject, null, null, null).Condition(delegate
				{
					if (this._deliveredRawGoods > 0)
					{
						npcSecondLine.SetTextVariable("REQUESTED_AMOUNT", this._amountOfRawGoodsToBeDelivered - this._deliveredRawGoods);
						playerDeliverItemsFully.SetTextVariable("REQUESTED_AMOUNT", this._amountOfRawGoodsToBeDelivered - this._deliveredRawGoods);
					}
					return Settlement.CurrentSettlement == this._targetSettlement && CharacterObject.OneToOneConversationCharacter.IsHero && CharacterObject.OneToOneConversationCharacter.HeroObject == this._targetHero;
				})
					.NpcLine(textObject2, null, null, null, null)
					.NpcLine(npcSecondLine, null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(text, null, null, null)
					.Condition(delegate
					{
						int availableRequestedItemCountOnPlayer = this.GetAvailableRequestedItemCountOnPlayer(this._rawMaterialsToBeDelivered);
						int num = this._amountOfRawGoodsToBeDelivered - this._deliveredRawGoods;
						Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("AVAILABLE_AMOUNT", availableRequestedItemCountOnPlayer);
						return availableRequestedItemCountOnPlayer < num && availableRequestedItemCountOnPlayer != 0;
					})
					.NpcLine(textObject3, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.DeliverItemsPartiallyOnConsequence))
					.CloseDialog()
					.PlayerOption(playerDeliverItemsFully, null, null, null)
					.Condition(delegate
					{
						int availableRequestedItemCountOnPlayer = this.GetAvailableRequestedItemCountOnPlayer(this._rawMaterialsToBeDelivered);
						int num = this._amountOfRawGoodsToBeDelivered - this._deliveredRawGoods;
						Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("REQUESTED_AMOUNT", this._amountOfRawGoodsToBeDelivered - this._deliveredRawGoods);
						Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("AVAILABLE_AMOUNT", num);
						return availableRequestedItemCountOnPlayer >= num && availableRequestedItemCountOnPlayer != 0;
					})
					.NpcLine(textObject4, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.DeliverItemsFullyOnConsequence))
					.CloseDialog()
					.PlayerOption(text3, null, null, null)
					.NpcLine(textObject5, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.DeliverItemsRejectOnConsequence))
					.CloseDialog()
					.PlayerOption(text2, null, null, null)
					.NpcLine(npcText, null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x060053BE RID: 21438 RVA: 0x0018ABC0 File Offset: 0x00188DC0
			private void DeliverItemsRejectOnConsequence()
			{
				TextObject textObject = new TextObject("{=yoiOIuI9}You refused to hand over the items. {QUEST_GIVER.LINK} must be furious.", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
				this.RelationshipChangeWithQuestGiver = -20;
				base.CompleteQuestWithFail(textObject);
				ChangeRelationAction.ApplyPlayerRelation(this._targetHero, -15, true, true);
			}

			// Token: 0x060053BF RID: 21439 RVA: 0x0018AC10 File Offset: 0x00188E10
			private void DeliverItemsPartiallyOnConsequence()
			{
				int availableRequestedItemCountOnPlayer = this.GetAvailableRequestedItemCountOnPlayer(this._rawMaterialsToBeDelivered);
				this._deliveredRawGoods += availableRequestedItemCountOnPlayer;
				PartyBase.MainParty.ItemRoster.AddToCounts(this._rawMaterialsToBeDelivered, -availableRequestedItemCountOnPlayer);
				base.UpdateQuestTaskStage(this._playerStartsQuestLog, this._deliveredRawGoods);
				int variable = this._amountOfRawGoodsToBeDelivered - this._deliveredRawGoods;
				TextObject textObject = new TextObject("{=ffoqz6yP}You have delivered {DELIVERED_ITEM_COUNT} units of goods from {QUEST_GIVER.NAME}.", null);
				textObject.SetTextVariable("DELIVERED_ITEM_COUNT", availableRequestedItemCountOnPlayer);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
				MBInformationManager.AddQuickInformation(textObject, 0, null, null, "");
				TextObject textObject2 = new TextObject("{=3zdK4sm2}You have to bring in amount {REQUIRED_AMOUNT} more to fulfill your end of the deal.", null);
				textObject2.SetTextVariable("REQUIRED_AMOUNT", variable);
				MBInformationManager.AddQuickInformation(textObject2, 0, null, null, "");
			}

			// Token: 0x060053C0 RID: 21440 RVA: 0x0018ACD4 File Offset: 0x00188ED4
			private void DeliverItemsFullyOnConsequence()
			{
				int num = this._amountOfRawGoodsToBeDelivered - this._deliveredRawGoods;
				this._deliveredRawGoods = this._amountOfRawGoodsToBeDelivered;
				PartyBase.MainParty.ItemRoster.AddToCounts(this._rawMaterialsToBeDelivered, -num);
				base.UpdateQuestTaskStage(this._playerStartsQuestLog, this._deliveredRawGoods);
				TextObject textObject = new TextObject("{=WSLHfiwg}You have delivered the goods from {QUEST_GIVER.NAME}.", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
				MBInformationManager.AddQuickInformation(textObject, 0, null, null, "");
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x060053C1 RID: 21441 RVA: 0x0018AD60 File Offset: 0x00188F60
			private void QuestFailedWithRefusal()
			{
				foreach (Hero hero in from x in base.QuestGiver.CurrentSettlement.Notables
					where x.IsMerchant
					select x)
				{
					ChangeRelationAction.ApplyPlayerRelation(hero, 2, true, true);
					hero.AddPower(10f);
				}
				this.RelationshipChangeWithQuestGiver = -5;
				TraitLevelingHelper.OnIssueFailed(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -50)
				});
				base.CompleteQuestWithFail(this.FailQuestLogCounterOfferText);
				this.RemoveRequestedItemsFromPlayer();
			}

			// Token: 0x060053C2 RID: 21442 RVA: 0x0018AE20 File Offset: 0x00189020
			private void RefuseCounterOfferConsequences()
			{
				if (base.QuestGiver.CurrentSettlement.Owner != Hero.MainHero)
				{
					ChangeCrimeRatingAction.Apply(base.QuestGiver.CurrentSettlement.MapFaction, 5f, true);
				}
				this._counterOfferHero.AddPower(-10f);
				this._counterOfferRefused = true;
			}

			// Token: 0x060053C3 RID: 21443 RVA: 0x0018AE78 File Offset: 0x00189078
			protected override void RegisterEvents()
			{
				CampaignEvents.BeforeGameMenuOpenedEvent.AddNonSerializedListener(this, new Action<MenuCallbackArgs>(this.BeforeGameMenuOpened));
				CampaignEvents.HeroKilledEvent.AddNonSerializedListener(this, new Action<Hero, Hero, KillCharacterAction.KillCharacterActionDetail, bool>(this.OnHeroKilled));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
			}

			// Token: 0x060053C4 RID: 21444 RVA: 0x0018AEE1 File Offset: 0x001890E1
			public override void OnHeroCanHaveCampaignIssuesInfoIsRequested(Hero hero, ref bool result)
			{
				if (hero == this._targetHero)
				{
					result = false;
				}
			}

			// Token: 0x060053C5 RID: 21445 RVA: 0x0018AEEF File Offset: 0x001890EF
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.OnQuestCancelledDueToWarLogText);
				}
			}

			// Token: 0x060053C6 RID: 21446 RVA: 0x0018AF1E File Offset: 0x0018911E
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.OnQuestCancelledDueToWarLogText, false);
			}

			// Token: 0x060053C7 RID: 21447 RVA: 0x0018AF38 File Offset: 0x00189138
			private void OnHeroKilled(Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail, bool showNotification)
			{
				if (victim == this._targetHero)
				{
					TextObject textObject = ((detail == KillCharacterAction.KillCharacterActionDetail.Lost) ? this.TargetHeroDisappearedLogText : this.TargetHeroDiedLogText);
					StringHelpers.SetCharacterProperties("QUEST_TARGET", this._targetHero.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					base.AddLog(textObject, false);
					base.CompleteQuestWithCancel(null);
					return;
				}
				if (victim == this._counterOfferHero)
				{
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x060053C8 RID: 21448 RVA: 0x0018AFB4 File Offset: 0x001891B4
			private void RemoveRequestedItemsFromPlayer()
			{
				int availableRequestedItemCountOnPlayer = this.GetAvailableRequestedItemCountOnPlayer(this._rawMaterialsToBeDelivered);
				int num = this._amountOfRawGoodsToBeDelivered - this._deliveredRawGoods;
				PartyBase.MainParty.ItemRoster.AddToCounts(this._rawMaterialsToBeDelivered, (availableRequestedItemCountOnPlayer < num) ? (-availableRequestedItemCountOnPlayer) : (-num));
			}

			// Token: 0x060053C9 RID: 21449 RVA: 0x0018AFFC File Offset: 0x001891FC
			public override void OnFailed()
			{
				base.QuestGiver.AddPower(-10f);
				base.QuestGiver.CurrentSettlement.Town.Prosperity -= 10f;
				foreach (Hero hero in from x in base.QuestGiver.CurrentSettlement.Notables
					where x.IsMerchant
					select x)
				{
					hero.AddPower(5f);
				}
			}

			// Token: 0x060053CA RID: 21450 RVA: 0x0018B0AC File Offset: 0x001892AC
			protected override void OnFinalize()
			{
			}

			// Token: 0x060053CB RID: 21451 RVA: 0x0018B0AE File Offset: 0x001892AE
			protected override void AfterLoad()
			{
			}

			// Token: 0x060053CC RID: 21452 RVA: 0x0018B0B0 File Offset: 0x001892B0
			protected override void OnCompleteWithSuccess()
			{
				base.QuestGiver.AddPower(15f);
				this.RelationshipChangeWithQuestGiver = 10;
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 50)
				});
				foreach (Hero hero in from x in base.QuestGiver.CurrentSettlement.Notables
					where x.IsMerchant
					select x)
				{
					hero.AddPower(-5f);
					ChangeRelationAction.ApplyPlayerRelation(hero, -5, true, true);
				}
				base.QuestGiver.CurrentSettlement.Town.Prosperity += 30f;
				base.AddLog(this.SuccessQuestLogText, false);
				base.RemoveTrackedObject(this._targetSettlement);
				base.RemoveTrackedObject(this._targetHero);
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this._rewardGold, false);
			}

			// Token: 0x060053CD RID: 21453 RVA: 0x0018B1C8 File Offset: 0x001893C8
			protected override void OnTimedOut()
			{
				this.OnFailed();
				this.RelationshipChangeWithQuestGiver = -5;
				base.AddLog(this.FailQuestLogText, false);
			}

			// Token: 0x04001B77 RID: 7031
			[SaveableField(10)]
			private readonly ItemObject _rawMaterialsToBeDelivered;

			// Token: 0x04001B78 RID: 7032
			[SaveableField(20)]
			private readonly int _amountOfRawGoodsToBeDelivered;

			// Token: 0x04001B79 RID: 7033
			[SaveableField(30)]
			private readonly Settlement _targetSettlement;

			// Token: 0x04001B7A RID: 7034
			[SaveableField(40)]
			private int _deliveredRawGoods;

			// Token: 0x04001B7B RID: 7035
			[SaveableField(100)]
			private Hero _counterOfferHero;

			// Token: 0x04001B7C RID: 7036
			[SaveableField(60)]
			private Hero _targetHero;

			// Token: 0x04001B7D RID: 7037
			[SaveableField(70)]
			private bool _counterOfferGiven;

			// Token: 0x04001B7E RID: 7038
			[SaveableField(80)]
			private bool _counterOfferRefused;

			// Token: 0x04001B7F RID: 7039
			[SaveableField(90)]
			private int _rewardGold;

			// Token: 0x04001B80 RID: 7040
			[SaveableField(212)]
			private JournalLog _playerStartsQuestLog;
		}

		// Token: 0x020006DE RID: 1758
		public class ArtisanCantSellProductsAtAFairPriceIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x060053D6 RID: 21462 RVA: 0x0018B2AC File Offset: 0x001894AC
			public ArtisanCantSellProductsAtAFairPriceIssueTypeDefiner()
				: base(480000)
			{
			}

			// Token: 0x060053D7 RID: 21463 RVA: 0x0018B2B9 File Offset: 0x001894B9
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssue), 1, null);
				base.AddClassDefinition(typeof(ArtisanCantSellProductsAtAFairPriceIssueBehavior.ArtisanCantSellProductsAtAFairPriceIssueQuest), 2, null);
			}
		}
	}
}
