using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000378 RID: 888
	public class TheConquestOfSettlementIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x060033BB RID: 13243 RVA: 0x000D4BBC File Offset: 0x000D2DBC
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x060033BC RID: 13244 RVA: 0x000D4BD8 File Offset: 0x000D2DD8
		private void OnCheckForIssue(Hero hero)
		{
			Settlement relatedObject;
			if (this.ConditionsHold(hero, out relatedObject))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnStartIssue), typeof(TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue), IssueBase.IssueFrequency.VeryCommon, relatedObject));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x060033BD RID: 13245 RVA: 0x000D4C40 File Offset: 0x000D2E40
		private bool ConditionsHold(Hero issueGiver, out Settlement targetSettlement)
		{
			targetSettlement = null;
			if (issueGiver.IsLord && issueGiver.MapFaction.IsKingdomFaction && issueGiver.IsFactionLeader && !issueGiver.IsPrisoner && issueGiver.GetMapPoint() != null)
			{
				if (issueGiver.Clan.Settlements.Any((Settlement x) => x.IsFortification))
				{
					float num = Campaign.Current.GetAverageDistanceBetweenClosestTwoTownsWithNavigationType(MobileParty.NavigationType.Default) * 2f;
					MBList<Settlement> mblist = new MBList<Settlement>();
					CampaignVec2 campaignPosition = issueGiver.GetCampaignPosition();
					foreach (Town town in Campaign.Current.AllTowns)
					{
						if (town.MapFaction.IsAtWarWith(issueGiver.MapFaction) && Campaign.Current.Models.MapDistanceModel.GetDistance(town.Settlement, campaignPosition, false, MobileParty.NavigationType.Default) < num)
						{
							mblist.Add(town.Settlement);
						}
					}
					foreach (Town town2 in Campaign.Current.AllCastles)
					{
						if (town2.MapFaction.IsAtWarWith(issueGiver.MapFaction) && Campaign.Current.Models.MapDistanceModel.GetDistance(town2.Settlement, campaignPosition, false, MobileParty.NavigationType.Default) < num)
						{
							mblist.Add(town2.Settlement);
						}
					}
					if (mblist.Count > 0)
					{
						targetSettlement = mblist.GetRandomElement<Settlement>();
					}
				}
			}
			return targetSettlement != null;
		}

		// Token: 0x060033BE RID: 13246 RVA: 0x000D4E00 File Offset: 0x000D3000
		private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
		{
			PotentialIssueData potentialIssueData = pid;
			return new TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue(issueOwner, (Settlement)potentialIssueData.RelatedObject);
		}

		// Token: 0x060033BF RID: 13247 RVA: 0x000D4E26 File Offset: 0x000D3026
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x04000EB6 RID: 3766
		private const IssueBase.IssueFrequency TheConquestOfSettlementIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x02000755 RID: 1877
		public class TheConquestOfSettlementIssue : IssueBase
		{
			// Token: 0x06005F1A RID: 24346 RVA: 0x001B5A4F File Offset: 0x001B3C4F
			internal static void AutoGeneratedStaticCollectObjectsTheConquestOfSettlementIssue(object o, List<object> collectedObjects)
			{
				((TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005F1B RID: 24347 RVA: 0x001B5A5D File Offset: 0x001B3C5D
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._targetSettlement);
			}

			// Token: 0x06005F1C RID: 24348 RVA: 0x001B5A72 File Offset: 0x001B3C72
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue)o)._targetSettlement;
			}

			// Token: 0x1700133A RID: 4922
			// (get) Token: 0x06005F1D RID: 24349 RVA: 0x001B5A7F File Offset: 0x001B3C7F
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=mvzh0HVk}The Conquest of {TARGET_SETTLEMENT}", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700133B RID: 4923
			// (get) Token: 0x06005F1E RID: 24350 RVA: 0x001B5AA4 File Offset: 0x001B3CA4
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=xeZR3r5u}{QUEST_GIVER.LINK} wants you siege and take over the {TARGET_SETTLEMENT}", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700133C RID: 4924
			// (get) Token: 0x06005F1F RID: 24351 RVA: 0x001B5AED File Offset: 0x001B3CED
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=Oi20UrO2}Our war with the {TARGET_SETTLEMENT_FACTION_INFORMAL_NAME} is going well enough. But there are some who say that we don't have enough to show for all the blood and silver we've spent. A clear victory at this stage would do a lot of good. I think I would like to see our banner flying from the towers of {TARGET_SETTLEMENT}.[ib:normal2][if:convo_thinking]", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT_FACTION_INFORMAL_NAME", this._targetSettlement.MapFaction.InformalName);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700133D RID: 4925
			// (get) Token: 0x06005F20 RID: 24352 RVA: 0x001B5B30 File Offset: 0x001B3D30
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=qKrUyqsD}Of course, my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}. But sieges are always costly...", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700133E RID: 4926
			// (get) Token: 0x06005F21 RID: 24353 RVA: 0x001B5B64 File Offset: 0x001B3D64
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=yf3NVFi0}Yes, they are. That's why I am offering you the sum of {REWARD_GOLD}{GOLD_ICON} if you can take {TARGET_SETTLEMENT} within {TIME_LIMIT} days.[if:convo_thinking] I count you among the most resourceful of my captains. I think you can do this, with courage, Heaven's favor and a bit of luck. Can I tell my other lords that you will do this?", null);
					textObject.SetTextVariable("REWARD_GOLD", this.RewardGold);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					textObject.SetTextVariable("TIME_LIMIT", 60);
					return textObject;
				}
			}

			// Token: 0x1700133F RID: 4927
			// (get) Token: 0x06005F22 RID: 24354 RVA: 0x001B5BB3 File Offset: 0x001B3DB3
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=scmTEn90}You may tell them. {TARGET_SETTLEMENT} will be ours within 60 days.", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001340 RID: 4928
			// (get) Token: 0x06005F23 RID: 24355 RVA: 0x001B5BD7 File Offset: 0x001B3DD7
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001341 RID: 4929
			// (get) Token: 0x06005F24 RID: 24356 RVA: 0x001B5BDA File Offset: 0x001B3DDA
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001342 RID: 4930
			// (get) Token: 0x06005F25 RID: 24357 RVA: 0x001B5BDD File Offset: 0x001B3DDD
			protected override int RewardGold
			{
				get
				{
					return 20000;
				}
			}

			// Token: 0x06005F26 RID: 24358 RVA: 0x001B5BE4 File Offset: 0x001B3DE4
			public TheConquestOfSettlementIssue(Hero issueOwner, Settlement targetSettlement)
				: base(issueOwner, CampaignTime.DaysFromNow(60f))
			{
				this._targetSettlement = targetSettlement;
			}

			// Token: 0x06005F27 RID: 24359 RVA: 0x001B5BFE File Offset: 0x001B3DFE
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.SettlementSecurity)
				{
					return -1f;
				}
				if (issueEffect == DefaultIssueEffects.SettlementLoyalty)
				{
					return -1f;
				}
				return 0f;
			}

			// Token: 0x06005F28 RID: 24360 RVA: 0x001B5C21 File Offset: 0x001B3E21
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005F29 RID: 24361 RVA: 0x001B5C23 File Offset: 0x001B3E23
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005F2A RID: 24362 RVA: 0x001B5C25 File Offset: 0x001B3E25
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssueQuest(questId, base.IssueOwner, this._targetSettlement, CampaignTime.DaysFromNow(60f), this.RewardGold);
			}

			// Token: 0x06005F2B RID: 24363 RVA: 0x001B5C49 File Offset: 0x001B3E49
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x06005F2C RID: 24364 RVA: 0x001B5C4C File Offset: 0x001B3E4C
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill)
			{
				relationHero = null;
				skill = null;
				flags = IssueBase.PreconditionFlags.None;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (issueGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				if (Clan.PlayerClan.Kingdom != issueGiver.MapFaction)
				{
					flags |= IssueBase.PreconditionFlags.NotInSameFaction;
				}
				if (Clan.PlayerClan.IsUnderMercenaryService)
				{
					flags |= IssueBase.PreconditionFlags.ClanIsMercenary;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005F2D RID: 24365 RVA: 0x001B5CD0 File Offset: 0x001B3ED0
			public override bool IssueStayAliveConditions()
			{
				if (this._targetSettlement.MapFaction.IsAtWarWith(base.IssueOwner.MapFaction) && base.IssueOwner.MapFaction.IsKingdomFaction)
				{
					return base.IssueOwner.Clan.Settlements.Any((Settlement x) => x.IsFortification);
				}
				return false;
			}

			// Token: 0x06005F2E RID: 24366 RVA: 0x001B5D42 File Offset: 0x001B3F42
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x04001DE6 RID: 7654
			private const int QuestTimeLimit = 60;

			// Token: 0x04001DE7 RID: 7655
			[SaveableField(10)]
			private Settlement _targetSettlement;
		}

		// Token: 0x02000756 RID: 1878
		public class TheConquestOfSettlementIssueQuest : QuestBase
		{
			// Token: 0x06005F2F RID: 24367 RVA: 0x001B5D44 File Offset: 0x001B3F44
			internal static void AutoGeneratedStaticCollectObjectsTheConquestOfSettlementIssueQuest(object o, List<object> collectedObjects)
			{
				((TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005F30 RID: 24368 RVA: 0x001B5D52 File Offset: 0x001B3F52
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._targetSettlement);
			}

			// Token: 0x06005F31 RID: 24369 RVA: 0x001B5D67 File Offset: 0x001B3F67
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssueQuest)o)._targetSettlement;
			}

			// Token: 0x17001343 RID: 4931
			// (get) Token: 0x06005F32 RID: 24370 RVA: 0x001B5D74 File Offset: 0x001B3F74
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=mvzh0HVk}The Conquest of {TARGET_SETTLEMENT}", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001344 RID: 4932
			// (get) Token: 0x06005F33 RID: 24371 RVA: 0x001B5D98 File Offset: 0x001B3F98
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001345 RID: 4933
			// (get) Token: 0x06005F34 RID: 24372 RVA: 0x001B5D9C File Offset: 0x001B3F9C
			private TextObject QuestStartedLog
			{
				get
				{
					TextObject textObject = new TextObject("{=b1T6qywr}{QUEST_GIVER.LINK} from {QUEST_GIVER.FACTION} asked you to take over {TARGET_SETTLEMENT} in the name of {QUEST_GIVER.FACTION} to fortify war efforts. {QUEST_GIVER.LINK} said {?QUEST_GIVER.GENDER}she{?}he{\\?} will aid you with {REWARD}{GOLD_ICON} once the {TARGET_SETTLEMENT} is fallen.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, true);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					textObject.SetTextVariable("REWARD", this.RewardGold);
					return textObject;
				}
			}

			// Token: 0x17001346 RID: 4934
			// (get) Token: 0x06005F35 RID: 24373 RVA: 0x001B5DF8 File Offset: 0x001B3FF8
			private TextObject WarDeclaredQuestCancelLog
			{
				get
				{
					TextObject textObject = new TextObject("{=PakhagOy}Your clan is now at war with {QUEST_GIVER.LINK}'s lord. Your agreement with {QUEST_GIVER.LINK} was canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001347 RID: 4935
			// (get) Token: 0x06005F36 RID: 24374 RVA: 0x001B5E2C File Offset: 0x001B402C
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001348 RID: 4936
			// (get) Token: 0x06005F37 RID: 24375 RVA: 0x001B5E60 File Offset: 0x001B4060
			private TextObject QuestTimeOutFailLog
			{
				get
				{
					TextObject textObject = new TextObject("{=lEcg67Qk}You have failed to take over {TARGET_SETTLEMENT} in time. {QUEST_GIVER.LINK} is disappointed that you have failed to take the fortress in time.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001349 RID: 4937
			// (get) Token: 0x06005F38 RID: 24376 RVA: 0x001B5EAC File Offset: 0x001B40AC
			private TextObject QuestSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=6d2VIgH3}{QUEST_GIVER.LINK}: Thank you. My lords see you as an example, and see your conquest of {TARGET_SETTLEMENT} as be a stepping stone toward further victories. {?QUEST_GIVER.GENDER}She{?}He{\\?} is grateful for your service and gave you {REWARD}{GOLD_ICON} denars.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					textObject.SetTextVariable("REWARD", this.RewardGold);
					return textObject;
				}
			}

			// Token: 0x1700134A RID: 4938
			// (get) Token: 0x06005F39 RID: 24377 RVA: 0x001B5F08 File Offset: 0x001B4108
			private TextObject QuestLesserSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=1NtZ4BJh}{QUEST_GIVER.LINK}: Thank you. My lords see the conquest of {TARGET_SETTLEMENT} was a stepping stone toward further victories. {?QUEST_GIVER.GENDER}She{?}He{\\?} is grateful for your service. Because you didn't lead the army, {?QUEST_GIVER.GENDER}she{?}he{\\?} gave you {LESSER_REWARD}{GOLD_ICON} denars.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700134B RID: 4939
			// (get) Token: 0x06005F3A RID: 24378 RVA: 0x001B5F54 File Offset: 0x001B4154
			private TextObject TargetSettlementTakenByAnotherFaction
			{
				get
				{
					TextObject textObject = new TextObject("{=diUtbbaH}{TARGET_SETTLEMENT} is taken by {NEW_OWNER_FACTION}. Your agreement with {QUEST_GIVER.LINK} is no longer valid.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700134C RID: 4940
			// (get) Token: 0x06005F3B RID: 24379 RVA: 0x001B5FA0 File Offset: 0x001B41A0
			private TextObject TargetSettlementTakenByPlayerFaction
			{
				get
				{
					TextObject textObject = new TextObject("{=bEak0k5N}{TARGET_SETTLEMENT} is taken. You did not participate in this battle. Your agreement with {QUEST_GIVER.LINK} is moot.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700134D RID: 4941
			// (get) Token: 0x06005F3C RID: 24380 RVA: 0x001B5FEC File Offset: 0x001B41EC
			private TextObject LeftFaction
			{
				get
				{
					TextObject textObject = new TextObject("{=d8TeoRNf}You are no longer in the same faction with {QUEST_GIVER.LINK}. Your agreement with {QUEST_GIVER.LINK} is no longer valid.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700134E RID: 4942
			// (get) Token: 0x06005F3D RID: 24381 RVA: 0x001B6020 File Offset: 0x001B4220
			private TextObject DefectedToAnotherFaction
			{
				get
				{
					TextObject textObject = new TextObject("{=8iVkBa6D}{TARGET_SETTLEMENT_OWNER.LINK} has defected to {FACTION_NAME} along with {TARGET_SETTLEMENT}. Your agreement with {QUEST_GIVER.LINK} is moot.", null);
					StringHelpers.SetCharacterProperties("TARGET_SETTLEMENT_OWNER", this._targetSettlement.OwnerClan.Leader.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700134F RID: 4943
			// (get) Token: 0x06005F3E RID: 24382 RVA: 0x001B608C File Offset: 0x001B428C
			private TextObject NoLongerEnemy
			{
				get
				{
					TextObject textObject = new TextObject("{=HknxaCpK}{TARGET_SETTLEMENT_OWNER.FACTION} and {QUEST_GIVER.FACTION} had made peace. Your agreement with {QUEST_GIVER.LINK} is moot.", null);
					StringHelpers.SetCharacterProperties("TARGET_SETTLEMENT_OWNER", this._targetSettlement.OwnerClan.Leader.CharacterObject, textObject, true);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, true);
					return textObject;
				}
			}

			// Token: 0x06005F3F RID: 24383 RVA: 0x001B60E0 File Offset: 0x001B42E0
			public TheConquestOfSettlementIssueQuest(string questId, Hero questGiver, Settlement targetSettlement, CampaignTime duration, int rewardGold)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._targetSettlement = targetSettlement;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005F40 RID: 24384 RVA: 0x001B6104 File Offset: 0x001B4304
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=QP3BbOW3}Very good. You have my blessing to summon an army if you wish, or, if you prefer to strike quickly, you may do so on your own...[ib:hip][if:convo_mocking_aristocratic]", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				TextObject textObject = new TextObject("{=ICNtSonV}How are your preparations to take {TARGET_SETTLEMENT} coming along, {PLAYER.NAME}? I have assured my other lords that you will take it, so it will look bad if you fail.", null);
				textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
				TextObject textObject2 = new TextObject("{=m4pZhnyd}They are going as planned, my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}...", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject2, false);
				TextObject textObject3 = new TextObject("{=jFXkosnJ}This may be tricky, my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}...", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject3, false);
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(textObject, null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject2, null, null, null)
					.NpcLine(new TextObject("{=opMDusHz}Good. I look forward to presenting you with your reward.", null), null, null, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += MapEventHelper.OnConversationEnd;
					})
					.CloseDialog()
					.PlayerOption(textObject3, null, null, null)
					.NpcLine(new TextObject("{=R85IMErK}Well, if you fail we will deal with that, but I would prefer not to.", null), null, null, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += MapEventHelper.OnConversationEnd;
					})
					.CloseDialog()
					.EndPlayerOptions();
			}

			// Token: 0x06005F41 RID: 24385 RVA: 0x001B628E File Offset: 0x001B448E
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddLog(this.QuestStartedLog, false);
				base.AddTrackedObject(this._targetSettlement);
			}

			// Token: 0x06005F42 RID: 24386 RVA: 0x001B62B0 File Offset: 0x001B44B0
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005F43 RID: 24387 RVA: 0x001B62B4 File Offset: 0x001B44B4
			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
				CampaignEvents.SiegeCompletedEvent.AddNonSerializedListener(this, new Action<Settlement, MobileParty, bool, MapEvent.BattleTypes>(this.OnSiegeCompleted));
				CampaignEvents.OnSettlementOwnerChangedEvent.AddNonSerializedListener(this, new Action<Settlement, bool, Hero, Hero, Hero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail>(this.OnSettlementOwnerChanged));
				CampaignEvents.MakePeace.AddNonSerializedListener(this, new Action<IFaction, IFaction, MakePeaceAction.MakePeaceDetail>(this.OnPeaceDeclared));
			}

			// Token: 0x06005F44 RID: 24388 RVA: 0x001B634B File Offset: 0x001B454B
			private void OnPeaceDeclared(IFaction faction1, IFaction faction2, MakePeaceAction.MakePeaceDetail detail)
			{
				if (!base.QuestGiver.MapFaction.IsAtWarWith(this._targetSettlement.MapFaction))
				{
					base.CompleteQuestWithCancel(this.NoLongerEnemy);
				}
			}

			// Token: 0x06005F45 RID: 24389 RVA: 0x001B6378 File Offset: 0x001B4578
			private void OnSettlementOwnerChanged(Settlement settlement, bool openToClaim, Hero newOwner, Hero oldOwner, Hero capturerHero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail detail)
			{
				if (base.IsOngoing && settlement == this._targetSettlement)
				{
					if (newOwner == Hero.MainHero && detail == ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail.ByBarter)
					{
						this.QuestSuccess(2);
						return;
					}
					if (newOwner.MapFaction != base.QuestGiver.MapFaction && !newOwner.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
					{
						TextObject targetSettlementTakenByAnotherFaction = this.TargetSettlementTakenByAnotherFaction;
						targetSettlementTakenByAnotherFaction.SetTextVariable("NEW_OWNER_FACTION", newOwner.MapFaction.EncyclopediaLinkWithName);
						base.CompleteQuestWithCancel(targetSettlementTakenByAnotherFaction);
					}
				}
			}

			// Token: 0x06005F46 RID: 24390 RVA: 0x001B63FC File Offset: 0x001B45FC
			private void OnSiegeCompleted(Settlement siegeSettlement, MobileParty attackerParty, bool isWin, MapEvent.BattleTypes battleType)
			{
				if (isWin && siegeSettlement == this._targetSettlement)
				{
					if (attackerParty.MapFaction == base.QuestGiver.MapFaction)
					{
						if (attackerParty == MobileParty.MainParty)
						{
							this.QuestSuccess(10);
							return;
						}
						if (siegeSettlement.Party.MapEvent.InvolvedParties.Contains(PartyBase.MainParty))
						{
							this.QuestLesserSuccess();
							return;
						}
						base.CompleteQuestWithCancel(this.TargetSettlementTakenByPlayerFaction);
						return;
					}
					else
					{
						TextObject targetSettlementTakenByAnotherFaction = this.TargetSettlementTakenByAnotherFaction;
						targetSettlementTakenByAnotherFaction.SetTextVariable("NEW_OWNER_FACTION", attackerParty.MapFaction.EncyclopediaLinkWithName);
						base.CompleteQuestWithCancel(targetSettlementTakenByAnotherFaction);
					}
				}
			}

			// Token: 0x06005F47 RID: 24391 RVA: 0x001B6494 File Offset: 0x001B4694
			private void QuestLesserSuccess()
			{
				TextObject questLesserSuccessLog = this.QuestLesserSuccessLog;
				int num = this.RewardGold / 4;
				questLesserSuccessLog.SetTextVariable("LESSER_REWARD", num);
				base.AddLog(questLesserSuccessLog, false);
				GainRenownAction.Apply(Hero.MainHero, 5f, false);
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, num, false);
				this.RelationshipChangeWithQuestGiver = 1;
				foreach (Settlement settlement in from x in base.QuestGiver.Clan.Settlements
					where x.IsFortification
					select x)
				{
					settlement.Town.Security += 2f;
					settlement.Town.Loyalty += 2f;
				}
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005F48 RID: 24392 RVA: 0x001B6584 File Offset: 0x001B4784
			private void QuestSuccess(int boost)
			{
				base.AddLog(this.QuestSuccessLog, false);
				this.RelationshipChangeWithQuestGiver = 5;
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this.RewardGold, false);
				foreach (Settlement settlement in from x in base.QuestGiver.Clan.Settlements
					where x.IsFortification
					select x)
				{
					settlement.Town.Security += (float)boost;
					settlement.Town.Loyalty += (float)boost;
				}
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005F49 RID: 24393 RVA: 0x001B664C File Offset: 0x001B484C
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x06005F4A RID: 24394 RVA: 0x001B6660 File Offset: 0x001B4860
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (clan == Clan.PlayerClan && oldKingdom == base.QuestGiver.MapFaction)
				{
					base.AddLog(this.LeftFaction, false);
					base.CompleteQuestWithFail(null);
					return;
				}
				if (!clan.Settlements.Contains(this._targetSettlement))
				{
					if (base.QuestGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
					{
						base.CompleteQuestWithCancel(this.WarDeclaredQuestCancelLog);
					}
					return;
				}
				if (newKingdom == base.QuestGiver.MapFaction)
				{
					this.QuestSuccess(1);
					return;
				}
				TextObject defectedToAnotherFaction = this.DefectedToAnotherFaction;
				defectedToAnotherFaction.SetTextVariable("FACTION_NAME", newKingdom.EncyclopediaLinkWithName);
				base.CompleteQuestWithCancel(defectedToAnotherFaction);
			}

			// Token: 0x06005F4B RID: 24395 RVA: 0x001B670B File Offset: 0x001B490B
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.WarDeclaredQuestCancelLog, false);
			}

			// Token: 0x06005F4C RID: 24396 RVA: 0x001B6723 File Offset: 0x001B4923
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x06005F4D RID: 24397 RVA: 0x001B672C File Offset: 0x001B492C
			protected override void OnTimedOut()
			{
				base.AddLog(this.QuestTimeOutFailLog, false);
				this.RelationshipChangeWithQuestGiver = -10;
				foreach (Settlement settlement in from x in base.QuestGiver.Clan.Settlements
					where x.IsFortification
					select x)
				{
					settlement.Town.Security += -10f;
					settlement.Town.Loyalty += -10f;
				}
			}

			// Token: 0x04001DE8 RID: 7656
			private const int SuccessLoyaltySecurityBoost = 10;

			// Token: 0x04001DE9 RID: 7657
			private const int LesserSuccessLoyaltySecurityBoost = 2;

			// Token: 0x04001DEA RID: 7658
			private const int SuccessRelationBoost = 5;

			// Token: 0x04001DEB RID: 7659
			private const int LesserSuccessRelationBoost = 1;

			// Token: 0x04001DEC RID: 7660
			private const int TimeoutSecurityLoyaltyPenalty = -10;

			// Token: 0x04001DED RID: 7661
			private const int TimeoutRelationyPenalty = -10;

			// Token: 0x04001DEE RID: 7662
			[SaveableField(10)]
			private Settlement _targetSettlement;
		}

		// Token: 0x02000757 RID: 1879
		public class TheConquestOfSettlementIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005F50 RID: 24400 RVA: 0x001B6802 File Offset: 0x001B4A02
			public TheConquestOfSettlementIssueTypeDefiner()
				: base(620000)
			{
			}

			// Token: 0x06005F51 RID: 24401 RVA: 0x001B680F File Offset: 0x001B4A0F
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue), 1, null);
				base.AddClassDefinition(typeof(TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssueQuest), 2, null);
			}
		}
	}
}
