using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.CampaignSystem.Settlements.Locations;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;

namespace TaleWorlds.CampaignSystem.TournamentGames
{
	// Token: 0x020002CD RID: 717
	public class FightTournamentGame : TournamentGame
	{
		// Token: 0x060026C3 RID: 9923 RVA: 0x000A10F8 File Offset: 0x0009F2F8
		internal static void AutoGeneratedStaticCollectObjectsFightTournamentGame(object o, List<object> collectedObjects)
		{
			((FightTournamentGame)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060026C4 RID: 9924 RVA: 0x000A1106 File Offset: 0x0009F306
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x1700097E RID: 2430
		// (get) Token: 0x060026C5 RID: 9925 RVA: 0x000A110F File Offset: 0x0009F30F
		public override int MaxTeamSize
		{
			get
			{
				return 4;
			}
		}

		// Token: 0x1700097F RID: 2431
		// (get) Token: 0x060026C6 RID: 9926 RVA: 0x000A1112 File Offset: 0x0009F312
		public override int MaxTeamNumberPerMatch
		{
			get
			{
				return 4;
			}
		}

		// Token: 0x17000980 RID: 2432
		// (get) Token: 0x060026C7 RID: 9927 RVA: 0x000A1115 File Offset: 0x0009F315
		public override int RemoveTournamentAfterDays
		{
			get
			{
				return 15;
			}
		}

		// Token: 0x17000981 RID: 2433
		// (get) Token: 0x060026C8 RID: 9928 RVA: 0x000A1119 File Offset: 0x0009F319
		public override int MaximumParticipantCount
		{
			get
			{
				return 16;
			}
		}

		// Token: 0x060026C9 RID: 9929 RVA: 0x000A111D File Offset: 0x0009F31D
		public FightTournamentGame(Town town)
			: base(town, null)
		{
			base.Mode = TournamentGame.QualificationMode.TeamScore;
		}

		// Token: 0x060026CA RID: 9930 RVA: 0x000A1130 File Offset: 0x0009F330
		public override bool CanBeAParticipant(CharacterObject character, bool considerSkills)
		{
			if (!character.IsHero)
			{
				return character.Tier >= 3;
			}
			return !considerSkills || character.HeroObject.GetSkillValue(DefaultSkills.OneHanded) >= 100 || character.HeroObject.GetSkillValue(DefaultSkills.TwoHanded) >= 100;
		}

		// Token: 0x060026CB RID: 9931 RVA: 0x000A1184 File Offset: 0x0009F384
		public override TextObject GetMenuText()
		{
			int num = this.GetParticipantCharacters(Settlement.CurrentSettlement, false).Count((CharacterObject p) => p.IsHero);
			TextObject textObject = new TextObject("{=!}{TOURNAMENT_EXPLANATION} {PRIZE_EXPLANATION}", null);
			textObject.SetTextVariable("TOURNAMENT_EXPLANATION", GameTexts.FindText("str_fighting_menu_text", null));
			TextObject textObject2;
			if (num > 0)
			{
				textObject2 = new TextObject("{=GuWWKgEm}As you approach the arena, you overhear gossip about the contestants and prizes. Apparently there {?(NOBLE_COUNT > 1)}are {NOBLE_COUNT} lords{?}is 1 lord{\\?} with renowned fighting skills present in the city who plan to enter the tournament. Given this turnout, the organizers are offering {.a} \"{.%}{TOURNAMENT_PRIZE}{.%}\" for the victor.", null);
				textObject2.SetTextVariable("NOBLE_COUNT", num);
				textObject2.SetTextVariable("TOURNAMENT_PRIZE", base.Prize.Name);
			}
			else
			{
				textObject2 = new TextObject("{=mnAdqeGu}As you approach the arena, you overhear gossip about the contestants and prizes. Apparently there are no lords who plan to compete, but the winner will still receive a {TOURNAMENT_PRIZE}.", null);
				textObject2.SetTextVariable("TOURNAMENT_PRIZE", base.Prize.Name);
			}
			textObject.SetTextVariable("PRIZE_EXPLANATION", textObject2);
			return textObject;
		}

		// Token: 0x060026CC RID: 9932 RVA: 0x000A124C File Offset: 0x0009F44C
		public override void OpenMission(Settlement settlement, bool isPlayerParticipating)
		{
			int upgradeLevel = (settlement.IsTown ? settlement.Town.GetWallLevel() : 1);
			SandBoxMission.OpenTournamentFightMission(LocationComplex.Current.GetScene("arena", upgradeLevel), this, settlement, settlement.Culture, isPlayerParticipating);
		}

		// Token: 0x060026CD RID: 9933 RVA: 0x000A1290 File Offset: 0x0009F490
		public override MBList<CharacterObject> GetParticipantCharacters(Settlement settlement, bool includePlayer = true)
		{
			MBList<CharacterObject> mblist = new MBList<CharacterObject>();
			if (includePlayer)
			{
				mblist.Add(CharacterObject.PlayerCharacter);
			}
			int num = 0;
			while (num < settlement.Parties.Count && mblist.Count < this.MaximumParticipantCount)
			{
				Hero leaderHero = settlement.Parties[num].LeaderHero;
				if (this.CanNpcJoinTournament(leaderHero, mblist, true))
				{
					if (leaderHero.CurrentSettlement != settlement)
					{
						Debug.Print(leaderHero.StringId + " is in settlement.Parties list but current settlement is not, tournament settlement: " + settlement.StringId, 0, Debug.DebugColor.White, 17592186044416UL);
					}
					mblist.Add(leaderHero.CharacterObject);
				}
				num++;
			}
			int num2 = 0;
			while (num2 < settlement.HeroesWithoutParty.Count && mblist.Count < this.MaximumParticipantCount)
			{
				Hero hero = settlement.HeroesWithoutParty[num2];
				if (this.CanNpcJoinTournament(hero, mblist, true) && hero.IsLord)
				{
					if (hero.CurrentSettlement != settlement)
					{
						Debug.Print(hero.StringId + " is in settlement.HeroesWithoutParty list but current settlement is not, tournament settlement: " + settlement.StringId, 0, Debug.DebugColor.White, 17592186044416UL);
					}
					mblist.Add(hero.CharacterObject);
				}
				num2++;
			}
			int num3 = 0;
			while (num3 < settlement.HeroesWithoutParty.Count && mblist.Count < this.MaximumParticipantCount)
			{
				Hero hero2 = settlement.HeroesWithoutParty[num3];
				if (this.CanNpcJoinTournament(hero2, mblist, true) && !hero2.IsLord)
				{
					if (hero2.CurrentSettlement != settlement)
					{
						Debug.Print(hero2.StringId + " is in settlement.HeroesWithoutParty list but current settlement is not, tournament settlement: " + settlement.StringId, 0, Debug.DebugColor.White, 17592186044416UL);
					}
					mblist.Add(hero2.CharacterObject);
				}
				num3++;
			}
			int num4 = 0;
			while (num4 < settlement.Parties.Count && mblist.Count < this.MaximumParticipantCount)
			{
				foreach (TroopRosterElement troopRosterElement in settlement.Parties[num4].MemberRoster.GetTroopRoster())
				{
					if (mblist.Count >= this.MaximumParticipantCount)
					{
						break;
					}
					CharacterObject character = troopRosterElement.Character;
					if (character.IsHero && character.HeroObject.Clan == Clan.PlayerClan && this.CanNpcJoinTournament(character.HeroObject, mblist, true))
					{
						if (character.HeroObject.CurrentSettlement != settlement)
						{
							Debug.Print(character.HeroObject.StringId + " is in settlement.HeroesWithoutParty list but current settlement is not, tournament settlement: " + settlement.StringId, 0, Debug.DebugColor.White, 17592186044416UL);
						}
						mblist.Add(character);
					}
				}
				num4++;
			}
			int num5 = 0;
			int num6 = 0;
			int num7 = 0;
			if (mblist.Count < this.MaximumParticipantCount && settlement.Town.GarrisonParty != null)
			{
				int num8 = this.MaximumParticipantCount - mblist.Count;
				foreach (TroopRosterElement troopRosterElement2 in settlement.Town.GarrisonParty.MemberRoster.GetTroopRoster())
				{
					if (this.CanBeAParticipant(troopRosterElement2.Character, false))
					{
						if (!mblist.Contains(troopRosterElement2.Character) && troopRosterElement2.Character.Tier == 3 && (float)num8 * 0.4f > (float)num5)
						{
							mblist.Add(troopRosterElement2.Character);
							num5++;
						}
						else if (!mblist.Contains(troopRosterElement2.Character) && troopRosterElement2.Character.Tier == 4 && (float)num8 * 0.4f > (float)num6)
						{
							mblist.Add(troopRosterElement2.Character);
							num6++;
						}
						else if (!mblist.Contains(troopRosterElement2.Character) && troopRosterElement2.Character.Tier == 5 && (float)num8 * 0.2f > (float)num7)
						{
							mblist.Add(troopRosterElement2.Character);
							num7++;
						}
					}
					if (mblist.Count >= this.MaximumParticipantCount)
					{
						break;
					}
				}
			}
			if (mblist.Count < this.MaximumParticipantCount)
			{
				List<CharacterObject> list = new List<CharacterObject>();
				CharacterObject basicTroop = ((settlement != null) ? settlement.Culture : Game.Current.ObjectManager.GetObject<CultureObject>("empire")).BasicTroop;
				this.GetUpgradeTargets(basicTroop, ref list);
				int num9 = this.MaximumParticipantCount - mblist.Count;
				foreach (CharacterObject characterObject in list)
				{
					if (!mblist.Contains(characterObject) && characterObject.Tier == 3 && (float)num9 * 0.4f > (float)num5)
					{
						mblist.Add(characterObject);
						num5++;
					}
					else if (!mblist.Contains(characterObject) && characterObject.Tier == 4 && (float)num9 * 0.4f > (float)num6)
					{
						mblist.Add(characterObject);
						num6++;
					}
					else if (!mblist.Contains(characterObject) && characterObject.Tier == 5 && (float)num9 * 0.2f > (float)num7)
					{
						mblist.Add(characterObject);
						num7++;
					}
					if (mblist.Count >= this.MaximumParticipantCount)
					{
						break;
					}
				}
				if (!list.IsEmpty<CharacterObject>())
				{
					while (mblist.Count < this.MaximumParticipantCount)
					{
						list.Shuffle<CharacterObject>();
						int num10 = 0;
						while (num10 < list.Count && mblist.Count < this.MaximumParticipantCount)
						{
							mblist.Add(list[num10]);
							num10++;
						}
					}
				}
			}
			while (mblist.Count < this.MaximumParticipantCount)
			{
				CultureObject cultureObject = ((settlement != null) ? settlement.Culture : Game.Current.ObjectManager.GetObject<CultureObject>("empire"));
				CharacterObject item = ((MBRandom.RandomFloat > 0.5f) ? cultureObject.BasicTroop : cultureObject.EliteBasicTroop);
				mblist.Add(item);
			}
			this.SortTournamentParticipants(mblist);
			return mblist;
		}

		// Token: 0x060026CE RID: 9934 RVA: 0x000A18B4 File Offset: 0x0009FAB4
		private bool CanNpcJoinTournament(Hero hero, MBList<CharacterObject> participantCharacters, bool considerSkills)
		{
			return hero != null && !hero.IsWounded && !hero.IsNoncombatant && !participantCharacters.Contains(hero.CharacterObject) && hero != Hero.MainHero && hero.Age >= (float)Campaign.Current.Models.AgeModel.HeroComesOfAge && (hero.IsLord || hero.IsWanderer) && this.CanBeAParticipant(hero.CharacterObject, considerSkills);
		}

		// Token: 0x060026CF RID: 9935 RVA: 0x000A1928 File Offset: 0x0009FB28
		private void GetUpgradeTargets(CharacterObject troop, ref List<CharacterObject> list)
		{
			if (!list.Contains(troop) && this.CanBeAParticipant(troop, false))
			{
				list.Add(troop);
			}
			foreach (CharacterObject troop2 in troop.UpgradeTargets)
			{
				this.GetUpgradeTargets(troop2, ref list);
			}
		}

		// Token: 0x060026D0 RID: 9936 RVA: 0x000A1974 File Offset: 0x0009FB74
		private void SortTournamentParticipants(MBList<CharacterObject> participantCharacters)
		{
			for (int i = 0; i < participantCharacters.Count - 1; i++)
			{
				for (int j = participantCharacters.Count - 1; j > i; j--)
				{
					if (this.GetTroopPriorityPointForTournament(participantCharacters[j]) > this.GetTroopPriorityPointForTournament(participantCharacters[i]))
					{
						CharacterObject value = participantCharacters[j];
						CharacterObject value2 = participantCharacters[i];
						participantCharacters[j] = value2;
						participantCharacters[i] = value;
					}
				}
			}
		}

		// Token: 0x060026D1 RID: 9937 RVA: 0x000A19E4 File Offset: 0x0009FBE4
		private int GetTroopPriorityPointForTournament(CharacterObject troop)
		{
			int num = 40000;
			if (troop == CharacterObject.PlayerCharacter)
			{
				num += 80000;
			}
			if (troop.IsHero)
			{
				num += 20000;
			}
			if (troop.IsHero && troop.HeroObject.IsPlayerCompanion)
			{
				num += 10000;
			}
			else
			{
				Hero heroObject = troop.HeroObject;
				if (((heroObject != null) ? heroObject.Clan : null) != null)
				{
					int num2 = num;
					Clan clan = troop.HeroObject.Clan;
					num = num2 + (int)((clan != null) ? new float?(clan.Renown) : null).Value;
				}
				else
				{
					num += troop.Level;
				}
			}
			return num;
		}

		// Token: 0x060026D2 RID: 9938 RVA: 0x000A1A88 File Offset: 0x0009FC88
		protected override ItemObject GetTournamentPrize(bool includePlayer, int lastRecordedLordCountForTournamentPrize)
		{
			int num = this.GetParticipantCharacters(base.Town.Settlement, includePlayer).Count((CharacterObject p) => p.IsHero);
			if (lastRecordedLordCountForTournamentPrize == num && base.Prize != null)
			{
				return base.Prize;
			}
			this._lastRecordedLordCountForTournamentPrize = num;
			if (num >= 4)
			{
				if (this._possibleEliteRewardItemObjectsCache == null || this._possibleEliteRewardItemObjectsCache.IsEmpty<ItemObject>())
				{
					this._possibleEliteRewardItemObjectsCache = Campaign.Current.Models.TournamentModel.GetEliteRewardItems(base.Town, 1600, 5000);
					this._possibleEliteRewardItemObjectsCache.Sort((ItemObject x, ItemObject y) => x.Value.CompareTo(y.Value));
				}
				int minValue = 0;
				int maxValue = this._possibleEliteRewardItemObjectsCache.Count;
				if (num < 10)
				{
					maxValue = this._possibleEliteRewardItemObjectsCache.Count / 2;
				}
				else
				{
					minValue = this._possibleEliteRewardItemObjectsCache.Count / 2;
				}
				return this._possibleEliteRewardItemObjectsCache[MBRandom.RandomInt(minValue, maxValue)];
			}
			ItemObject itemObject = null;
			if (MBRandom.RandomFloat < 0.05f)
			{
				if (this._possibleBannerRewardItemObjectsCache == null || this._possibleBannerRewardItemObjectsCache.IsEmpty<ItemObject>())
				{
					List<ItemObject> regularRewardItems = Campaign.Current.Models.TournamentModel.GetRegularRewardItems(base.Town, 1600, 5000);
					this._possibleBannerRewardItemObjectsCache = new MBList<ItemObject>();
					foreach (ItemObject itemObject2 in regularRewardItems)
					{
						if (itemObject2.IsBannerItem)
						{
							this._possibleBannerRewardItemObjectsCache.Add(itemObject2);
						}
					}
				}
				itemObject = this._possibleBannerRewardItemObjectsCache.GetRandomElement<ItemObject>();
			}
			if (itemObject == null)
			{
				if (this._possibleRegularRewardItemObjectsCache == null || this._possibleRegularRewardItemObjectsCache.IsEmpty<ItemObject>())
				{
					this._possibleRegularRewardItemObjectsCache = Campaign.Current.Models.TournamentModel.GetRegularRewardItems(base.Town, 1600, 5000);
					this._possibleRegularRewardItemObjectsCache.Sort((ItemObject x, ItemObject y) => x.Value.CompareTo(y.Value));
				}
				int num2 = this._possibleRegularRewardItemObjectsCache.Count / 4;
				int num3 = Math.Min(this._possibleRegularRewardItemObjectsCache.Count, num2 * (num + 1));
				int minValue2 = Math.Max(0, num3 - num2);
				itemObject = this._possibleRegularRewardItemObjectsCache[MBRandom.RandomInt(minValue2, num3)];
			}
			if (itemObject != null)
			{
				return itemObject;
			}
			if (this._possibleEliteRewardItemObjectsCache == null || this._possibleEliteRewardItemObjectsCache.IsEmpty<ItemObject>())
			{
				this._possibleEliteRewardItemObjectsCache = Campaign.Current.Models.TournamentModel.GetEliteRewardItems(base.Town, 1600, 5000);
			}
			return this._possibleEliteRewardItemObjectsCache.GetRandomElement<ItemObject>();
		}

		// Token: 0x04000B53 RID: 2899
		private const int LordLimitForEliteReward = 4;

		// Token: 0x04000B54 RID: 2900
		private const int EliteRewardLordCountToDivideRewards = 10;

		// Token: 0x04000B55 RID: 2901
		private const int EliteRewardGroupCount = 2;

		// Token: 0x04000B56 RID: 2902
		private const int RegularRewardMinimumValue = 1600;

		// Token: 0x04000B57 RID: 2903
		private const int RegularRewardMaximumValue = 5000;

		// Token: 0x04000B58 RID: 2904
		private const int ParticipateTournamentMinimumSkillLimit = 100;

		// Token: 0x04000B59 RID: 2905
		private const float RegularBannerRewardChance = 0.05f;

		// Token: 0x04000B5A RID: 2906
		public const int ParticipantTroopMinimumTierLimit = 3;

		// Token: 0x04000B5B RID: 2907
		private MBList<ItemObject> _possibleBannerRewardItemObjectsCache;

		// Token: 0x04000B5C RID: 2908
		private MBList<ItemObject> _possibleRegularRewardItemObjectsCache;

		// Token: 0x04000B5D RID: 2909
		private MBList<ItemObject> _possibleEliteRewardItemObjectsCache;
	}
}
