using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Election;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.MapNotificationTypes
{
	// Token: 0x020002A6 RID: 678
	public class KingdomDecisionMapNotification : InformationData
	{
		// Token: 0x0600240C RID: 9228 RVA: 0x0009A02A File Offset: 0x0009822A
		internal static void AutoGeneratedStaticCollectObjectsKingdomDecisionMapNotification(object o, List<object> collectedObjects)
		{
			((KingdomDecisionMapNotification)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600240D RID: 9229 RVA: 0x0009A038 File Offset: 0x00098238
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.KingdomOfDecision);
			collectedObjects.Add(this.Decision);
		}

		// Token: 0x0600240E RID: 9230 RVA: 0x0009A059 File Offset: 0x00098259
		internal static object AutoGeneratedGetMemberValueKingdomOfDecision(object o)
		{
			return ((KingdomDecisionMapNotification)o).KingdomOfDecision;
		}

		// Token: 0x0600240F RID: 9231 RVA: 0x0009A066 File Offset: 0x00098266
		internal static object AutoGeneratedGetMemberValueDecision(object o)
		{
			return ((KingdomDecisionMapNotification)o).Decision;
		}

		// Token: 0x170008FB RID: 2299
		// (get) Token: 0x06002410 RID: 9232 RVA: 0x0009A073 File Offset: 0x00098273
		public override TextObject TitleText
		{
			get
			{
				return this.Decision.GetGeneralTitle();
			}
		}

		// Token: 0x170008FC RID: 2300
		// (get) Token: 0x06002411 RID: 9233 RVA: 0x0009A080 File Offset: 0x00098280
		public override string SoundEventPath
		{
			get
			{
				return "event:/ui/notification/kingdom_decision";
			}
		}

		// Token: 0x170008FD RID: 2301
		// (get) Token: 0x06002412 RID: 9234 RVA: 0x0009A087 File Offset: 0x00098287
		// (set) Token: 0x06002413 RID: 9235 RVA: 0x0009A08F File Offset: 0x0009828F
		[SaveableProperty(1)]
		public Kingdom KingdomOfDecision { get; private set; }

		// Token: 0x170008FE RID: 2302
		// (get) Token: 0x06002414 RID: 9236 RVA: 0x0009A098 File Offset: 0x00098298
		// (set) Token: 0x06002415 RID: 9237 RVA: 0x0009A0A0 File Offset: 0x000982A0
		[SaveableProperty(2)]
		public KingdomDecision Decision { get; private set; }

		// Token: 0x06002416 RID: 9238 RVA: 0x0009A0A9 File Offset: 0x000982A9
		public KingdomDecisionMapNotification(Kingdom kingdom, KingdomDecision decision, TextObject descriptionText)
			: base(descriptionText)
		{
			this.KingdomOfDecision = kingdom;
			this.Decision = decision;
		}

		// Token: 0x06002417 RID: 9239 RVA: 0x0009A0C0 File Offset: 0x000982C0
		public override bool IsValid()
		{
			KingdomPolicyDecision kingdomPolicyDecision;
			return (kingdomPolicyDecision = this.Decision as KingdomPolicyDecision) == null || kingdomPolicyDecision.Policy.IsReady;
		}
	}
}
