using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Conversation;
using TaleWorlds.CampaignSystem.ViewModelCollection.Map.MapConversation;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Map.MapConversation;

namespace SandBox.GauntletUI.AutoGenerated0
{
	// Token: 0x02000115 RID: 277
	public class MapConversation__TaleWorlds_CampaignSystem_ViewModelCollection_Map_MapConversation_MapConversationVM : MapConversationScreenButtonWidget, IGeneratedGauntletMovieRoot
	{
		// Token: 0x06005376 RID: 21366 RVA: 0x0029C23E File Offset: 0x0029A43E
		public MapConversation__TaleWorlds_CampaignSystem_ViewModelCollection_Map_MapConversation_MapConversationVM(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06005377 RID: 21367 RVA: 0x0029C248 File Offset: 0x0029A448
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new Widget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new MapConversationTableauWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
			this._widget_2 = new MapConversation__TaleWorlds_CampaignSystem_ViewModelCollection_Map_MapConversation_MapConversationVM_Dependency_1_SPConversation__DependendPrefab(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_2.CreateWidgets();
		}

		// Token: 0x06005378 RID: 21368 RVA: 0x0029C2EF File Offset: 0x0029A4EF
		public void SetIds()
		{
			base.Id = "MapConversationParent";
			this._widget_2.SetIds();
			this._widget_2.Id = "ConversationParent";
		}

		// Token: 0x06005379 RID: 21369 RVA: 0x0029C318 File Offset: 0x0029A518
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.StretchToParent;
			base.ConversationParent = this._widget_2;
			base.FrictionEnabled = false;
			this._widget_0.DoNotAcceptEvents = true;
			this._widget_0.DoNotPassEventsToChildren = true;
			this._widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			this._widget_0.Color = new Color(0f, 0f, 0f, 1f);
			this._widget_1.DoNotAcceptEvents = true;
			this._widget_1.DoNotPassEventsToChildren = true;
			this._widget_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.IsEnabled = false;
			this._widget_2.SetAttributes();
		}

		// Token: 0x0600537A RID: 21370 RVA: 0x0029C41C File Offset: 0x0029A61C
		public void RefreshBindingWithChildren()
		{
			MapConversationVM datasource_Root = this._datasource_Root;
			this.SetDataSource(null);
			this.SetDataSource(datasource_Root);
		}

		// Token: 0x0600537B RID: 21371 RVA: 0x0029C440 File Offset: 0x0029A640
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0;
				if (this._datasource_Root_DialogController != null)
				{
					this._widget_2.DestroyDataSource();
					this._datasource_Root_DialogController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x0600537C RID: 21372 RVA: 0x0029C7CF File Offset: 0x0029A9CF
		public void SetDataSource(MapConversationVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x0600537D RID: 21373 RVA: 0x0029C7D8 File Offset: 0x0029A9D8
		private void EventListenerOf_widget(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.ExecuteContinue();
			}
		}

		// Token: 0x0600537E RID: 21374 RVA: 0x0029C7F2 File Offset: 0x0029A9F2
		private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x0600537F RID: 21375 RVA: 0x0029C7FB File Offset: 0x0029A9FB
		private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06005380 RID: 21376 RVA: 0x0029C804 File Offset: 0x0029AA04
		private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06005381 RID: 21377 RVA: 0x0029C80D File Offset: 0x0029AA0D
		private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06005382 RID: 21378 RVA: 0x0029C816 File Offset: 0x0029AA16
		private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06005383 RID: 21379 RVA: 0x0029C81F File Offset: 0x0029AA1F
		private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06005384 RID: 21380 RVA: 0x0029C828 File Offset: 0x0029AA28
		private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06005385 RID: 21381 RVA: 0x0029C831 File Offset: 0x0029AA31
		private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06005386 RID: 21382 RVA: 0x0029C83A File Offset: 0x0029AA3A
		private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06005387 RID: 21383 RVA: 0x0029C843 File Offset: 0x0029AA43
		private void HandleWidgetPropertyChangeOf_widget(string propertyName)
		{
			if (propertyName == "IsBarterActive")
			{
				this._datasource_Root.IsBarterActive = this._widget.IsBarterActive;
				return;
			}
		}

		// Token: 0x06005388 RID: 21384 RVA: 0x0029C869 File Offset: 0x0029AA69
		private void PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06005389 RID: 21385 RVA: 0x0029C872 File Offset: 0x0029AA72
		private void boolPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600538A RID: 21386 RVA: 0x0029C87B File Offset: 0x0029AA7B
		private void floatPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600538B RID: 21387 RVA: 0x0029C884 File Offset: 0x0029AA84
		private void Vec2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600538C RID: 21388 RVA: 0x0029C88D File Offset: 0x0029AA8D
		private void Vector2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600538D RID: 21389 RVA: 0x0029C896 File Offset: 0x0029AA96
		private void doublePropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600538E RID: 21390 RVA: 0x0029C89F File Offset: 0x0029AA9F
		private void intPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600538F RID: 21391 RVA: 0x0029C8A8 File Offset: 0x0029AAA8
		private void uintPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06005390 RID: 21392 RVA: 0x0029C8B1 File Offset: 0x0029AAB1
		private void ColorPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06005391 RID: 21393 RVA: 0x0029C8BA File Offset: 0x0029AABA
		private void HandleWidgetPropertyChangeOf_widget_1_0(string propertyName)
		{
			if (propertyName == "Data")
			{
				this._datasource_Root.TableauData = this._widget_1_0.Data;
				return;
			}
		}

		// Token: 0x06005392 RID: 21394 RVA: 0x0029C8E0 File Offset: 0x0029AAE0
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06005393 RID: 21395 RVA: 0x0029C8EE File Offset: 0x0029AAEE
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06005394 RID: 21396 RVA: 0x0029C8FD File Offset: 0x0029AAFD
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06005395 RID: 21397 RVA: 0x0029C90C File Offset: 0x0029AB0C
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06005396 RID: 21398 RVA: 0x0029C91B File Offset: 0x0029AB1B
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06005397 RID: 21399 RVA: 0x0029C92A File Offset: 0x0029AB2A
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06005398 RID: 21400 RVA: 0x0029C939 File Offset: 0x0029AB39
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06005399 RID: 21401 RVA: 0x0029C948 File Offset: 0x0029AB48
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600539A RID: 21402 RVA: 0x0029C957 File Offset: 0x0029AB57
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600539B RID: 21403 RVA: 0x0029C968 File Offset: 0x0029AB68
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "DialogController")
			{
				this.RefreshDataSource_datasource_Root_DialogController(this._datasource_Root.DialogController);
				return;
			}
			if (propertyName == "IsBarterActive")
			{
				this._widget.IsBarterActive = this._datasource_Root.IsBarterActive;
				return;
			}
			if (propertyName == "TableauData")
			{
				this._widget_1_0.Data = this._datasource_Root.TableauData;
				return;
			}
		}

		// Token: 0x0600539C RID: 21404 RVA: 0x0029C9DC File Offset: 0x0029ABDC
		private void ViewModelPropertyChangedListenerOf_datasource_Root_DialogController(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DialogController(e.PropertyName);
		}

		// Token: 0x0600539D RID: 21405 RVA: 0x0029C9EA File Offset: 0x0029ABEA
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DialogController(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DialogController(e.PropertyName);
		}

		// Token: 0x0600539E RID: 21406 RVA: 0x0029C9F9 File Offset: 0x0029ABF9
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DialogController(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DialogController(e.PropertyName);
		}

		// Token: 0x0600539F RID: 21407 RVA: 0x0029CA08 File Offset: 0x0029AC08
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DialogController(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DialogController(e.PropertyName);
		}

		// Token: 0x060053A0 RID: 21408 RVA: 0x0029CA17 File Offset: 0x0029AC17
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DialogController(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DialogController(e.PropertyName);
		}

		// Token: 0x060053A1 RID: 21409 RVA: 0x0029CA26 File Offset: 0x0029AC26
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DialogController(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DialogController(e.PropertyName);
		}

		// Token: 0x060053A2 RID: 21410 RVA: 0x0029CA35 File Offset: 0x0029AC35
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DialogController(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DialogController(e.PropertyName);
		}

		// Token: 0x060053A3 RID: 21411 RVA: 0x0029CA44 File Offset: 0x0029AC44
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DialogController(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DialogController(e.PropertyName);
		}

		// Token: 0x060053A4 RID: 21412 RVA: 0x0029CA53 File Offset: 0x0029AC53
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DialogController(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DialogController(e.PropertyName);
		}

		// Token: 0x060053A5 RID: 21413 RVA: 0x0029CA62 File Offset: 0x0029AC62
		private void HandleViewModelPropertyChangeOf_datasource_Root_DialogController(string propertyName)
		{
		}

		// Token: 0x060053A6 RID: 21414 RVA: 0x0029CA64 File Offset: 0x0029AC64
		private void RefreshDataSource_datasource_Root(MapConversationVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0;
				if (this._datasource_Root_DialogController != null)
				{
					this._widget_2.SetDataSource(null);
					this._datasource_Root_DialogController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.IsBarterActive = this._datasource_Root.IsBarterActive;
				this._widget.EventFire += this.EventListenerOf_widget;
				this._widget.PropertyChanged += this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged += this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget;
				this._widget_1_0.Data = this._datasource_Root.TableauData;
				this._widget_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_0;
				this._datasource_Root_DialogController = this._datasource_Root.DialogController;
				if (this._datasource_Root_DialogController != null)
				{
					this._datasource_Root_DialogController.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DialogController;
					this._datasource_Root_DialogController.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DialogController;
					this._widget_2.SetDataSource(this._datasource_Root_DialogController);
				}
			}
		}

		// Token: 0x060053A7 RID: 21415 RVA: 0x0029D1B4 File Offset: 0x0029B3B4
		private void RefreshDataSource_datasource_Root_DialogController(MissionConversationVM newDataSource)
		{
			if (this._datasource_Root_DialogController != null)
			{
				this._widget_2.SetDataSource(null);
				this._datasource_Root_DialogController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController = null;
			}
			this._datasource_Root_DialogController = newDataSource;
			this._datasource_Root_DialogController = this._datasource_Root.DialogController;
			if (this._datasource_Root_DialogController != null)
			{
				this._datasource_Root_DialogController.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DialogController;
				this._datasource_Root_DialogController.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DialogController;
				this._widget_2.SetDataSource(this._datasource_Root_DialogController);
			}
		}

		// Token: 0x04001124 RID: 4388
		private MapConversationScreenButtonWidget _widget;

		// Token: 0x04001125 RID: 4389
		private Widget _widget_0;

		// Token: 0x04001126 RID: 4390
		private Widget _widget_1;

		// Token: 0x04001127 RID: 4391
		private MapConversationTableauWidget _widget_1_0;

		// Token: 0x04001128 RID: 4392
		private MapConversation__TaleWorlds_CampaignSystem_ViewModelCollection_Map_MapConversation_MapConversationVM_Dependency_1_SPConversation__DependendPrefab _widget_2;

		// Token: 0x04001129 RID: 4393
		private MapConversationVM _datasource_Root;

		// Token: 0x0400112A RID: 4394
		private MissionConversationVM _datasource_Root_DialogController;
	}
}
