using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.BarterSystem.Barterables
{
	// Token: 0x0200047F RID: 1151
	public class FiefBarterable : Barterable
	{
		// Token: 0x17000E59 RID: 3673
		// (get) Token: 0x06004867 RID: 18535 RVA: 0x0016D53B File Offset: 0x0016B73B
		public override string StringID
		{
			get
			{
				return "fief_barterable";
			}
		}

		// Token: 0x17000E5A RID: 3674
		// (get) Token: 0x06004868 RID: 18536 RVA: 0x0016D542 File Offset: 0x0016B742
		public Settlement TargetSettlement
		{
			get
			{
				return this._settlement;
			}
		}

		// Token: 0x17000E5B RID: 3675
		// (get) Token: 0x06004869 RID: 18537 RVA: 0x0016D54A File Offset: 0x0016B74A
		public override TextObject Name
		{
			get
			{
				return this._settlement.Name;
			}
		}

		// Token: 0x0600486A RID: 18538 RVA: 0x0016D557 File Offset: 0x0016B757
		public FiefBarterable(Settlement settlement, Hero owner, Hero heroOfferedTo)
			: base(owner, null)
		{
			this._settlement = settlement;
			this._heroOfferedTo = heroOfferedTo;
		}

		// Token: 0x0600486B RID: 18539 RVA: 0x0016D570 File Offset: 0x0016B770
		public override int GetUnitValueForFaction(IFaction faction)
		{
			float num = 1f;
			if (faction == this._heroOfferedTo.Clan)
			{
				num = 1f;
			}
			else if (faction == base.OriginalOwner.Clan)
			{
				num = -1f;
			}
			else if (faction.MapFaction == this._heroOfferedTo.MapFaction)
			{
				num = 1f;
			}
			else if (faction.MapFaction == base.OriginalOwner.MapFaction)
			{
				num = -1f;
			}
			float num2 = Campaign.Current.Models.SettlementValueModel.CalculateSettlementValueForFaction(this._settlement, faction);
			return (int)(num * num2);
		}

		// Token: 0x0600486C RID: 18540 RVA: 0x0016D603 File Offset: 0x0016B803
		public override ImageIdentifier GetVisualIdentifier()
		{
			return null;
		}

		// Token: 0x0600486D RID: 18541 RVA: 0x0016D606 File Offset: 0x0016B806
		public override string GetEncyclopediaLink()
		{
			return this.TargetSettlement.EncyclopediaLink;
		}

		// Token: 0x0600486E RID: 18542 RVA: 0x0016D613 File Offset: 0x0016B813
		public override void Apply()
		{
			ChangeOwnerOfSettlementAction.ApplyByBarter(this._heroOfferedTo, this._settlement);
		}

		// Token: 0x0600486F RID: 18543 RVA: 0x0016D626 File Offset: 0x0016B826
		internal static void AutoGeneratedStaticCollectObjectsFiefBarterable(object o, List<object> collectedObjects)
		{
			((FiefBarterable)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06004870 RID: 18544 RVA: 0x0016D634 File Offset: 0x0016B834
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._settlement);
			collectedObjects.Add(this._heroOfferedTo);
		}

		// Token: 0x06004871 RID: 18545 RVA: 0x0016D655 File Offset: 0x0016B855
		internal static object AutoGeneratedGetMemberValue_settlement(object o)
		{
			return ((FiefBarterable)o)._settlement;
		}

		// Token: 0x06004872 RID: 18546 RVA: 0x0016D662 File Offset: 0x0016B862
		internal static object AutoGeneratedGetMemberValue_heroOfferedTo(object o)
		{
			return ((FiefBarterable)o)._heroOfferedTo;
		}

		// Token: 0x040013FB RID: 5115
		[SaveableField(100)]
		private readonly Settlement _settlement;

		// Token: 0x040013FC RID: 5116
		[SaveableField(101)]
		private readonly Hero _heroOfferedTo;
	}
}
