using System;
using System.Collections.Generic;
using TaleWorlds.Core;

namespace TaleWorlds.CampaignSystem.Party.PartyComponents
{
	// Token: 0x02000308 RID: 776
	public abstract class WarPartyComponent : PartyComponent
	{
		// Token: 0x06002D47 RID: 11591 RVA: 0x000BCDD2 File Offset: 0x000BAFD2
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x17000B2A RID: 2858
		// (get) Token: 0x06002D48 RID: 11592 RVA: 0x000BCDDB File Offset: 0x000BAFDB
		public Clan Clan
		{
			get
			{
				return base.Party.MobileParty.ActualClan;
			}
		}

		// Token: 0x06002D49 RID: 11593 RVA: 0x000BCDED File Offset: 0x000BAFED
		public override Banner GetDefaultComponentBanner()
		{
			Clan clan = this.Clan;
			if (clan == null)
			{
				return null;
			}
			return clan.Banner;
		}

		// Token: 0x06002D4A RID: 11594 RVA: 0x000BCE00 File Offset: 0x000BB000
		protected override void OnInitialize()
		{
			this.Clan.OnWarPartyAdded(this);
		}

		// Token: 0x06002D4B RID: 11595 RVA: 0x000BCE0E File Offset: 0x000BB00E
		protected override void OnFinalize()
		{
			this.Clan.OnWarPartyRemoved(this);
		}

		// Token: 0x06002D4C RID: 11596 RVA: 0x000BCE1C File Offset: 0x000BB01C
		internal void OnClanChange(Clan oldClan, Clan newClan)
		{
			oldClan.OnWarPartyRemoved(this);
			newClan.OnWarPartyAdded(this);
		}
	}
}
