using System;
using System.Collections.Generic;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x02000342 RID: 834
	public class IssueQuestLogEntry : LogEntry
	{
		// Token: 0x0600313A RID: 12602 RVA: 0x000CBE57 File Offset: 0x000CA057
		internal static void AutoGeneratedStaticCollectObjectsIssueQuestLogEntry(object o, List<object> collectedObjects)
		{
			((IssueQuestLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600313B RID: 12603 RVA: 0x000CBE65 File Offset: 0x000CA065
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.IssueGiver);
			collectedObjects.Add(this.Antagonist);
		}

		// Token: 0x0600313C RID: 12604 RVA: 0x000CBE86 File Offset: 0x000CA086
		internal static object AutoGeneratedGetMemberValueIssueGiver(object o)
		{
			return ((IssueQuestLogEntry)o).IssueGiver;
		}

		// Token: 0x0600313D RID: 12605 RVA: 0x000CBE93 File Offset: 0x000CA093
		internal static object AutoGeneratedGetMemberValueAntagonist(object o)
		{
			return ((IssueQuestLogEntry)o).Antagonist;
		}

		// Token: 0x0600313E RID: 12606 RVA: 0x000CBEA0 File Offset: 0x000CA0A0
		internal static object AutoGeneratedGetMemberValueDetails(object o)
		{
			return ((IssueQuestLogEntry)o).Details;
		}

		// Token: 0x17000BDE RID: 3038
		// (get) Token: 0x0600313F RID: 12607 RVA: 0x000CBEB2 File Offset: 0x000CA0B2
		public override CampaignTime KeepInHistoryTime
		{
			get
			{
				return CampaignTime.Days(7f);
			}
		}

		// Token: 0x06003140 RID: 12608 RVA: 0x000CBEBE File Offset: 0x000CA0BE
		public IssueQuestLogEntry(Hero questGiver, Hero antagonist, QuestBase.QuestCompleteDetails status)
		{
			this.IssueGiver = questGiver;
			this.Antagonist = antagonist;
			this.Details = status;
		}

		// Token: 0x06003141 RID: 12609 RVA: 0x000CBEDC File Offset: 0x000CA0DC
		public override void GetConversationScoreAndComment(Hero talkTroop, bool findString, out string comment, out ImportanceEnum score)
		{
			score = ImportanceEnum.Zero;
			comment = "";
			if (this.IssueGiver == talkTroop)
			{
				if (this.Details == QuestBase.QuestCompleteDetails.FailWithBetrayal)
				{
					score = ImportanceEnum.MatterOfLifeAndDeath;
					if (findString)
					{
						comment = "str_comment_quest_betrayed";
						return;
					}
				}
				else if (this.Details == QuestBase.QuestCompleteDetails.Success)
				{
					score = ImportanceEnum.VeryImportant;
					if (findString)
					{
						comment = "str_comment_quest_succeeded";
						return;
					}
				}
				else if (this.Details == QuestBase.QuestCompleteDetails.Fail || this.Details == QuestBase.QuestCompleteDetails.Timeout || this.Details == QuestBase.QuestCompleteDetails.Cancel)
				{
					score = ImportanceEnum.Important;
					if (findString)
					{
						comment = "str_comment_quest_failed";
						return;
					}
				}
				else if (this.Details == QuestBase.QuestCompleteDetails.Invalid)
				{
					score = ImportanceEnum.ReasonablyImportant;
					if (findString)
					{
						comment = "str_comment_quest_invalid";
						return;
					}
				}
			}
			else if (this.Antagonist == talkTroop && this.Details == QuestBase.QuestCompleteDetails.FailWithBetrayal)
			{
				score = ImportanceEnum.MatterOfLifeAndDeath;
				if (findString)
				{
					comment = "str_comment_quest_counteroffer_accepted";
				}
			}
		}

		// Token: 0x04000E18 RID: 3608
		[SaveableField(10)]
		public readonly Hero IssueGiver;

		// Token: 0x04000E19 RID: 3609
		[SaveableField(20)]
		public readonly Hero Antagonist;

		// Token: 0x04000E1A RID: 3610
		[SaveableField(30)]
		public QuestBase.QuestCompleteDetails Details;
	}
}
