using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Election;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x02000330 RID: 816
	public class KingdomDecisionConcludedLogEntry : LogEntry, IChatNotification
	{
		// Token: 0x06003051 RID: 12369 RVA: 0x000C93FB File Offset: 0x000C75FB
		internal static void AutoGeneratedStaticCollectObjectsKingdomDecisionConcludedLogEntry(object o, List<object> collectedObjects)
		{
			((KingdomDecisionConcludedLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06003052 RID: 12370 RVA: 0x000C9409 File Offset: 0x000C7609
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.Kingdom);
			collectedObjects.Add(this._notificationText);
		}

		// Token: 0x06003053 RID: 12371 RVA: 0x000C942A File Offset: 0x000C762A
		internal static object AutoGeneratedGetMemberValueKingdom(object o)
		{
			return ((KingdomDecisionConcludedLogEntry)o).Kingdom;
		}

		// Token: 0x06003054 RID: 12372 RVA: 0x000C9437 File Offset: 0x000C7637
		internal static object AutoGeneratedGetMemberValue_isVisibleNotification(object o)
		{
			return ((KingdomDecisionConcludedLogEntry)o)._isVisibleNotification;
		}

		// Token: 0x06003055 RID: 12373 RVA: 0x000C9449 File Offset: 0x000C7649
		internal static object AutoGeneratedGetMemberValue_notificationText(object o)
		{
			return ((KingdomDecisionConcludedLogEntry)o)._notificationText;
		}

		// Token: 0x17000BBA RID: 3002
		// (get) Token: 0x06003056 RID: 12374 RVA: 0x000C9456 File Offset: 0x000C7656
		public override CampaignTime KeepInHistoryTime
		{
			get
			{
				return CampaignTime.Days(7f);
			}
		}

		// Token: 0x17000BBB RID: 3003
		// (get) Token: 0x06003057 RID: 12375 RVA: 0x000C9462 File Offset: 0x000C7662
		public bool IsVisibleNotification
		{
			get
			{
				return this._isVisibleNotification;
			}
		}

		// Token: 0x17000BBC RID: 3004
		// (get) Token: 0x06003058 RID: 12376 RVA: 0x000C946A File Offset: 0x000C766A
		public override ChatNotificationType NotificationType
		{
			get
			{
				return base.PoliticalNotification(this.Kingdom);
			}
		}

		// Token: 0x06003059 RID: 12377 RVA: 0x000C9478 File Offset: 0x000C7678
		public KingdomDecisionConcludedLogEntry(KingdomDecision decision, DecisionOutcome chosenOutcome, bool isPlayerInvolved)
		{
			this.Kingdom = decision.Kingdom;
			this._isVisibleNotification = !isPlayerInvolved;
			this._notificationText = decision.GetChosenOutcomeText(chosenOutcome, decision.SupportStatusOfFinalDecision, true);
		}

		// Token: 0x0600305A RID: 12378 RVA: 0x000C94AA File Offset: 0x000C76AA
		public override string ToString()
		{
			return this.GetNotificationText().ToString();
		}

		// Token: 0x0600305B RID: 12379 RVA: 0x000C94B7 File Offset: 0x000C76B7
		public TextObject GetNotificationText()
		{
			return this._notificationText;
		}

		// Token: 0x04000DD4 RID: 3540
		[SaveableField(1)]
		public readonly Kingdom Kingdom;

		// Token: 0x04000DD5 RID: 3541
		[SaveableField(3)]
		private readonly bool _isVisibleNotification;

		// Token: 0x04000DD6 RID: 3542
		[SaveableField(4)]
		private readonly TextObject _notificationText;
	}
}
