using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x02000339 RID: 825
	public class SettlementClaimedLogEntry : LogEntry, IChatNotification
	{
		// Token: 0x060030C5 RID: 12485 RVA: 0x000CA9FE File Offset: 0x000C8BFE
		internal static void AutoGeneratedStaticCollectObjectsSettlementClaimedLogEntry(object o, List<object> collectedObjects)
		{
			((SettlementClaimedLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060030C6 RID: 12486 RVA: 0x000CAA0C File Offset: 0x000C8C0C
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.Claimant);
			collectedObjects.Add(this.Settlement);
			collectedObjects.Add(this._settlementClan);
		}

		// Token: 0x060030C7 RID: 12487 RVA: 0x000CAA39 File Offset: 0x000C8C39
		internal static object AutoGeneratedGetMemberValueClaimant(object o)
		{
			return ((SettlementClaimedLogEntry)o).Claimant;
		}

		// Token: 0x060030C8 RID: 12488 RVA: 0x000CAA46 File Offset: 0x000C8C46
		internal static object AutoGeneratedGetMemberValueSettlement(object o)
		{
			return ((SettlementClaimedLogEntry)o).Settlement;
		}

		// Token: 0x060030C9 RID: 12489 RVA: 0x000CAA53 File Offset: 0x000C8C53
		internal static object AutoGeneratedGetMemberValue_settlementClan(object o)
		{
			return ((SettlementClaimedLogEntry)o)._settlementClan;
		}

		// Token: 0x17000BCF RID: 3023
		// (get) Token: 0x060030CA RID: 12490 RVA: 0x000CAA60 File Offset: 0x000C8C60
		public bool IsVisibleNotification
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17000BD0 RID: 3024
		// (get) Token: 0x060030CB RID: 12491 RVA: 0x000CAA63 File Offset: 0x000C8C63
		public override CampaignTime KeepInHistoryTime
		{
			get
			{
				return CampaignTime.Days(1680f);
			}
		}

		// Token: 0x060030CC RID: 12492 RVA: 0x000CAA6F File Offset: 0x000C8C6F
		public SettlementClaimedLogEntry(Hero claimant, Settlement settlement)
		{
			this.Claimant = claimant;
			this.Settlement = settlement;
			this._settlementClan = settlement.OwnerClan;
		}

		// Token: 0x060030CD RID: 12493 RVA: 0x000CAA91 File Offset: 0x000C8C91
		public override string ToString()
		{
			return this.GetNotificationText().ToString();
		}

		// Token: 0x060030CE RID: 12494 RVA: 0x000CAAA0 File Offset: 0x000C8CA0
		public TextObject GetNotificationText()
		{
			TextObject textObject = new TextObject("{=ARNYrXln}{TROOP.NAME} has claimed {SIDE1_PARTY} currently held by the {SIDE2_FACTION}", null);
			StringHelpers.SetCharacterProperties("TROOP", this.Claimant.CharacterObject, textObject, false);
			textObject.SetTextVariable("SIDE1_PARTY", this.Settlement.Name);
			textObject.SetTextVariable("SIDE2_FACTION", this._settlementClan.Name);
			return textObject;
		}

		// Token: 0x04000DF5 RID: 3573
		[SaveableField(320)]
		public readonly Hero Claimant;

		// Token: 0x04000DF6 RID: 3574
		[SaveableField(321)]
		public readonly Settlement Settlement;

		// Token: 0x04000DF7 RID: 3575
		[SaveableField(322)]
		private readonly Clan _settlementClan;
	}
}
