using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000364 RID: 868
	public class HeadmanNeedsToDeliverAHerdIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x060032FB RID: 13051 RVA: 0x000D0E43 File Offset: 0x000CF043
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x060032FC RID: 13052 RVA: 0x000D0E5C File Offset: 0x000CF05C
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x060032FD RID: 13053 RVA: 0x000D0E60 File Offset: 0x000CF060
		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnSelected), typeof(HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x060032FE RID: 13054 RVA: 0x000D0EC4 File Offset: 0x000CF0C4
		private bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.CurrentSettlement != null && issueGiver.CurrentSettlement.IsVillage && HeadmanNeedsToDeliverAHerdIssueBehavior.IsVillageSuitableForIssue(issueGiver.CurrentSettlement.Village) && (issueGiver.IsHeadman || issueGiver.IsRuralNotable) && issueGiver.CurrentSettlement.Village.Bound.Notables.Count > 0 && issueGiver.CurrentSettlement.Village.Bound.Town.Security <= 60f;
		}

		// Token: 0x060032FF RID: 13055 RVA: 0x000D0F4C File Offset: 0x000CF14C
		private static bool IsVillageSuitableForIssue(Village village)
		{
			return !village.Bound.IsCastle && (village.VillageType == DefaultVillageTypes.BattanianHorseRanch || village.VillageType == DefaultVillageTypes.DesertHorseRanch || village.VillageType == DefaultVillageTypes.EuropeHorseRanch || village.VillageType == DefaultVillageTypes.SteppeHorseRanch || village.VillageType == DefaultVillageTypes.SturgianHorseRanch || village.VillageType == DefaultVillageTypes.VlandianHorseRanch || village.VillageType == DefaultVillageTypes.CattleRange || village.VillageType == DefaultVillageTypes.SheepFarm || village.VillageType == DefaultVillageTypes.HogFarm);
		}

		// Token: 0x06003300 RID: 13056 RVA: 0x000D0FDF File Offset: 0x000CF1DF
		private IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			this._headmanNeedsToDeliverAHerdIssue = new HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue(issueOwner);
			return this._headmanNeedsToDeliverAHerdIssue;
		}

		// Token: 0x04000E8F RID: 3727
		private const IssueBase.IssueFrequency HeadmanNeedsToDeliverAHerdIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x04000E90 RID: 3728
		[SaveableField(216)]
		private HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue _headmanNeedsToDeliverAHerdIssue;

		// Token: 0x0200070B RID: 1803
		public class HeadmanNeedsToDeliverAHerdIssue : IssueBase
		{
			// Token: 0x060057F3 RID: 22515 RVA: 0x0019A7A4 File Offset: 0x001989A4
			internal static void AutoGeneratedStaticCollectObjectsHeadmanNeedsToDeliverAHerdIssue(object o, List<object> collectedObjects)
			{
				((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x060057F4 RID: 22516 RVA: 0x0019A7B2 File Offset: 0x001989B2
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._targetSettlement);
				collectedObjects.Add(this._targetHero);
				collectedObjects.Add(this._herdTypeToDeliver);
			}

			// Token: 0x060057F5 RID: 22517 RVA: 0x0019A7DF File Offset: 0x001989DF
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue)o)._targetSettlement;
			}

			// Token: 0x060057F6 RID: 22518 RVA: 0x0019A7EC File Offset: 0x001989EC
			internal static object AutoGeneratedGetMemberValue_targetHero(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue)o)._targetHero;
			}

			// Token: 0x060057F7 RID: 22519 RVA: 0x0019A7F9 File Offset: 0x001989F9
			internal static object AutoGeneratedGetMemberValue_herdTypeToDeliver(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue)o)._herdTypeToDeliver;
			}

			// Token: 0x17001101 RID: 4353
			// (get) Token: 0x060057F8 RID: 22520 RVA: 0x0019A806 File Offset: 0x00198A06
			private float MaxDistanceForSettlementSelection
			{
				get
				{
					return Campaign.Current.GetAverageDistanceBetweenClosestTwoTownsWithNavigationType(MobileParty.NavigationType.Default) * 3.75f;
				}
			}

			// Token: 0x17001102 RID: 4354
			// (get) Token: 0x060057F9 RID: 22521 RVA: 0x0019A819 File Offset: 0x00198A19
			private float MinDistanceForSettlementSelection
			{
				get
				{
					return Campaign.Current.GetAverageDistanceBetweenClosestTwoTownsWithNavigationType(MobileParty.NavigationType.Default) * 1.5f;
				}
			}

			// Token: 0x17001103 RID: 4355
			// (get) Token: 0x060057FA RID: 22522 RVA: 0x0019A82C File Offset: 0x00198A2C
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Duration;
				}
			}

			// Token: 0x17001104 RID: 4356
			// (get) Token: 0x060057FB RID: 22523 RVA: 0x0019A82F File Offset: 0x00198A2F
			private int AnimalCountToDeliver
			{
				get
				{
					return (int)MathF.Clamp((float)MathF.Round(5000f * base.IssueDifficultyMultiplier / (float)this._herdTypeToDeliver.Value), 10f, 75f);
				}
			}

			// Token: 0x17001105 RID: 4357
			// (get) Token: 0x060057FC RID: 22524 RVA: 0x0019A860 File Offset: 0x00198A60
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 6 + MathF.Ceiling(14f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001106 RID: 4358
			// (get) Token: 0x060057FD RID: 22525 RVA: 0x0019A875 File Offset: 0x00198A75
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 5 + MathF.Ceiling(5f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001107 RID: 4359
			// (get) Token: 0x060057FE RID: 22526 RVA: 0x0019A88A File Offset: 0x00198A8A
			protected override int RewardGold
			{
				get
				{
					return 300 + (int)((float)this._herdTypeToDeliver.Value * 0.75f * (float)this.AnimalCountToDeliver);
				}
			}

			// Token: 0x17001108 RID: 4360
			// (get) Token: 0x060057FF RID: 22527 RVA: 0x0019A8AD File Offset: 0x00198AAD
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=kDIi3bLN}The village needs someone to take a herd to {TARGET_SETTLEMENT}.", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x17001109 RID: 4361
			// (get) Token: 0x06005800 RID: 22528 RVA: 0x0019A8D4 File Offset: 0x00198AD4
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=7H4HQNvF}Yes. Some of the families in this village need to raise a bit of money. [if:convo_calm_friendly][ib:normal2]They've put together a herd of {ANIMAL_COUNT_TO_DELIVER} {.%}{?ANIMAL_COUNT_TO_DELIVER > 1}{PLURAL(HERD_TYPE_TO_DELIVER)}{?}{HERD_TYPE_TO_DELIVER}{\\?}{.%} to sell in {TARGET_SETTLEMENT}, but with all the banditry on the roads, they can't drive it there on their own. We're not merchants or landowners. We can't afford any losses.", null);
					if (base.IssueOwner.CharacterObject.GetPersona() == DefaultTraits.PersonaCurt)
					{
						textObject = new TextObject("{=6kJ31qut}Yeah, well, some people here are a bit short of money these days. [if:convo_calm_friendly][ib:normal]They've put together a herd of {ANIMAL_COUNT_TO_DELIVER} {.%}{?ANIMAL_COUNT_TO_DELIVER > 1}{PLURAL(HERD_TYPE_TO_DELIVER)}{?}{HERD_TYPE_TO_DELIVER}{\\?}{.%} to sell in {TARGET_SETTLEMENT}. But they're poor folks. Not really fighters, and they can't afford to hire guards. If they go there by themselves they'd be sitting ducks for any bandits.", null);
					}
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("ANIMAL_COUNT_TO_DELIVER", this.AnimalCountToDeliver);
					textObject.SetTextVariable("HERD_TYPE_TO_DELIVER", this._herdTypeToDeliver.Name);
					return textObject;
				}
			}

			// Token: 0x1700110A RID: 4362
			// (get) Token: 0x06005801 RID: 22529 RVA: 0x0019A951 File Offset: 0x00198B51
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=lmJYF6pQ}Tell me how I can help.", null);
				}
			}

			// Token: 0x1700110B RID: 4363
			// (get) Token: 0x06005802 RID: 22530 RVA: 0x0019A960 File Offset: 0x00198B60
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=VbRyXBsv}If you're going in the direction of {TARGET_SETTLEMENT}, you can perhaps take our herd there to {TARGET_HERO.LINK}. I am willing to pay {REWARD_AMOUNT}{GOLD_ICON} if you deliver them safe and sound.[if:convo_calm_friendly][ib:normal]", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("REWARD_AMOUNT", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					StringHelpers.SetCharacterProperties("TARGET_HERO", this._targetHero.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700110C RID: 4364
			// (get) Token: 0x06005803 RID: 22531 RVA: 0x0019A9CC File Offset: 0x00198BCC
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=CqmoyrHH}You can assign a companion with {REQUIRED_SOLDIERS} men, they will be enough too. Both ways works fine for us. I promise if you or your men manage to deliver the herd safely, I will pay you {REWARD}{GOLD_ICON}. So what do you say?[if:convo_nonchalant]", null);
					textObject.SetTextVariable("REQUIRED_SOLDIERS", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			// Token: 0x1700110D RID: 4365
			// (get) Token: 0x06005804 RID: 22532 RVA: 0x0019AA1C File Offset: 0x00198C1C
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=MJdVfS4z}Don't worry. I will deliver your {ANIMAL_COUNT_TO_DELIVER} {.%}{?ANIMAL_COUNT_TO_DELIVER > 1}{PLURAL(HERD_TYPE_TO_DELIVER)}{?}{HERD_TYPE_TO_DELIVER}{\\?}{.%} personally to {TARGET_HERO.LINK} in {TARGET_SETTLEMENT}.", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					textObject.SetTextVariable("ANIMAL_COUNT_TO_DELIVER", this.AnimalCountToDeliver);
					textObject.SetTextVariable("HERD_TYPE_TO_DELIVER", this._herdTypeToDeliver.Name);
					StringHelpers.SetCharacterProperties("TARGET_HERO", this._targetHero.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700110E RID: 4366
			// (get) Token: 0x06005805 RID: 22533 RVA: 0x0019AA90 File Offset: 0x00198C90
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=k8W02aj9}I will assign a companion with {NEEDED_MEN_COUNT} of my men to deliver {ANIMAL_COUNT_TO_DELIVER} {.%}{?ANIMAL_COUNT_TO_DELIVER > 1}{PLURAL(HERD_TYPE_TO_DELIVER)}{?}{HERD_TYPE_TO_DELIVER}{\\?}{.%} safely.", null);
					textObject.SetTextVariable("NEEDED_MEN_COUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("ANIMAL_COUNT_TO_DELIVER", this.AnimalCountToDeliver);
					textObject.SetTextVariable("HERD_TYPE_TO_DELIVER", this._herdTypeToDeliver.Name);
					return textObject;
				}
			}

			// Token: 0x1700110F RID: 4367
			// (get) Token: 0x06005806 RID: 22534 RVA: 0x0019AAE3 File Offset: 0x00198CE3
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					TextObject textObject = new TextObject("{=mwpY5Ylb}I am still waiting for news from {TARGET_SETTLEMENT}. Once again, I appreciate that you could spare the men to do this.[if:convo_calm_friendly]", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001110 RID: 4368
			// (get) Token: 0x06005807 RID: 22535 RVA: 0x0019AB08 File Offset: 0x00198D08
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=BJxJwCc5}Thank you, {?PLAYER.GENDER}madam{?}sir{\\?}. Any brigands would be most unwise to tangle with you.", null);
					if (base.IssueOwner.CharacterObject.GetPersona() == DefaultTraits.PersonaCurt)
					{
						textObject = new TextObject("{=muE5fcOf}Good. Anyone gives you trouble... Well, you look like you could handle them.", null);
					}
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001111 RID: 4369
			// (get) Token: 0x06005808 RID: 22536 RVA: 0x0019AB58 File Offset: 0x00198D58
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=m2h6zMp7}{ISSUE_GIVER.LINK}, the headman from {SETTLEMENT}, has asked you to deliver some of the village's livestock to {SETTLEMENT_TARGET}. The villagers can't afford their own guards and also can't afford any losses. {ISSUE_GIVER.LINK} offers {REWARD_AMOUNT}{GOLD_ICON} for the herd's delivery. You sent {COMPANION.LINK} with {NEEDED_MEN_COUNT} of your men to protect the herd. They should return to you with news of their success in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("SETTLEMENT_TARGET", this._targetSettlement.Name);
					textObject.SetTextVariable("NEEDED_MEN_COUNT", this.AlternativeSolutionSentTroops.TotalManCount - 1);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					textObject.SetTextVariable("REWARD_AMOUNT", this.RewardGold);
					return textObject;
				}
			}

			// Token: 0x17001112 RID: 4370
			// (get) Token: 0x06005809 RID: 22537 RVA: 0x0019AC23 File Offset: 0x00198E23
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17001113 RID: 4371
			// (get) Token: 0x0600580A RID: 22538 RVA: 0x0019AC26 File Offset: 0x00198E26
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001114 RID: 4372
			// (get) Token: 0x0600580B RID: 22539 RVA: 0x0019AC2C File Offset: 0x00198E2C
			public override TextObject IssueAsRumorInSettlement
			{
				get
				{
					TextObject textObject = new TextObject("{=cvZH3cI1}I hope {QUEST_GIVER.NAME} has a plan to get that herd to market.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001115 RID: 4373
			// (get) Token: 0x0600580C RID: 22540 RVA: 0x0019AC5E File Offset: 0x00198E5E
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(500f + 700f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001116 RID: 4374
			// (get) Token: 0x0600580D RID: 22541 RVA: 0x0019AC73 File Offset: 0x00198E73
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=KhUkmIrH}Deliver the Herd to {TARGET_SETTLEMENT}", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x0600580E RID: 22542 RVA: 0x0019AC98 File Offset: 0x00198E98
			public HeadmanNeedsToDeliverAHerdIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
				HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue <>4__this = this;
				Settlement settlement = SettlementHelper.FindRandomSettlement(delegate(Settlement x)
				{
					if (x.IsTown)
					{
						if (x.Notables.Any((Hero y) => y.CanHaveCampaignIssues()) && !x.MapFaction.IsAtWarWith(issueOwner.MapFaction) && Campaign.Current.Models.MapDistanceModel.GetDistance(x, <>4__this.IssueSettlement, false, false, MobileParty.MainParty.NavigationCapability) > <>4__this.MinDistanceForSettlementSelection)
						{
							return Campaign.Current.Models.MapDistanceModel.GetDistance(x, <>4__this.IssueSettlement, false, false, MobileParty.MainParty.NavigationCapability) < <>4__this.MaxDistanceForSettlementSelection;
						}
					}
					return false;
				});
				this._targetSettlement = settlement ?? base.IssueSettlement.Village.Bound;
				this._herdTypeToDeliver = Campaign.Current.ObjectManager.GetObject<ItemObject>(this._possibleHerdTypes.GetRandomElement<string>());
				if (this._targetSettlement != null)
				{
					this._targetHero = this._targetSettlement.Notables.GetRandomElementWithPredicate((Hero x) => x.CanHaveCampaignIssues()) ?? this._targetSettlement.Notables.GetRandomElement<Hero>();
				}
			}

			// Token: 0x0600580F RID: 22543 RVA: 0x0019AD99 File Offset: 0x00198F99
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.SettlementProsperity)
				{
					return -0.2f;
				}
				return 0f;
			}

			// Token: 0x06005810 RID: 22544 RVA: 0x0019ADAE File Offset: 0x00198FAE
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Riding) >= hero.GetSkillValue(DefaultSkills.Scouting)) ? DefaultSkills.Riding : DefaultSkills.Scouting, 120);
			}

			// Token: 0x06005811 RID: 22545 RVA: 0x0019ADDB File Offset: 0x00198FDB
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x06005812 RID: 22546 RVA: 0x0019ADEC File Offset: 0x00198FEC
			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2;
			}

			// Token: 0x06005813 RID: 22547 RVA: 0x0019ADFC File Offset: 0x00198FFC
			public override bool IssueStayAliveConditions()
			{
				return !base.IssueOwner.CurrentSettlement.IsRaided && !base.IssueOwner.CurrentSettlement.IsUnderRaid && this._targetHero.IsActive && base.IssueOwner.CurrentSettlement.Village.Bound.Town.Security <= 70f;
			}

			// Token: 0x06005814 RID: 22548 RVA: 0x0019AE65 File Offset: 0x00199065
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x06005815 RID: 22549 RVA: 0x0019AE67 File Offset: 0x00199067
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x06005816 RID: 22550 RVA: 0x0019AE81 File Offset: 0x00199081
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				this.ApplySuccessRewards(base.IssueOwner);
			}

			// Token: 0x06005817 RID: 22551 RVA: 0x0019AE8F File Offset: 0x0019908F
			private void ApplySuccessRewards(Hero issueGiver)
			{
				issueGiver.AddPower(5f);
				this.RelationshipChangeWithIssueOwner = 5;
				issueGiver.CurrentSettlement.Village.Hearth += 50f;
			}

			// Token: 0x06005818 RID: 22552 RVA: 0x0019AEBF File Offset: 0x001990BF
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005819 RID: 22553 RVA: 0x0019AEC1 File Offset: 0x001990C1
			protected override void HourlyTick()
			{
			}

			// Token: 0x0600581A RID: 22554 RVA: 0x0019AEC3 File Offset: 0x001990C3
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(30f), this.AnimalCountToDeliver, this._herdTypeToDeliver, this._targetSettlement, this.RewardGold, this._targetHero);
			}

			// Token: 0x0600581B RID: 22555 RVA: 0x0019AEF9 File Offset: 0x001990F9
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x0600581C RID: 22556 RVA: 0x0019AEFC File Offset: 0x001990FC
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill)
			{
				flag = IssueBase.PreconditionFlags.None;
				relationHero = null;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flag |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (issueGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					flag |= IssueBase.PreconditionFlags.AtWar;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x04001C83 RID: 7299
			private const int IssueDuration = 30;

			// Token: 0x04001C84 RID: 7300
			private const int QuestTimeLimit = 30;

			// Token: 0x04001C85 RID: 7301
			private const int AlternativeSolutionTroopTierRequirement = 2;

			// Token: 0x04001C86 RID: 7302
			private const int RequiredSkillForSendingCompanion = 120;

			// Token: 0x04001C87 RID: 7303
			[CachedData]
			private readonly MBList<string> _possibleHerdTypes = new MBList<string> { "sheep", "cow", "hog" };

			// Token: 0x04001C88 RID: 7304
			[SaveableField(10)]
			private Settlement _targetSettlement;

			// Token: 0x04001C89 RID: 7305
			[SaveableField(20)]
			private Hero _targetHero;

			// Token: 0x04001C8A RID: 7306
			[SaveableField(30)]
			private ItemObject _herdTypeToDeliver;
		}

		// Token: 0x0200070C RID: 1804
		public class HeadmanNeedsToDeliverAHerdIssueQuest : QuestBase
		{
			// Token: 0x0600581D RID: 22557 RVA: 0x0019AF51 File Offset: 0x00199151
			internal static void AutoGeneratedStaticCollectObjectsHeadmanNeedsToDeliverAHerdIssueQuest(object o, List<object> collectedObjects)
			{
				((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x0600581E RID: 22558 RVA: 0x0019AF5F File Offset: 0x0019915F
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._targetSettlement);
				collectedObjects.Add(this._targetHero);
				collectedObjects.Add(this._herdTypeToDeliver);
				collectedObjects.Add(this._playerStartsQuestLog);
			}

			// Token: 0x0600581F RID: 22559 RVA: 0x0019AF98 File Offset: 0x00199198
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._targetSettlement;
			}

			// Token: 0x06005820 RID: 22560 RVA: 0x0019AFA5 File Offset: 0x001991A5
			internal static object AutoGeneratedGetMemberValue_targetHero(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._targetHero;
			}

			// Token: 0x06005821 RID: 22561 RVA: 0x0019AFB2 File Offset: 0x001991B2
			internal static object AutoGeneratedGetMemberValue_herdTypeToDeliver(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._herdTypeToDeliver;
			}

			// Token: 0x06005822 RID: 22562 RVA: 0x0019AFBF File Offset: 0x001991BF
			internal static object AutoGeneratedGetMemberValue_animalCountToDeliver(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._animalCountToDeliver;
			}

			// Token: 0x06005823 RID: 22563 RVA: 0x0019AFD1 File Offset: 0x001991D1
			internal static object AutoGeneratedGetMemberValue_rewardGold(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._rewardGold;
			}

			// Token: 0x06005824 RID: 22564 RVA: 0x0019AFE3 File Offset: 0x001991E3
			internal static object AutoGeneratedGetMemberValue_playerStartsQuestLog(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._playerStartsQuestLog;
			}

			// Token: 0x17001117 RID: 4375
			// (get) Token: 0x06005825 RID: 22565 RVA: 0x0019AFF0 File Offset: 0x001991F0
			public sealed override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=KhUkmIrH}Deliver the Herd to {TARGET_SETTLEMENT}", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001118 RID: 4376
			// (get) Token: 0x06005826 RID: 22566 RVA: 0x0019B014 File Offset: 0x00199214
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001119 RID: 4377
			// (get) Token: 0x06005827 RID: 22567 RVA: 0x0019B018 File Offset: 0x00199218
			private TextObject PlayerStartsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=wsGDDXPN}{QUEST_GIVER.LINK}, the headman from {QUEST_GIVER_SETTLEMENT} has asked you to deliver {ANIMAL_COUNT_TO_DELIVER} {.%}{?ANIMAL_COUNT_TO_DELIVER > 1}{PLURAL(HERD_TYPE_TO_DELIVER)}{?}{HERD_TYPE_TO_DELIVER}{\\?}{.%} to {TARGET_HERO.LINK} in {TARGET_SETTLEMENT}. {?QUEST_GIVER.GENDER}She{?}He{\\?} fears such a large herd will attract attention from the brigands on the way. {QUEST_GIVER.LINK} offers {REWARD_AMOUNT}{GOLD_ICON} for the herd's delivery.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("TARGET_HERO", this._targetHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("ANIMAL_COUNT_TO_DELIVER", this._animalCountToDeliver);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("HERD_TYPE_TO_DELIVER", this._herdTypeToDeliver.Name);
					textObject.SetTextVariable("REWARD_AMOUNT", this._rewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			// Token: 0x1700111A RID: 4378
			// (get) Token: 0x06005828 RID: 22568 RVA: 0x0019B0E4 File Offset: 0x001992E4
			private TextObject SuccessQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=6IKKFH3A}You have received a message and a large purse from {QUEST_GIVER.LINK}. The missive reads: ”The herd is safe. Thank you, and please accept these {REWARD}{GOLD_ICON} with our gratitude.”.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("REWARD", this._rewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			// Token: 0x1700111B RID: 4379
			// (get) Token: 0x06005829 RID: 22569 RVA: 0x0019B13C File Offset: 0x0019933C
			private TextObject FailByTimeOutQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=hhrRnSvr}You failed to deliver the herd in time, as {QUEST_GIVER.LINK} has asked of you. The shepherds and the herd left you.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			// Token: 0x1700111C RID: 4380
			// (get) Token: 0x0600582A RID: 22570 RVA: 0x0019B180 File Offset: 0x00199380
			private TextObject FailByRejectQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=MjwNHtQd}You rejected to deliver the herd, as {QUEST_GIVER.LINK} has asked of you. The shepherds have left you.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			// Token: 0x1700111D RID: 4381
			// (get) Token: 0x0600582B RID: 22571 RVA: 0x0019B1C4 File Offset: 0x001993C4
			private TextObject QuestCanceledWarDeclaredLog
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700111E RID: 4382
			// (get) Token: 0x0600582C RID: 22572 RVA: 0x0019B1F8 File Offset: 0x001993F8
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x0600582D RID: 22573 RVA: 0x0019B22C File Offset: 0x0019942C
			public HeadmanNeedsToDeliverAHerdIssueQuest(string questId, Hero questGiver, CampaignTime duration, int animalCountToDeliver, ItemObject herdTypeToDeliver, Settlement targetSettlement, int rewardGold, Hero targetHero)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._animalCountToDeliver = animalCountToDeliver;
				this._herdTypeToDeliver = herdTypeToDeliver;
				this._targetSettlement = targetSettlement;
				this._rewardGold = rewardGold;
				this._targetHero = targetHero;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x0600582E RID: 22574 RVA: 0x0019B278 File Offset: 0x00199478
			protected override void SetDialogs()
			{
				TextObject textObject = new TextObject("{=iUQuwAZY}Thank you, {?PLAYER.GENDER}madam{?}sir{\\?}. The village will be grateful to you. Good luck.", null);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(textObject, null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(new TextObject("{=zB6elkn1}The herd is ready to depart.", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=8tBET7S5}Good. We will be heading out soon.", null), null, null, null)
					.NpcLine(new TextObject("{=iAGx49nO}Good to hear that! Safe journeys.[if:convo_approving]", null), null, null, null, null)
					.CloseDialog()
					.PlayerOption(new TextObject("{=EOaOlh39}In due time. Let's not be too hasty.", null), null, null, null)
					.NpcLine(new TextObject("{=79Te4duG}As you wish.[if:convo_normal][ib:demure]", null), null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x0600582F RID: 22575 RVA: 0x0019B388 File Offset: 0x00199588
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				this._playerStartsQuestLog = base.AddLog(this.PlayerStartsQuestLogText, false);
				this.AddHerdAndShepherdsToMainParty();
				base.AddTrackedObject(this._targetSettlement);
				base.AddTrackedObject(this._targetHero);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetDeliveryDialogFlow(), this);
			}

			// Token: 0x06005830 RID: 22576 RVA: 0x0019B3E4 File Offset: 0x001995E4
			protected override void OnCompleteWithSuccess()
			{
				base.QuestGiver.AddPower(5f);
				this.RelationshipChangeWithQuestGiver = 5;
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 30)
				});
				base.QuestGiver.CurrentSettlement.Village.Hearth += 50f;
				this._targetSettlement.Town.Prosperity += 50f;
				int availableRequestedItemCountOnPlayer = this.GetAvailableRequestedItemCountOnPlayer(this._herdTypeToDeliver);
				int num = ((availableRequestedItemCountOnPlayer > this._animalCountToDeliver) ? this._animalCountToDeliver : availableRequestedItemCountOnPlayer);
				foreach (ItemRosterElement itemRosterElement in MobileParty.MainParty.ItemRoster)
				{
					if (itemRosterElement.EquipmentElement.Item == this._herdTypeToDeliver)
					{
						int amount = itemRosterElement.Amount;
						if (amount >= num)
						{
							PartyBase.MainParty.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, -num);
							this._targetSettlement.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, num);
							break;
						}
						num -= amount;
						PartyBase.MainParty.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, -amount);
						this._targetSettlement.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, amount);
					}
				}
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this._rewardGold, false);
				base.AddLog(this.SuccessQuestLogText, false);
			}

			// Token: 0x06005831 RID: 22577 RVA: 0x0019B580 File Offset: 0x00199780
			protected override void OnFinalize()
			{
				base.RemoveTrackedObject(this._targetSettlement);
				base.RemoveTrackedObject(this._targetHero);
			}

			// Token: 0x06005832 RID: 22578 RVA: 0x0019B59C File Offset: 0x0019979C
			private DialogFlow GetDeliveryDialogFlow()
			{
				TextObject textObject = new TextObject("{=8nwZXNTk}About the task {QUEST_GIVER.LINK} gave me...", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
				TextObject textObject2 = new TextObject("{=kwJBLl00}Yes {?PLAYER.GENDER}madam{?}sir{\\?}. Our mutual friend {QUEST_GIVER.LINK} sent word to us. {?QUEST_GIVER.GENDER}She{?}He{\\?} told us to expect you with {?QUEST_GIVER.GENDER}her{?}his{\\?} {HERD_AMOUNT} {.%}{?HERD_AMOUNT > 1}{PLURAL(HERD_TYPE)}{?}{HERD_TYPE}{\\?}{.%}.", null);
				TextObject npcText = new TextObject("{=vXCg3OYx}So, have you brought them?[if:convo_undecided_open]", null);
				textObject2.SetTextVariable("HERD_AMOUNT", this._animalCountToDeliver);
				textObject2.SetTextVariable("HERD_TYPE", this._herdTypeToDeliver.Name);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject2, false);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject2, false);
				TextObject textObject3 = new TextObject("{=wmZYHGb9}I brought {HERD_AMOUNT} {.%}{?HERD_AMOUNT > 1}{PLURAL(HERD_TYPE)}{?}{HERD_TYPE}{\\?}{.%} as we agreed.", null);
				textObject3.SetTextVariable("HERD_AMOUNT", this._animalCountToDeliver);
				textObject3.SetTextVariable("HERD_TYPE", this._herdTypeToDeliver.Name);
				TextObject textObject4 = new TextObject("{=VkUMPAfR}Thank you for your help. {QUEST_GIVER.LINK} will send your reward as soon as possible.[if:convo_calm_friendly][ib:demure]", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject4, false);
				TextObject text = new TextObject("{=1s54uxsA}Sorry. I don't have any animals for you this time.", null);
				TextObject npcText2 = new TextObject("{=1dUVrgQ8}I just hope you can deliver the herd soon.", null);
				TextObject text2 = new TextObject("{=HFZisEnI}I'm going to keep that herd for myself.", null);
				TextObject textObject5 = new TextObject("{=LpfQYLQo}What? That's straight-up theft. I guarantee you {QUEST_GIVER.LINK} will hear about this![if:convo_annoyed][ib:aggressive]", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject5, false);
				return DialogFlow.CreateDialogFlow("hero_main_options", 125).PlayerLine(textObject, null, null, null).Condition(() => Settlement.CurrentSettlement == this._targetSettlement && CharacterObject.OneToOneConversationCharacter.IsHero && CharacterObject.OneToOneConversationCharacter.HeroObject == this._targetHero)
					.NpcLine(textObject2, null, null, null, null)
					.NpcLine(npcText, null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject3, null, null, null)
					.Condition(delegate
					{
						int availableRequestedItemCountOnPlayer = this.GetAvailableRequestedItemCountOnPlayer(this._herdTypeToDeliver);
						Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("HERD_AMOUNT", this._animalCountToDeliver);
						Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("HERD_TYPE", this._herdTypeToDeliver.Name);
						return availableRequestedItemCountOnPlayer >= this._animalCountToDeliver;
					})
					.NpcLine(textObject4, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.DeliverHerdOnConsequence))
					.CloseDialog()
					.PlayerOption(text2, null, null, null)
					.NpcLine(textObject5, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.DeliverHerdRejectOnConsequence))
					.CloseDialog()
					.PlayerOption(text, null, null, null)
					.NpcLine(npcText2, null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06005833 RID: 22579 RVA: 0x0019B7AB File Offset: 0x001999AB
			private void DeliverHerdRejectOnConsequence()
			{
				base.CompleteQuestWithFail(null);
				ChangeCrimeRatingAction.Apply(base.QuestGiver.CurrentSettlement.MapFaction, 20f, true);
			}

			// Token: 0x06005834 RID: 22580 RVA: 0x0019B7CF File Offset: 0x001999CF
			private void DeliverHerdOnConsequence()
			{
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005835 RID: 22581 RVA: 0x0019B7D8 File Offset: 0x001999D8
			private int GetAvailableRequestedItemCountOnPlayer(ItemObject item)
			{
				int num = 0;
				foreach (ItemRosterElement itemRosterElement in PartyBase.MainParty.ItemRoster)
				{
					if (itemRosterElement.EquipmentElement.Item == item)
					{
						num += itemRosterElement.Amount;
					}
				}
				return num;
			}

			// Token: 0x06005836 RID: 22582 RVA: 0x0019B844 File Offset: 0x00199A44
			public override void OnCanceled()
			{
				int availableRequestedItemCountOnPlayer = this.GetAvailableRequestedItemCountOnPlayer(this._herdTypeToDeliver);
				PartyBase.MainParty.ItemRoster.AddToCounts(this._herdTypeToDeliver, (availableRequestedItemCountOnPlayer > this._animalCountToDeliver) ? (-this._animalCountToDeliver) : (-availableRequestedItemCountOnPlayer));
			}

			// Token: 0x06005837 RID: 22583 RVA: 0x0019B888 File Offset: 0x00199A88
			protected override void OnTimedOut()
			{
				this.ApplyFailureEffects(true);
				base.AddLog(this.FailByTimeOutQuestLogText, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -10)
				});
				this.RemoveRemainingHorses();
			}

			// Token: 0x06005838 RID: 22584 RVA: 0x0019B8C5 File Offset: 0x00199AC5
			public override void OnFailed()
			{
				this.ApplyFailureEffects(false);
				base.AddLog(this.FailByRejectQuestLogText, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -30)
				});
			}

			// Token: 0x06005839 RID: 22585 RVA: 0x0019B8FC File Offset: 0x00199AFC
			private void ApplyFailureEffects(bool isTimedOut = false)
			{
				base.QuestGiver.AddPower(-5f);
				this._targetSettlement.Town.Prosperity -= 10f;
				this.RelationshipChangeWithQuestGiver = (isTimedOut ? (-5) : (-10));
			}

			// Token: 0x0600583A RID: 22586 RVA: 0x0019B93C File Offset: 0x00199B3C
			private void RemoveRemainingHorses()
			{
				int num = this._animalCountToDeliver;
				foreach (ItemRosterElement itemRosterElement in MobileParty.MainParty.ItemRoster)
				{
					if (itemRosterElement.EquipmentElement.Item == this._herdTypeToDeliver)
					{
						int amount = itemRosterElement.Amount;
						if (amount >= num)
						{
							PartyBase.MainParty.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, -num);
							break;
						}
						num -= amount;
						PartyBase.MainParty.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, -amount);
					}
				}
			}

			// Token: 0x0600583B RID: 22587 RVA: 0x0019B9F0 File Offset: 0x00199BF0
			private void AddHerdAndShepherdsToMainParty()
			{
				MobileParty.MainParty.ItemRoster.AddToCounts(this._herdTypeToDeliver, this._animalCountToDeliver);
				MobileParty.MainParty.ItemRoster.AddToCounts(DefaultItems.Grain, 5);
				TextObject textObject = new TextObject("{=GgBtpOEm}{.%}{ANIMAL_COUNT} {?ANIMAL_COUNT > 1}{PLURAL(ANIMAL_TYPE)}{?}{ANIMAL_TYPE}{\\?}{.%} added to your party.", null);
				textObject.SetTextVariable("ANIMAL_COUNT", this._animalCountToDeliver);
				textObject.SetTextVariable("ANIMAL_TYPE", this._herdTypeToDeliver.Name);
				MBInformationManager.AddQuickInformation(textObject, 0, null, null, "");
			}

			// Token: 0x0600583C RID: 22588 RVA: 0x0019BA70 File Offset: 0x00199C70
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetDeliveryDialogFlow(), this);
			}

			// Token: 0x0600583D RID: 22589 RVA: 0x0019BA8E File Offset: 0x00199C8E
			protected override void HourlyTick()
			{
			}

			// Token: 0x0600583E RID: 22590 RVA: 0x0019BA90 File Offset: 0x00199C90
			protected override void RegisterEvents()
			{
				CampaignEvents.HeroKilledEvent.AddNonSerializedListener(this, new Action<Hero, Hero, KillCharacterAction.KillCharacterActionDetail, bool>(this.OnHeroKilled));
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
			}

			// Token: 0x0600583F RID: 22591 RVA: 0x0019BAF9 File Offset: 0x00199CF9
			public override void OnHeroCanHaveCampaignIssuesInfoIsRequested(Hero hero, ref bool result)
			{
				if (hero == this._targetHero)
				{
					result = false;
				}
			}

			// Token: 0x06005840 RID: 22592 RVA: 0x0019BB07 File Offset: 0x00199D07
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x1700111F RID: 4383
			// (get) Token: 0x06005841 RID: 22593 RVA: 0x0019BB1A File Offset: 0x00199D1A
			protected override TextObject TargetHeroDiedLogText
			{
				get
				{
					return new TextObject("{=m41vdhSR}{QUEST_TARGET.LINK} is no longer alive. It might not be your fault that you didn't get the herd to {?QUEST_TARGET.GENDER}her{?}him{\\?} in time, but many people will consider this breach of trust.", null);
				}
			}

			// Token: 0x06005842 RID: 22594 RVA: 0x0019BB28 File Offset: 0x00199D28
			private void OnHeroKilled(Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail, bool showNotification)
			{
				if (victim == this._targetHero)
				{
					TextObject textObject = ((detail == KillCharacterAction.KillCharacterActionDetail.Lost) ? this.TargetHeroDisappearedLogText : this.TargetHeroDiedLogText);
					StringHelpers.SetCharacterProperties("QUEST_TARGET", this._targetHero.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					base.AddLog(textObject, false);
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x06005843 RID: 22595 RVA: 0x0019BB91 File Offset: 0x00199D91
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLog);
				}
			}

			// Token: 0x06005844 RID: 22596 RVA: 0x0019BBC0 File Offset: 0x00199DC0
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.QuestCanceledWarDeclaredLog, false);
			}

			// Token: 0x04001C8B RID: 7307
			[SaveableField(10)]
			private readonly Settlement _targetSettlement;

			// Token: 0x04001C8C RID: 7308
			[SaveableField(20)]
			private readonly Hero _targetHero;

			// Token: 0x04001C8D RID: 7309
			[SaveableField(30)]
			private readonly ItemObject _herdTypeToDeliver;

			// Token: 0x04001C8E RID: 7310
			[SaveableField(40)]
			private readonly int _animalCountToDeliver;

			// Token: 0x04001C8F RID: 7311
			[SaveableField(70)]
			private int _rewardGold;

			// Token: 0x04001C90 RID: 7312
			[SaveableField(215)]
			private JournalLog _playerStartsQuestLog;
		}

		// Token: 0x0200070D RID: 1805
		public class HeadmanNeedsToDeliverAHerdIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005849 RID: 22601 RVA: 0x0019BC91 File Offset: 0x00199E91
			public HeadmanNeedsToDeliverAHerdIssueTypeDefiner()
				: base(430000)
			{
			}

			// Token: 0x0600584A RID: 22602 RVA: 0x0019BC9E File Offset: 0x00199E9E
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue), 1, null);
				base.AddClassDefinition(typeof(HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest), 2, null);
			}
		}
	}
}
