using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000379 RID: 889
	public class VillageNeedsCraftingMaterialsIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x060033C1 RID: 13249 RVA: 0x000D4E30 File Offset: 0x000D3030
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x060033C2 RID: 13250 RVA: 0x000D4E4C File Offset: 0x000D304C
		private void OnCheckForIssue(Hero hero)
		{
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, this.ConditionsHold(hero) ? new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnStartIssue), typeof(VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue), IssueBase.IssueFrequency.Rare, null) : new PotentialIssueData(typeof(VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue), IssueBase.IssueFrequency.Rare));
		}

		// Token: 0x060033C3 RID: 13251 RVA: 0x000D4EA1 File Offset: 0x000D30A1
		private bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.IsRuralNotable && !issueGiver.MapFaction.IsAtWarWith(Clan.PlayerClan);
		}

		// Token: 0x060033C4 RID: 13252 RVA: 0x000D4EC0 File Offset: 0x000D30C0
		private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
		{
			return new VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue(issueOwner);
		}

		// Token: 0x060033C5 RID: 13253 RVA: 0x000D4EC8 File Offset: 0x000D30C8
		private static ItemObject SelectCraftingMaterial()
		{
			int num = MBRandom.RandomInt(0, 2);
			if (num == 0)
			{
				return DefaultItems.IronIngot1;
			}
			if (num != 1)
			{
				return DefaultItems.IronIngot1;
			}
			return DefaultItems.IronIngot2;
		}

		// Token: 0x060033C6 RID: 13254 RVA: 0x000D4EF7 File Offset: 0x000D30F7
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x04000EB7 RID: 3767
		private const IssueBase.IssueFrequency VillageNeedsCraftingMaterialsIssueFrequency = IssueBase.IssueFrequency.Rare;

		// Token: 0x02000759 RID: 1881
		public class VillageNeedsCraftingMaterialsIssue : IssueBase
		{
			// Token: 0x06005F55 RID: 24405 RVA: 0x001B6851 File Offset: 0x001B4A51
			internal static void AutoGeneratedStaticCollectObjectsVillageNeedsCraftingMaterialsIssue(object o, List<object> collectedObjects)
			{
				((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005F56 RID: 24406 RVA: 0x001B685F File Offset: 0x001B4A5F
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._requestedItem);
			}

			// Token: 0x06005F57 RID: 24407 RVA: 0x001B6874 File Offset: 0x001B4A74
			internal static object AutoGeneratedGetMemberValue_requestedItem(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue)o)._requestedItem;
			}

			// Token: 0x06005F58 RID: 24408 RVA: 0x001B6881 File Offset: 0x001B4A81
			internal static object AutoGeneratedGetMemberValue_promisedPayment(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue)o)._promisedPayment;
			}

			// Token: 0x17001350 RID: 4944
			// (get) Token: 0x06005F59 RID: 24409 RVA: 0x001B6893 File Offset: 0x001B4A93
			private int _numberOfRequestedItem
			{
				get
				{
					return MathF.Round((float)((int)(750f / (float)this._requestedItem.Value)) * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001351 RID: 4945
			// (get) Token: 0x06005F5A RID: 24410 RVA: 0x001B68B5 File Offset: 0x001B4AB5
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return 500 + (int)(700f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001352 RID: 4946
			// (get) Token: 0x06005F5B RID: 24411 RVA: 0x001B68CA File Offset: 0x001B4ACA
			protected override bool IssueQuestCanBeDuplicated
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001353 RID: 4947
			// (get) Token: 0x06005F5C RID: 24412 RVA: 0x001B68CD File Offset: 0x001B4ACD
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 4;
				}
			}

			// Token: 0x17001354 RID: 4948
			// (get) Token: 0x06005F5D RID: 24413 RVA: 0x001B68D0 File Offset: 0x001B4AD0
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return (int)(2f + 4f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x06005F5E RID: 24414 RVA: 0x001B68E5 File Offset: 0x001B4AE5
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.VillageHearth)
				{
					return -0.2f;
				}
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06005F5F RID: 24415 RVA: 0x001B6908 File Offset: 0x001B4B08
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>(DefaultSkills.Crafting, 120);
			}

			// Token: 0x06005F60 RID: 24416 RVA: 0x001B6916 File Offset: 0x001B4B16
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 0, false);
			}

			// Token: 0x06005F61 RID: 24417 RVA: 0x001B6930 File Offset: 0x001B4B30
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this.GetPayment(), false);
				this.RelationshipChangeWithIssueOwner = 5;
				base.IssueSettlement.Village.Hearth += 60f;
				base.IssueOwner.AddPower(10f);
			}

			// Token: 0x06005F62 RID: 24418 RVA: 0x001B6982 File Offset: 0x001B4B82
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 0, false);
			}

			// Token: 0x17001355 RID: 4949
			// (get) Token: 0x06005F63 RID: 24419 RVA: 0x001B6993 File Offset: 0x001B4B93
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=eR7P1cVA}{VILLAGE} Needs Crafting Materials", null);
					textObject.SetTextVariable("VILLAGE", base.IssueOwner.CurrentSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001356 RID: 4950
			// (get) Token: 0x06005F64 RID: 24420 RVA: 0x001B69BC File Offset: 0x001B4BBC
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=5CJrR0X3}{ISSUE_GIVER.LINK} in the village requested crafting materials for their ongoing project.", null);
					textObject.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, false);
					return textObject;
				}
			}

			// Token: 0x17001357 RID: 4951
			// (get) Token: 0x06005F65 RID: 24421 RVA: 0x001B69E0 File Offset: 0x001B4BE0
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=095beaQ5}Yes, there's a lot of work we need to do around the village, and we're short on the materials that our smith needs to make us tools and fittings. Do you think you could get us some? We'll pay well.[ib:demure][if:convo_dismayed]", null);
				}
			}

			// Token: 0x17001358 RID: 4952
			// (get) Token: 0x06005F66 RID: 24422 RVA: 0x001B69ED File Offset: 0x001B4BED
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=xmu89biL}Maybe I can help. What do you need exactly?", null);
				}
			}

			// Token: 0x17001359 RID: 4953
			// (get) Token: 0x06005F67 RID: 24423 RVA: 0x001B69FC File Offset: 0x001B4BFC
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=PftlaE0x}We need {REQUESTED_ITEM_COUNT} {?(REQUESTED_ITEM_COUNT > 1)}{PLURAL(REQUESTED_ITEM)}{?}{REQUESTED_ITEM}{\\?} in {NUMBER_OF_DAYS} days. We need to repair some roofs before the next big storms. I can offer {PAYMENT}{GOLD_ICON}. What do you say?", null);
					textObject.SetTextVariable("PAYMENT", this.GetPayment());
					textObject.SetTextVariable("REQUESTED_ITEM", this._requestedItem.Name);
					textObject.SetTextVariable("REQUESTED_ITEM_COUNT", this._numberOfRequestedItem);
					textObject.SetTextVariable("NUMBER_OF_DAYS", 30);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			// Token: 0x1700135A RID: 4954
			// (get) Token: 0x06005F68 RID: 24424 RVA: 0x001B6A6E File Offset: 0x001B4C6E
			public override TextObject IssuePlayerResponseAfterAlternativeExplanation
			{
				get
				{
					return new TextObject("{=i96OaGH3}Is there anything else I could do to help?", null);
				}
			}

			// Token: 0x1700135B RID: 4955
			// (get) Token: 0x06005F69 RID: 24425 RVA: 0x001B6A7B File Offset: 0x001B4C7B
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					return new TextObject("{=WzdhPF7M}Well, if we had some extra skilled labor, we could probably melt down old tools and reforge them. That's too much work for just our smith by himself, but maybe he could do it with someone proficient in crafting to help him.[ib:demure2][if:convo_thinking]", null);
				}
			}

			// Token: 0x1700135C RID: 4956
			// (get) Token: 0x06005F6A RID: 24426 RVA: 0x001B6A88 File Offset: 0x001B4C88
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=WsmH9Cfd}I will provide what you need.", null);
				}
			}

			// Token: 0x1700135D RID: 4957
			// (get) Token: 0x06005F6B RID: 24427 RVA: 0x001B6A95 File Offset: 0x001B4C95
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=8DWTTnpP}My comrade will help your smith to produce what you need.", null);
				}
			}

			// Token: 0x1700135E RID: 4958
			// (get) Token: 0x06005F6C RID: 24428 RVA: 0x001B6AA2 File Offset: 0x001B4CA2
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					return new TextObject("{=xlagNKZ2}Thank you. With their help, we should be able to make what we need.[if:convo_astonished]", null);
				}
			}

			// Token: 0x1700135F RID: 4959
			// (get) Token: 0x06005F6D RID: 24429 RVA: 0x001B6AAF File Offset: 0x001B4CAF
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=P3Uu0Ham}Your companion is still working with our smith. I hope they will finish the order in time.[if:convo_approving]", null);
				}
			}

			// Token: 0x17001360 RID: 4960
			// (get) Token: 0x06005F6E RID: 24430 RVA: 0x001B6ABC File Offset: 0x001B4CBC
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17001361 RID: 4961
			// (get) Token: 0x06005F6F RID: 24431 RVA: 0x001B6ABF File Offset: 0x001B4CBF
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001362 RID: 4962
			// (get) Token: 0x06005F70 RID: 24432 RVA: 0x001B6AC2 File Offset: 0x001B4CC2
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Duration;
				}
			}

			// Token: 0x17001363 RID: 4963
			// (get) Token: 0x06005F71 RID: 24433 RVA: 0x001B6AC8 File Offset: 0x001B4CC8
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=1XuYGQcT}{ISSUE_GIVER.LINK} told you that {?QUEST_GIVER.GENDER}her{?}his{\\?} local smith needs {REQUESTED_ITEM} to forge more tools. You asked your companion {COMPANION.LINK} to help the local smith and craft {REQUESTED_ITEM_COUNT} {?(REQUESTED_ITEM_COUNT > 1)}{PLURAL(REQUESTED_ITEM)}{?}{REQUESTED_ITEM}{\\?} for the village. Your companion will rejoin your party in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("REQUESTED_ITEM", this._requestedItem.Name);
					textObject.SetTextVariable("REQUESTED_ITEM_COUNT", this._numberOfRequestedItem);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			// Token: 0x17001364 RID: 4964
			// (get) Token: 0x06005F72 RID: 24434 RVA: 0x001B6B6C File Offset: 0x001B4D6C
			public override TextObject IssueAlternativeSolutionSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=n86jgG3m}Your companion {COMPANION.LINK} has helped the local smith and produced {REQUESTED_AMOUNT} {?(REQUESTED_AMOUNT > 1)}{PLURAL(REQUESTED_GOOD)}{?}{REQUESTED_GOOD}{\\?} as you promised.", null);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("REQUESTED_AMOUNT", this._numberOfRequestedItem);
					textObject.SetTextVariable("REQUESTED_GOOD", this._requestedItem.Name);
					return textObject;
				}
			}

			// Token: 0x06005F73 RID: 24435 RVA: 0x001B6BC7 File Offset: 0x001B4DC7
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005F74 RID: 24436 RVA: 0x001B6BC9 File Offset: 0x001B4DC9
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005F75 RID: 24437 RVA: 0x001B6BCB File Offset: 0x001B4DCB
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(30f), this.GetPayment(), this._requestedItem, this._numberOfRequestedItem);
			}

			// Token: 0x06005F76 RID: 24438 RVA: 0x001B6BF5 File Offset: 0x001B4DF5
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.Rare;
			}

			// Token: 0x06005F77 RID: 24439 RVA: 0x001B6BF8 File Offset: 0x001B4DF8
			public override void AlternativeSolutionStartConsequence()
			{
				this._promisedPayment = this.GetPayment();
			}

			// Token: 0x06005F78 RID: 24440 RVA: 0x001B6C08 File Offset: 0x001B4E08
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill)
			{
				flags = IssueBase.PreconditionFlags.None;
				relationHero = null;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (FactionManager.IsAtWarAgainstFaction(issueGiver.MapFaction, Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005F79 RID: 24441 RVA: 0x001B6C58 File Offset: 0x001B4E58
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x06005F7A RID: 24442 RVA: 0x001B6C5A File Offset: 0x001B4E5A
			public override bool IssueStayAliveConditions()
			{
				return !base.IssueOwner.CurrentSettlement.IsRaided && !base.IssueOwner.CurrentSettlement.IsUnderRaid;
			}

			// Token: 0x06005F7B RID: 24443 RVA: 0x001B6C83 File Offset: 0x001B4E83
			public VillageNeedsCraftingMaterialsIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
				this._requestedItem = VillageNeedsCraftingMaterialsIssueBehavior.SelectCraftingMaterial();
			}

			// Token: 0x06005F7C RID: 24444 RVA: 0x001B6CA4 File Offset: 0x001B4EA4
			private int GetPayment()
			{
				if (this._promisedPayment != 0)
				{
					return this._promisedPayment;
				}
				return 750 + (base.IssueSettlement.Village.Bound.Town.MarketData.GetPrice(this._requestedItem, null, false, null) + QuestHelper.GetAveragePriceOfItemInTheWorld(this._requestedItem) / 2) * this._numberOfRequestedItem;
			}

			// Token: 0x04001DF1 RID: 7665
			private const int TimeLimit = 30;

			// Token: 0x04001DF2 RID: 7666
			private const int PowerChangeForQuestGiver = 10;

			// Token: 0x04001DF3 RID: 7667
			private const int RelationWithIssueOwnerRewardOnSuccess = 5;

			// Token: 0x04001DF4 RID: 7668
			private const int VillageHeartChangeOnAlternativeSuccess = 60;

			// Token: 0x04001DF5 RID: 7669
			private const int RequiredSkillValueForAlternativeSolution = 120;

			// Token: 0x04001DF6 RID: 7670
			[SaveableField(1)]
			private readonly ItemObject _requestedItem;

			// Token: 0x04001DF7 RID: 7671
			[SaveableField(4)]
			private int _promisedPayment;
		}

		// Token: 0x0200075A RID: 1882
		public class VillageNeedsCraftingMaterialsIssueQuest : QuestBase
		{
			// Token: 0x06005F7D RID: 24445 RVA: 0x001B6D03 File Offset: 0x001B4F03
			internal static void AutoGeneratedStaticCollectObjectsVillageNeedsCraftingMaterialsIssueQuest(object o, List<object> collectedObjects)
			{
				((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005F7E RID: 24446 RVA: 0x001B6D11 File Offset: 0x001B4F11
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._requestedItem);
				collectedObjects.Add(this._playerAcceptedQuestLog);
				collectedObjects.Add(this._playerHasNeededItemsLog);
			}

			// Token: 0x06005F7F RID: 24447 RVA: 0x001B6D3E File Offset: 0x001B4F3E
			internal static object AutoGeneratedGetMemberValue_requestedItemAmount(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest)o)._requestedItemAmount;
			}

			// Token: 0x06005F80 RID: 24448 RVA: 0x001B6D50 File Offset: 0x001B4F50
			internal static object AutoGeneratedGetMemberValue_requestedItem(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest)o)._requestedItem;
			}

			// Token: 0x06005F81 RID: 24449 RVA: 0x001B6D5D File Offset: 0x001B4F5D
			internal static object AutoGeneratedGetMemberValue_playerAcceptedQuestLog(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest)o)._playerAcceptedQuestLog;
			}

			// Token: 0x06005F82 RID: 24450 RVA: 0x001B6D6A File Offset: 0x001B4F6A
			internal static object AutoGeneratedGetMemberValue_playerHasNeededItemsLog(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest)o)._playerHasNeededItemsLog;
			}

			// Token: 0x17001365 RID: 4965
			// (get) Token: 0x06005F83 RID: 24451 RVA: 0x001B6D78 File Offset: 0x001B4F78
			private TextObject QuestStartedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=YZeKScP5}{QUEST_GIVER.LINK} told you that {?QUEST_GIVER.GENDER}her{?}his{\\?} local smith needs {REQUESTED_ITEM} to forge more tools. {?QUEST_GIVER.GENDER}She{?}He{\\?} asked you to bring {REQUESTED_ITEM_AMOUNT} {?(REQUESTED_ITEM_AMOUNT > 1)}{PLURAL(REQUESTED_ITEM)}{?}{REQUESTED_ITEM}{\\?} to {?QUEST_GIVER.GENDER}her{?}him{\\?}.", null);
					textObject.SetTextVariable("REQUESTED_ITEM_AMOUNT", this._requestedItemAmount);
					textObject.SetTextVariable("REQUESTED_ITEM", this._requestedItem.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001366 RID: 4966
			// (get) Token: 0x06005F84 RID: 24452 RVA: 0x001B6DD4 File Offset: 0x001B4FD4
			private TextObject QuestSuccessLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=LiDSTrvV}You brought {REQUESTED_ITEM_AMOUNT} {?(REQUESTED_ITEM_AMOUNT > 1)}{PLURAL(REQUESTED_ITEM)}{?}{REQUESTED_ITEM}{\\?} to {?QUEST_GIVER.GENDER}her{?}him{\\?} as promised.", null);
					textObject.SetTextVariable("REQUESTED_ITEM_AMOUNT", this._requestedItemAmount);
					textObject.SetTextVariable("REQUESTED_ITEM", this._requestedItem.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001367 RID: 4967
			// (get) Token: 0x06005F85 RID: 24453 RVA: 0x001B6E30 File Offset: 0x001B5030
			private TextObject QuestCanceledWarDeclaredLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001368 RID: 4968
			// (get) Token: 0x06005F86 RID: 24454 RVA: 0x001B6E64 File Offset: 0x001B5064
			private TextObject QuestGiverVillageRaidedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=gJG0xmAq}{QUEST_GIVER.LINK}'s village {QUEST_SETTLEMENT} was raided. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x17001369 RID: 4969
			// (get) Token: 0x06005F87 RID: 24455 RVA: 0x001B6EB4 File Offset: 0x001B50B4
			private TextObject QuestFailedWithTimeOutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=nmz1ky2D}You failed to deliver {REQUESTED_ITEM_AMOUNT} {?(REQUESTED_ITEM_AMOUNT > 1)}{PLURAL(REQUESTED_ITEM)}{?}{REQUESTED_ITEM}{\\?} to {QUEST_GIVER.LINK} in time.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("REQUESTED_ITEM_AMOUNT", this._requestedItemAmount);
					textObject.SetTextVariable("REQUESTED_ITEM", this._requestedItem.Name);
					return textObject;
				}
			}

			// Token: 0x1700136A RID: 4970
			// (get) Token: 0x06005F88 RID: 24456 RVA: 0x001B6F0F File Offset: 0x001B510F
			private TextObject PlayerHasNeededItemsLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=MxpPkytG}You now have enough {ITEM} to complete the quest. Return to {QUEST_SETTLEMENT} to hand them over.", null);
					textObject.SetTextVariable("ITEM", this._requestedItem.Name);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x06005F89 RID: 24457 RVA: 0x001B6F4F File Offset: 0x001B514F
			public VillageNeedsCraftingMaterialsIssueQuest(string questId, Hero questGiver, CampaignTime duration, int rewardGold, ItemObject requestedItem, int requestedItemAmount)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._requestedItem = requestedItem;
				this._requestedItemAmount = requestedItemAmount;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x1700136B RID: 4971
			// (get) Token: 0x06005F8A RID: 24458 RVA: 0x001B6F78 File Offset: 0x001B5178
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=LgiRMbgE}{ISSUE_SETTLEMENT} Needs Crafting Materials", null);
					textObject.SetTextVariable("ISSUE_SETTLEMENT", base.QuestGiver.CurrentSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700136C RID: 4972
			// (get) Token: 0x06005F8B RID: 24459 RVA: 0x001B6FA1 File Offset: 0x001B51A1
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x06005F8C RID: 24460 RVA: 0x001B6FA4 File Offset: 0x001B51A4
			protected override void SetDialogs()
			{
				TextObject npcText = new TextObject("{=UbUokDyI}Thank you. We'd appreciate it if you got the goods to us as quickly as possible. Good luck![ib:nervous2][if:convo_excited]", null);
				TextObject textObject = new TextObject("{=4c9ySfVj}Did you find what we needed, {?PLAYER.GENDER}madam{?}sir{\\?}?", null);
				TextObject textObject2 = new TextObject("{=nEGe8rUd}Thank you for your help, {?PLAYER.GENDER}madam{?}sir{\\?}. Here is what we promised.", null);
				TextObject npcText2 = new TextObject("{=sTfr1C8H}Thank you. But if the storms come before you find them, well, that would be bad for us.[ib:nervous2][if:convo_nervous]", null);
				textObject.SetCharacterProperties("PLAYER", Hero.MainHero.CharacterObject, false);
				textObject2.SetCharacterProperties("PLAYER", Hero.MainHero.CharacterObject, false);
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(npcText, null, null, null, null).Condition(() => CharacterObject.OneToOneConversationCharacter == base.QuestGiver.CharacterObject)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(textObject, null, null, null, null).Condition(() => CharacterObject.OneToOneConversationCharacter == base.QuestGiver.CharacterObject)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=bLRGix1b}Yes, I have them with me.", null), null, null, null)
					.ClickableCondition(new ConversationSentence.OnClickableConditionDelegate(this.CompleteQuestClickableConditions))
					.NpcLine(textObject2, null, null, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += this.Success;
					})
					.CloseDialog()
					.PlayerOption(new TextObject("{=D8KFcE2i}Not yet, I am still working on it.", null), null, null, null)
					.NpcLine(npcText2, null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06005F8D RID: 24461 RVA: 0x001B70F4 File Offset: 0x001B52F4
			private bool CompleteQuestClickableConditions(out TextObject explanation)
			{
				if (this._playerAcceptedQuestLog.CurrentProgress >= this._requestedItemAmount)
				{
					explanation = null;
					return true;
				}
				explanation = new TextObject("{=EmBla2xa}You don't have enough {ITEM}", null);
				explanation.SetTextVariable("ITEM", this._requestedItem.Name);
				return false;
			}

			// Token: 0x06005F8E RID: 24462 RVA: 0x001B7134 File Offset: 0x001B5334
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x06005F8F RID: 24463 RVA: 0x001B713C File Offset: 0x001B533C
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005F90 RID: 24464 RVA: 0x001B7140 File Offset: 0x001B5340
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				int requiredItemCountOnPlayer = this.GetRequiredItemCountOnPlayer();
				TextObject textObject = new TextObject("{=nAEhfGJk}Collect {ITEM}", null);
				textObject.SetTextVariable("ITEM", this._requestedItem.Name);
				this._playerAcceptedQuestLog = base.AddDiscreteLog(this.QuestStartedLogText, textObject, requiredItemCountOnPlayer, this._requestedItemAmount, null, false);
			}

			// Token: 0x06005F91 RID: 24465 RVA: 0x001B7199 File Offset: 0x001B5399
			protected override void OnTimedOut()
			{
				this.Fail();
			}

			// Token: 0x06005F92 RID: 24466 RVA: 0x001B71A4 File Offset: 0x001B53A4
			private void Success()
			{
				base.AddLog(this.QuestSuccessLogText, false);
				ItemRosterElement itemRosterElement = new ItemRosterElement(this._requestedItem, this._requestedItemAmount, null);
				GiveItemAction.ApplyForParties(PartyBase.MainParty, Settlement.CurrentSettlement.Party, itemRosterElement);
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this.RewardGold, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 30)
				});
				base.QuestGiver.AddPower(10f);
				this.RelationshipChangeWithQuestGiver = 5;
				base.QuestGiver.CurrentSettlement.Village.Hearth += 30f;
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005F93 RID: 24467 RVA: 0x001B7258 File Offset: 0x001B5458
			private void Fail()
			{
				base.AddLog(this.QuestFailedWithTimeOutLogText, false);
				base.QuestGiver.AddPower(-10f);
				this.RelationshipChangeWithQuestGiver = -5;
				base.QuestGiver.CurrentSettlement.Village.Hearth += -40f;
				base.CompleteQuestWithFail(null);
			}

			// Token: 0x06005F94 RID: 24468 RVA: 0x001B72B4 File Offset: 0x001B54B4
			private int GetRequiredItemCountOnPlayer()
			{
				int itemNumber = PartyBase.MainParty.ItemRoster.GetItemNumber(this._requestedItem);
				if (itemNumber >= this._requestedItemAmount)
				{
					TextObject textObject = new TextObject("{=MTCrXEvj}You have enough {ITEM} to complete the quest. Return to {QUEST_SETTLEMENT} to hand it over.", null);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.Name);
					textObject.SetTextVariable("ITEM", this._requestedItem.Name);
					MBInformationManager.AddQuickInformation(textObject, 0, null, null, "");
				}
				if (itemNumber <= this._requestedItemAmount)
				{
					return itemNumber;
				}
				return this._requestedItemAmount;
			}

			// Token: 0x06005F95 RID: 24469 RVA: 0x001B733C File Offset: 0x001B553C
			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.RaidCompletedEvent.AddNonSerializedListener(this, new Action<BattleSideEnum, RaidEventComponent>(this.OnRaidCompleted));
				CampaignEvents.PlayerInventoryExchangeEvent.AddNonSerializedListener(this, new Action<List<ValueTuple<ItemRosterElement, int>>, List<ValueTuple<ItemRosterElement, int>>, bool>(this.OnPlayerInventoryExchange));
				CampaignEvents.OnNewItemCraftedEvent.AddNonSerializedListener(this, new Action<ItemObject, ItemModifier, bool>(this.OnItemCrafted));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
				CampaignEvents.OnEquipmentSmeltedByHeroEvent.AddNonSerializedListener(this, new Action<Hero, EquipmentElement>(this.OnEquipmentSmeltedByHero));
				CampaignEvents.OnItemsRefinedEvent.AddNonSerializedListener(this, new Action<Hero, Crafting.RefiningFormula>(this.OnItemsRefined));
			}

			// Token: 0x06005F96 RID: 24470 RVA: 0x001B7401 File Offset: 0x001B5601
			private void OnItemsRefined(Hero hero, Crafting.RefiningFormula refiningFormula)
			{
				this.UpdateQuestLog();
			}

			// Token: 0x06005F97 RID: 24471 RVA: 0x001B7409 File Offset: 0x001B5609
			private void OnEquipmentSmeltedByHero(Hero hero, EquipmentElement equipmentElement)
			{
				this.UpdateQuestLog();
			}

			// Token: 0x06005F98 RID: 24472 RVA: 0x001B7411 File Offset: 0x001B5611
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.QuestCanceledWarDeclaredLogText, this.QuestCanceledWarDeclaredLogText, false);
			}

			// Token: 0x06005F99 RID: 24473 RVA: 0x001B7429 File Offset: 0x001B5629
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x06005F9A RID: 24474 RVA: 0x001B743C File Offset: 0x001B563C
			private void OnItemCrafted(ItemObject item, ItemModifier overriddenItemModifier, bool isCraftingOrderItem)
			{
				this.UpdateQuestLog();
			}

			// Token: 0x06005F9B RID: 24475 RVA: 0x001B7444 File Offset: 0x001B5644
			private void OnPlayerInventoryExchange(List<ValueTuple<ItemRosterElement, int>> purchasedItems, List<ValueTuple<ItemRosterElement, int>> soldItems, bool isTrading)
			{
				this.UpdateQuestLog();
			}

			// Token: 0x06005F9C RID: 24476 RVA: 0x001B744C File Offset: 0x001B564C
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLogText);
				}
			}

			// Token: 0x06005F9D RID: 24477 RVA: 0x001B747B File Offset: 0x001B567B
			private void OnRaidCompleted(BattleSideEnum battleSide, RaidEventComponent mapEvent)
			{
				if (mapEvent.MapEventSettlement == base.QuestGiver.CurrentSettlement)
				{
					base.CompleteQuestWithCancel(this.QuestGiverVillageRaidedLogText);
				}
			}

			// Token: 0x06005F9E RID: 24478 RVA: 0x001B749C File Offset: 0x001B569C
			private void CheckIfPlayerReadyToReturnItems()
			{
				if (this._playerHasNeededItemsLog == null && this._playerAcceptedQuestLog.CurrentProgress >= this._requestedItemAmount)
				{
					this._playerHasNeededItemsLog = base.AddLog(this.PlayerHasNeededItemsLogText, false);
					return;
				}
				if (this._playerHasNeededItemsLog != null && this._playerAcceptedQuestLog.CurrentProgress < this._requestedItemAmount)
				{
					base.RemoveLog(this._playerHasNeededItemsLog);
					this._playerHasNeededItemsLog = null;
				}
			}

			// Token: 0x06005F9F RID: 24479 RVA: 0x001B7506 File Offset: 0x001B5706
			private void UpdateQuestLog()
			{
				this._playerAcceptedQuestLog.UpdateCurrentProgress(this.GetRequiredItemCountOnPlayer());
				this.CheckIfPlayerReadyToReturnItems();
			}

			// Token: 0x04001DF8 RID: 7672
			[SaveableField(10)]
			private readonly int _requestedItemAmount;

			// Token: 0x04001DF9 RID: 7673
			[SaveableField(20)]
			private readonly ItemObject _requestedItem;

			// Token: 0x04001DFA RID: 7674
			[SaveableField(30)]
			private JournalLog _playerAcceptedQuestLog;

			// Token: 0x04001DFB RID: 7675
			[SaveableField(40)]
			private JournalLog _playerHasNeededItemsLog;

			// Token: 0x04001DFC RID: 7676
			private const int SuccessRelationBonus = 5;

			// Token: 0x04001DFD RID: 7677
			private const int FailRelationPenalty = -5;

			// Token: 0x04001DFE RID: 7678
			private const int SuccessPowerBonus = 10;

			// Token: 0x04001DFF RID: 7679
			private const int FailPowerPenalty = -10;

			// Token: 0x04001E00 RID: 7680
			private const int SuccessHonorBonus = 30;

			// Token: 0x04001E01 RID: 7681
			private const int FailWithCrimeHonorPenalty = -50;

			// Token: 0x04001E02 RID: 7682
			private const int SuccessHearthBonus = 30;

			// Token: 0x04001E03 RID: 7683
			private const int FailToDeliverInTimeHearthPenalty = -40;
		}

		// Token: 0x0200075B RID: 1883
		public class VillageNeedsCraftingMaterialsIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005FA3 RID: 24483 RVA: 0x001B7564 File Offset: 0x001B5764
			public VillageNeedsCraftingMaterialsIssueTypeDefiner()
				: base(601000)
			{
			}

			// Token: 0x06005FA4 RID: 24484 RVA: 0x001B7571 File Offset: 0x001B5771
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue), 1, null);
				base.AddClassDefinition(typeof(VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest), 2, null);
			}
		}
	}
}
