using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x02000697 RID: 1687
	internal enum IIDENTITYAUTHORITY_REFERENCE_IDENTITY_TO_TEXT_FLAGS
	{
		// Token: 0x04002214 RID: 8724
		IIDENTITYAUTHORITY_REFERENCE_IDENTITY_TO_TEXT_FLAG_CANONICAL = 1
	}
}
