using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x02000698 RID: 1688
	internal enum IIDENTITYAUTHORITY_DOES_DEFINITION_MATCH_REFERENCE_FLAGS
	{
		// Token: 0x04002216 RID: 8726
		IIDENTITYAUTHORITY_DOES_DEFINITION_MATCH_REFERENCE_FLAG_EXACT_MATCH_REQUIRED = 1
	}
}
