using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Encyclopedia.List;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Encyclopedia;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x02000064 RID: 100
	public class EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaPageVM_Dependency_5_EncyclopediaItemListItem__InheritedPrefab : EncyclopediaListItemButtonWidget
	{
		// Token: 0x06001770 RID: 6000 RVA: 0x000AB003 File Offset: 0x000A9203
		public EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaPageVM_Dependency_5_EncyclopediaItemListItem__InheritedPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06001771 RID: 6001 RVA: 0x000AB00C File Offset: 0x000A920C
		public virtual void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new ListPanel(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_1 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_1);
			this._widget_0_2 = new ScrollingTextWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_2);
			this._widget_0_3 = new TextWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_3);
		}

		// Token: 0x06001772 RID: 6002 RVA: 0x000AB0CA File Offset: 0x000A92CA
		public virtual void SetIds()
		{
			this._widget_0.Id = "ItemParentListPanel";
			this._widget_0_2.Id = "ListItemNameTextWidget";
			this._widget_0_3.Id = "ListComparedValueTextWidget";
		}

		// Token: 0x06001773 RID: 6003 RVA: 0x000AB0FC File Offset: 0x000A92FC
		public virtual void SetAttributes()
		{
			base.DoNotPassEventsToChildren = true;
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.CoverChildren;
			base.SuggestedHeight = 37f;
			base.Brush = base.Context.GetBrush("Encyclopedia.ListButton");
			base.InfoAvailableItemNameBrush = base.Context.GetBrush("EncyclopediaList.Filter.Name.Text");
			base.InfoUnvailableItemNameBrush = base.Context.GetBrush("EncyclopediaList.Item.InfoUnavailable.Name.Text");
			base.ListItemNameTextWidget = this._widget_0_2;
			base.ListComparedValueTextWidget = this._widget_0_3;
			this._widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.StackLayout.LayoutMethod = LayoutMethod.HorizontalLeftToRight;
			this._widget_0_0.DoNotPassEventsToChildren = true;
			this._widget_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.SuggestedWidth = 35f;
			this._widget_0_0.SuggestedHeight = 35f;
			this._widget_0_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0.Sprite = base.Context.SpriteData.GetSprite("Encyclopedia\\star_without_glow");
			this._widget_0_0.Color = new Color(0.9960785f, 0.7568628f, 0.3411765f, 1f);
			this._widget_0_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_1.SuggestedWidth = 35f;
			this._widget_0_1.SuggestedHeight = 35f;
			this._widget_0_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_1.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_2.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_2.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_2.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_2.SuggestedWidth = 500f;
			this._widget_0_2.MarginLeft = 5f;
			this._widget_0_3.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_3.MarginLeft = 30f;
		}

		// Token: 0x06001774 RID: 6004 RVA: 0x000AB308 File Offset: 0x000A9508
		public virtual void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
				this._widget_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1;
				this._widget_0_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_2;
				this._widget_0_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3;
				this._datasource_Root = null;
			}
		}

		// Token: 0x06001775 RID: 6005 RVA: 0x000AB818 File Offset: 0x000A9A18
		public virtual void SetDataSource(EncyclopediaListItemVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06001776 RID: 6006 RVA: 0x000AB824 File Offset: 0x000A9A24
		private void EventListenerOf_widget(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.Execute();
			}
			if (commandName == "HoverBegin")
			{
				this._datasource_Root.ExecuteBeginTooltip();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root.ExecuteEndTooltip();
			}
		}

		// Token: 0x06001777 RID: 6007 RVA: 0x000AB879 File Offset: 0x000A9A79
		private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001778 RID: 6008 RVA: 0x000AB882 File Offset: 0x000A9A82
		private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001779 RID: 6009 RVA: 0x000AB88B File Offset: 0x000A9A8B
		private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x0600177A RID: 6010 RVA: 0x000AB894 File Offset: 0x000A9A94
		private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x0600177B RID: 6011 RVA: 0x000AB89D File Offset: 0x000A9A9D
		private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x0600177C RID: 6012 RVA: 0x000AB8A6 File Offset: 0x000A9AA6
		private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x0600177D RID: 6013 RVA: 0x000AB8AF File Offset: 0x000A9AAF
		private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x0600177E RID: 6014 RVA: 0x000AB8B8 File Offset: 0x000A9AB8
		private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x0600177F RID: 6015 RVA: 0x000AB8C1 File Offset: 0x000A9AC1
		private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001780 RID: 6016 RVA: 0x000AB8CC File Offset: 0x000A9ACC
		private void HandleWidgetPropertyChangeOf_widget(string propertyName)
		{
			if (propertyName == "IsHidden")
			{
				this._datasource_Root.IsFiltered = this._widget.IsHidden;
				return;
			}
			if (propertyName == "ListItemId")
			{
				this._datasource_Root.Id = this._widget.ListItemId;
				return;
			}
			if (propertyName == "IsInfoAvailable")
			{
				this._datasource_Root.PlayerCanSeeValues = this._widget.IsInfoAvailable;
				return;
			}
		}

		// Token: 0x06001781 RID: 6017 RVA: 0x000AB945 File Offset: 0x000A9B45
		private void PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06001782 RID: 6018 RVA: 0x000AB94E File Offset: 0x000A9B4E
		private void boolPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06001783 RID: 6019 RVA: 0x000AB957 File Offset: 0x000A9B57
		private void floatPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06001784 RID: 6020 RVA: 0x000AB960 File Offset: 0x000A9B60
		private void Vec2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06001785 RID: 6021 RVA: 0x000AB969 File Offset: 0x000A9B69
		private void Vector2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06001786 RID: 6022 RVA: 0x000AB972 File Offset: 0x000A9B72
		private void doublePropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06001787 RID: 6023 RVA: 0x000AB97B File Offset: 0x000A9B7B
		private void intPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06001788 RID: 6024 RVA: 0x000AB984 File Offset: 0x000A9B84
		private void uintPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06001789 RID: 6025 RVA: 0x000AB98D File Offset: 0x000A9B8D
		private void ColorPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600178A RID: 6026 RVA: 0x000AB996 File Offset: 0x000A9B96
		private void HandleWidgetPropertyChangeOf_widget_0_0(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsBookmarked = this._widget_0_0.IsVisible;
				return;
			}
		}

		// Token: 0x0600178B RID: 6027 RVA: 0x000AB9BC File Offset: 0x000A9BBC
		private void PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600178C RID: 6028 RVA: 0x000AB9C5 File Offset: 0x000A9BC5
		private void boolPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600178D RID: 6029 RVA: 0x000AB9CE File Offset: 0x000A9BCE
		private void floatPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600178E RID: 6030 RVA: 0x000AB9D7 File Offset: 0x000A9BD7
		private void Vec2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600178F RID: 6031 RVA: 0x000AB9E0 File Offset: 0x000A9BE0
		private void Vector2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001790 RID: 6032 RVA: 0x000AB9E9 File Offset: 0x000A9BE9
		private void doublePropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001791 RID: 6033 RVA: 0x000AB9F2 File Offset: 0x000A9BF2
		private void intPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001792 RID: 6034 RVA: 0x000AB9FB File Offset: 0x000A9BFB
		private void uintPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001793 RID: 6035 RVA: 0x000ABA04 File Offset: 0x000A9C04
		private void ColorPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001794 RID: 6036 RVA: 0x000ABA0D File Offset: 0x000A9C0D
		private void HandleWidgetPropertyChangeOf_widget_0_1(string propertyName)
		{
			if (propertyName == "IsHidden")
			{
				this._datasource_Root.IsBookmarked = this._widget_0_1.IsHidden;
				return;
			}
		}

		// Token: 0x06001795 RID: 6037 RVA: 0x000ABA33 File Offset: 0x000A9C33
		private void PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001796 RID: 6038 RVA: 0x000ABA3C File Offset: 0x000A9C3C
		private void boolPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001797 RID: 6039 RVA: 0x000ABA45 File Offset: 0x000A9C45
		private void floatPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001798 RID: 6040 RVA: 0x000ABA4E File Offset: 0x000A9C4E
		private void Vec2PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001799 RID: 6041 RVA: 0x000ABA57 File Offset: 0x000A9C57
		private void Vector2PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x0600179A RID: 6042 RVA: 0x000ABA60 File Offset: 0x000A9C60
		private void doublePropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x0600179B RID: 6043 RVA: 0x000ABA69 File Offset: 0x000A9C69
		private void intPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x0600179C RID: 6044 RVA: 0x000ABA72 File Offset: 0x000A9C72
		private void uintPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x0600179D RID: 6045 RVA: 0x000ABA7B File Offset: 0x000A9C7B
		private void ColorPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x0600179E RID: 6046 RVA: 0x000ABA84 File Offset: 0x000A9C84
		private void HandleWidgetPropertyChangeOf_widget_0_2(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.Name = this._widget_0_2.Text;
				return;
			}
		}

		// Token: 0x0600179F RID: 6047 RVA: 0x000ABAAA File Offset: 0x000A9CAA
		private void PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x060017A0 RID: 6048 RVA: 0x000ABAB3 File Offset: 0x000A9CB3
		private void boolPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x060017A1 RID: 6049 RVA: 0x000ABABC File Offset: 0x000A9CBC
		private void floatPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x060017A2 RID: 6050 RVA: 0x000ABAC5 File Offset: 0x000A9CC5
		private void Vec2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x060017A3 RID: 6051 RVA: 0x000ABACE File Offset: 0x000A9CCE
		private void Vector2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x060017A4 RID: 6052 RVA: 0x000ABAD7 File Offset: 0x000A9CD7
		private void doublePropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x060017A5 RID: 6053 RVA: 0x000ABAE0 File Offset: 0x000A9CE0
		private void intPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x060017A6 RID: 6054 RVA: 0x000ABAE9 File Offset: 0x000A9CE9
		private void uintPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x060017A7 RID: 6055 RVA: 0x000ABAF2 File Offset: 0x000A9CF2
		private void ColorPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x060017A8 RID: 6056 RVA: 0x000ABAFB File Offset: 0x000A9CFB
		private void HandleWidgetPropertyChangeOf_widget_0_3(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.ComparedValue = this._widget_0_3.Text;
				return;
			}
		}

		// Token: 0x060017A9 RID: 6057 RVA: 0x000ABB21 File Offset: 0x000A9D21
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060017AA RID: 6058 RVA: 0x000ABB2F File Offset: 0x000A9D2F
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060017AB RID: 6059 RVA: 0x000ABB3E File Offset: 0x000A9D3E
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060017AC RID: 6060 RVA: 0x000ABB4D File Offset: 0x000A9D4D
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060017AD RID: 6061 RVA: 0x000ABB5C File Offset: 0x000A9D5C
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060017AE RID: 6062 RVA: 0x000ABB6B File Offset: 0x000A9D6B
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060017AF RID: 6063 RVA: 0x000ABB7A File Offset: 0x000A9D7A
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060017B0 RID: 6064 RVA: 0x000ABB89 File Offset: 0x000A9D89
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060017B1 RID: 6065 RVA: 0x000ABB98 File Offset: 0x000A9D98
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060017B2 RID: 6066 RVA: 0x000ABBA8 File Offset: 0x000A9DA8
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "IsFiltered")
			{
				this._widget.IsHidden = this._datasource_Root.IsFiltered;
				return;
			}
			if (propertyName == "Id")
			{
				this._widget.ListItemId = this._datasource_Root.Id;
				return;
			}
			if (propertyName == "PlayerCanSeeValues")
			{
				this._widget.IsInfoAvailable = this._datasource_Root.PlayerCanSeeValues;
				return;
			}
			if (propertyName == "IsBookmarked")
			{
				this._widget_0_0.IsVisible = this._datasource_Root.IsBookmarked;
				this._widget_0_1.IsHidden = this._datasource_Root.IsBookmarked;
				return;
			}
			if (propertyName == "Name")
			{
				this._widget_0_2.Text = this._datasource_Root.Name;
				return;
			}
			if (propertyName == "ComparedValue")
			{
				this._widget_0_3.Text = this._datasource_Root.ComparedValue;
				return;
			}
		}

		// Token: 0x060017B3 RID: 6067 RVA: 0x000ABCA4 File Offset: 0x000A9EA4
		private void RefreshDataSource_datasource_Root(EncyclopediaListItemVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
				this._widget_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1;
				this._widget_0_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_2;
				this._widget_0_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3;
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.IsHidden = this._datasource_Root.IsFiltered;
				this._widget.ListItemId = this._datasource_Root.Id;
				this._widget.IsInfoAvailable = this._datasource_Root.PlayerCanSeeValues;
				this._widget.EventFire += this.EventListenerOf_widget;
				this._widget.PropertyChanged += this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged += this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget;
				this._widget_0_0.IsVisible = this._datasource_Root.IsBookmarked;
				this._widget_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0;
				this._widget_0_1.IsHidden = this._datasource_Root.IsBookmarked;
				this._widget_0_1.PropertyChanged += this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_1;
				this._widget_0_2.Text = this._datasource_Root.Name;
				this._widget_0_2.PropertyChanged += this.PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_2;
				this._widget_0_3.Text = this._datasource_Root.ComparedValue;
				this._widget_0_3.PropertyChanged += this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_3;
			}
		}

		// Token: 0x040004C3 RID: 1219
		private EncyclopediaListItemButtonWidget _widget;

		// Token: 0x040004C4 RID: 1220
		private ListPanel _widget_0;

		// Token: 0x040004C5 RID: 1221
		private Widget _widget_0_0;

		// Token: 0x040004C6 RID: 1222
		private Widget _widget_0_1;

		// Token: 0x040004C7 RID: 1223
		private ScrollingTextWidget _widget_0_2;

		// Token: 0x040004C8 RID: 1224
		private TextWidget _widget_0_3;

		// Token: 0x040004C9 RID: 1225
		private EncyclopediaListItemVM _datasource_Root;
	}
}
