using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Inventory;
using TaleWorlds.Core.ViewModelCollection.ImageIdentifiers;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Inventory;

namespace SandBox.GauntletUI.AutoGenerated0
{
	// Token: 0x02000101 RID: 257
	public class Inventory__TaleWorlds_CampaignSystem_ViewModelCollection_Inventory_SPInventoryVM_Dependency_14_InventoryEquippedItemSlot__DependendPrefab : Widget
	{
		// Token: 0x06004C83 RID: 19587 RVA: 0x00262F11 File Offset: 0x00261111
		public Inventory__TaleWorlds_CampaignSystem_ViewModelCollection_Inventory_SPInventoryVM_Dependency_14_InventoryEquippedItemSlot__DependendPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06004C84 RID: 19588 RVA: 0x00262F1C File Offset: 0x0026111C
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new NavigationTargetSwitcher(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new Inventory__TaleWorlds_CampaignSystem_ViewModelCollection_Inventory_SPInventoryVM_Dependency_21_InventoryEquippedItemControls__DependendPrefab(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1.CreateWidgets();
			this._widget_2 = new BrushWidget(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_2_0 = new HintWidget(base.Context);
			this._widget_2.AddChild(this._widget_2_0);
			this._widget_3 = new InventoryEquippedItemSlotWidget(base.Context);
			GeneratedWidgetData component = new GeneratedWidgetData(this._widget_3);
			this._widget_3.AddComponent(component);
			this._widget.AddChild(this._widget_3);
			this._widget_3_0 = new Widget(base.Context);
			this._widget_3.AddChild(this._widget_3_0);
			this._widget_3_1 = new ImageIdentifierWidget(base.Context);
			this._widget_3.AddChild(this._widget_3_1);
			this._widget_3_1_0 = new Inventory__TaleWorlds_CampaignSystem_ViewModelCollection_Inventory_SPInventoryVM_Dependency_22_Standard_CircleLoadingWidget__DependendPrefab(base.Context);
			this._widget_3_1.AddChild(this._widget_3_1_0);
			this._widget_3_1_0.CreateWidgets();
		}

		// Token: 0x06004C85 RID: 19589 RVA: 0x00263070 File Offset: 0x00261270
		public void SetIds()
		{
			this._widget_1.SetIds();
			this._widget_1.Id = "EquippedItemControls";
			this._widget_2.Id = "Background";
			this._widget_3.Id = "EquippedItemSlotWidget";
			this._widget_3_1.Id = "ImageIdentifier";
			this._widget_3_1_0.SetIds();
			this._widget_3_1_0.Id = "LoadingIconWidget";
		}

		// Token: 0x06004C86 RID: 19590 RVA: 0x002630E4 File Offset: 0x002612E4
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.Fixed;
			base.HeightSizePolicy = SizePolicy.Fixed;
			base.SuggestedWidth = 130f;
			base.SuggestedHeight = 115f;
			base.PositionYOffset = -25f;
			this._widget_0.FromTarget = this._widget;
			this._widget_0.ToTarget = this._widget_2;
			this._widget_1.SetAttributes();
			this._widget_1.IsVisible = false;
			this._widget_1.ItemWidget = this._widget_3;
			this._widget_1.PositionYOffset = 50f;
			this._widget_2.AcceptDrop = true;
			this._widget_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_2.SuggestedHeight = 65f;
			this._widget_2.Brush = base.Context.GetBrush("InventoryBannerSlot");
			this._widget_2_0.IsDisabled = true;
			this._widget_2_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_3.IsRightSide = true;
			this._widget_3.TargetEquipmentIndex = 4;
			this._widget_3.AcceptDrag = true;
			this._widget_3.DoNotPassEventsToChildren = true;
			this._widget_3.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_3.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_3.SuggestedHeight = 65f;
			this._widget_3.Background = this._widget_2;
			this._widget_3.ImageIdentifier = this._widget_3_1;
			this._widget_3_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_3_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_3_0.MarginLeft = 3f;
			this._widget_3_0.MarginRight = 4f;
			this._widget_3_0.MarginTop = 3f;
			this._widget_3_0.MarginBottom = 4f;
			this._widget_3_0.Sprite = base.Context.SpriteData.GetSprite("Inventory\\portrait_cart");
			this._widget_3_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_3_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_3_1.MarginLeft = 3f;
			this._widget_3_1.MarginRight = 4f;
			this._widget_3_1.MarginTop = 3f;
			this._widget_3_1.MarginBottom = 4f;
			this._widget_3_1.LoadingIconWidget = this._widget_3_1_0;
			this._widget_3_1_0.SetAttributes();
			this._widget_3_1_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_3_1_0.VerticalAlignment = VerticalAlignment.Center;
		}

		// Token: 0x06004C87 RID: 19591 RVA: 0x0026336C File Offset: 0x0026156C
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2.EventFire -= this.EventListenerOf_widget_2;
				this._widget_2_0.EventFire -= this.EventListenerOf_widget_2_0;
				if (this._datasource_Root_CharacterBannerSlot != null)
				{
					this._widget_1.DestroyDataSource();
					this._widget_3.GetComponent<GeneratedWidgetData>().Data = null;
					this._datasource_Root_CharacterBannerSlot.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._widget_3.EventFire -= this.EventListenerOf_widget_3;
					this._widget_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_3;
					this._widget_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3;
					this._widget_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3;
					this._widget_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3;
					this._widget_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3;
					this._widget_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3;
					this._widget_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3;
					this._widget_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3;
					this._widget_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3;
					if (this._datasource_Root_CharacterBannerSlot_ImageIdentifier != null)
					{
						this._widget_3_1_0.DestroyDataSource();
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._widget_3_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3_1;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier = null;
					}
					this._datasource_Root_CharacterBannerSlot = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06004C88 RID: 19592 RVA: 0x00263826 File Offset: 0x00261A26
		public void SetDataSource(SPInventoryVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06004C89 RID: 19593 RVA: 0x00263830 File Offset: 0x00261A30
		private void EventListenerOf_widget_2(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Drop")
			{
				SPItemVM item = null;
				GeneratedWidgetData component = ((Widget)args[0]).GetComponent<GeneratedWidgetData>();
				if (component != null)
				{
					item = (SPItemVM)component.Data;
				}
				int index = (int)args[1];
				string targetTag = "Equipment_4";
				this._datasource_Root.ExecuteTransferWithParameters(item, index, targetTag);
			}
		}

		// Token: 0x06004C8A RID: 19594 RVA: 0x00263886 File Offset: 0x00261A86
		private void EventListenerOf_widget_2_0(Widget widget, string commandName, object[] args)
		{
			commandName == "HoverBegin";
			commandName == "HoverEnd";
		}

		// Token: 0x06004C8B RID: 19595 RVA: 0x002638A0 File Offset: 0x00261AA0
		private void EventListenerOf_widget_3(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root_CharacterBannerSlot.ExecuteSelectItem();
			}
		}

		// Token: 0x06004C8C RID: 19596 RVA: 0x002638BA File Offset: 0x00261ABA
		private void PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06004C8D RID: 19597 RVA: 0x002638C3 File Offset: 0x00261AC3
		private void boolPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06004C8E RID: 19598 RVA: 0x002638CC File Offset: 0x00261ACC
		private void floatPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06004C8F RID: 19599 RVA: 0x002638D5 File Offset: 0x00261AD5
		private void Vec2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06004C90 RID: 19600 RVA: 0x002638DE File Offset: 0x00261ADE
		private void Vector2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06004C91 RID: 19601 RVA: 0x002638E7 File Offset: 0x00261AE7
		private void doublePropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06004C92 RID: 19602 RVA: 0x002638F0 File Offset: 0x00261AF0
		private void intPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06004C93 RID: 19603 RVA: 0x002638F9 File Offset: 0x00261AF9
		private void uintPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06004C94 RID: 19604 RVA: 0x00263902 File Offset: 0x00261B02
		private void ColorPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06004C95 RID: 19605 RVA: 0x0026390C File Offset: 0x00261B0C
		private void HandleWidgetPropertyChangeOf_widget_3(string propertyName)
		{
			if (propertyName == "ItemType")
			{
				this._datasource_Root_CharacterBannerSlot.TypeName = this._widget_3.ItemType;
				return;
			}
			if (propertyName == "IsSelected")
			{
				this._datasource_Root_CharacterBannerSlot.IsSelected = this._widget_3.IsSelected;
				return;
			}
		}

		// Token: 0x06004C96 RID: 19606 RVA: 0x00263961 File Offset: 0x00261B61
		private void PropertyChangedListenerOf_widget_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_1(propertyName);
		}

		// Token: 0x06004C97 RID: 19607 RVA: 0x0026396A File Offset: 0x00261B6A
		private void boolPropertyChangedListenerOf_widget_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_1(propertyName);
		}

		// Token: 0x06004C98 RID: 19608 RVA: 0x00263973 File Offset: 0x00261B73
		private void floatPropertyChangedListenerOf_widget_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_1(propertyName);
		}

		// Token: 0x06004C99 RID: 19609 RVA: 0x0026397C File Offset: 0x00261B7C
		private void Vec2PropertyChangedListenerOf_widget_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_1(propertyName);
		}

		// Token: 0x06004C9A RID: 19610 RVA: 0x00263985 File Offset: 0x00261B85
		private void Vector2PropertyChangedListenerOf_widget_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_1(propertyName);
		}

		// Token: 0x06004C9B RID: 19611 RVA: 0x0026398E File Offset: 0x00261B8E
		private void doublePropertyChangedListenerOf_widget_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_1(propertyName);
		}

		// Token: 0x06004C9C RID: 19612 RVA: 0x00263997 File Offset: 0x00261B97
		private void intPropertyChangedListenerOf_widget_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_1(propertyName);
		}

		// Token: 0x06004C9D RID: 19613 RVA: 0x002639A0 File Offset: 0x00261BA0
		private void uintPropertyChangedListenerOf_widget_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_1(propertyName);
		}

		// Token: 0x06004C9E RID: 19614 RVA: 0x002639A9 File Offset: 0x00261BA9
		private void ColorPropertyChangedListenerOf_widget_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_1(propertyName);
		}

		// Token: 0x06004C9F RID: 19615 RVA: 0x002639B4 File Offset: 0x00261BB4
		private void HandleWidgetPropertyChangeOf_widget_3_1(string propertyName)
		{
			if (propertyName == "ImageId")
			{
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.Id = this._widget_3_1.ImageId;
				return;
			}
			if (propertyName == "AdditionalArgs")
			{
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.AdditionalArgs = this._widget_3_1.AdditionalArgs;
				return;
			}
			if (propertyName == "TextureProviderName")
			{
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.TextureProviderName = this._widget_3_1.TextureProviderName;
				return;
			}
		}

		// Token: 0x06004CA0 RID: 19616 RVA: 0x00263A2D File Offset: 0x00261C2D
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06004CA1 RID: 19617 RVA: 0x00263A3B File Offset: 0x00261C3B
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06004CA2 RID: 19618 RVA: 0x00263A4A File Offset: 0x00261C4A
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06004CA3 RID: 19619 RVA: 0x00263A59 File Offset: 0x00261C59
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06004CA4 RID: 19620 RVA: 0x00263A68 File Offset: 0x00261C68
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06004CA5 RID: 19621 RVA: 0x00263A77 File Offset: 0x00261C77
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06004CA6 RID: 19622 RVA: 0x00263A86 File Offset: 0x00261C86
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06004CA7 RID: 19623 RVA: 0x00263A95 File Offset: 0x00261C95
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06004CA8 RID: 19624 RVA: 0x00263AA4 File Offset: 0x00261CA4
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06004CA9 RID: 19625 RVA: 0x00263AB3 File Offset: 0x00261CB3
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "CharacterBannerSlot")
			{
				this.RefreshDataSource_datasource_Root_CharacterBannerSlot(this._datasource_Root.CharacterBannerSlot);
				return;
			}
		}

		// Token: 0x06004CAA RID: 19626 RVA: 0x00263AD4 File Offset: 0x00261CD4
		private void ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot(e.PropertyName);
		}

		// Token: 0x06004CAB RID: 19627 RVA: 0x00263AE2 File Offset: 0x00261CE2
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot(e.PropertyName);
		}

		// Token: 0x06004CAC RID: 19628 RVA: 0x00263AF1 File Offset: 0x00261CF1
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot(e.PropertyName);
		}

		// Token: 0x06004CAD RID: 19629 RVA: 0x00263B00 File Offset: 0x00261D00
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot(e.PropertyName);
		}

		// Token: 0x06004CAE RID: 19630 RVA: 0x00263B0F File Offset: 0x00261D0F
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot(e.PropertyName);
		}

		// Token: 0x06004CAF RID: 19631 RVA: 0x00263B1E File Offset: 0x00261D1E
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot(e.PropertyName);
		}

		// Token: 0x06004CB0 RID: 19632 RVA: 0x00263B2D File Offset: 0x00261D2D
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot(e.PropertyName);
		}

		// Token: 0x06004CB1 RID: 19633 RVA: 0x00263B3C File Offset: 0x00261D3C
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot(e.PropertyName);
		}

		// Token: 0x06004CB2 RID: 19634 RVA: 0x00263B4B File Offset: 0x00261D4B
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot(e.PropertyName);
		}

		// Token: 0x06004CB3 RID: 19635 RVA: 0x00263B5C File Offset: 0x00261D5C
		private void HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot(string propertyName)
		{
			if (propertyName == "ImageIdentifier")
			{
				this.RefreshDataSource_datasource_Root_CharacterBannerSlot_ImageIdentifier(this._datasource_Root_CharacterBannerSlot.ImageIdentifier);
				return;
			}
			if (propertyName == "TypeName")
			{
				this._widget_3.ItemType = this._datasource_Root_CharacterBannerSlot.TypeName;
				return;
			}
			if (propertyName == "IsSelected")
			{
				this._widget_3.IsSelected = this._datasource_Root_CharacterBannerSlot.IsSelected;
				return;
			}
		}

		// Token: 0x06004CB4 RID: 19636 RVA: 0x00263BD0 File Offset: 0x00261DD0
		private void ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(e.PropertyName);
		}

		// Token: 0x06004CB5 RID: 19637 RVA: 0x00263BDE File Offset: 0x00261DDE
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(e.PropertyName);
		}

		// Token: 0x06004CB6 RID: 19638 RVA: 0x00263BED File Offset: 0x00261DED
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(e.PropertyName);
		}

		// Token: 0x06004CB7 RID: 19639 RVA: 0x00263BFC File Offset: 0x00261DFC
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(e.PropertyName);
		}

		// Token: 0x06004CB8 RID: 19640 RVA: 0x00263C0B File Offset: 0x00261E0B
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(e.PropertyName);
		}

		// Token: 0x06004CB9 RID: 19641 RVA: 0x00263C1A File Offset: 0x00261E1A
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(e.PropertyName);
		}

		// Token: 0x06004CBA RID: 19642 RVA: 0x00263C29 File Offset: 0x00261E29
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(e.PropertyName);
		}

		// Token: 0x06004CBB RID: 19643 RVA: 0x00263C38 File Offset: 0x00261E38
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(e.PropertyName);
		}

		// Token: 0x06004CBC RID: 19644 RVA: 0x00263C47 File Offset: 0x00261E47
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(e.PropertyName);
		}

		// Token: 0x06004CBD RID: 19645 RVA: 0x00263C58 File Offset: 0x00261E58
		private void HandleViewModelPropertyChangeOf_datasource_Root_CharacterBannerSlot_ImageIdentifier(string propertyName)
		{
			if (propertyName == "Id")
			{
				this._widget_3_1.ImageId = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.Id;
				return;
			}
			if (propertyName == "AdditionalArgs")
			{
				this._widget_3_1.AdditionalArgs = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.AdditionalArgs;
				return;
			}
			if (propertyName == "TextureProviderName")
			{
				this._widget_3_1.TextureProviderName = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.TextureProviderName;
				return;
			}
		}

		// Token: 0x06004CBE RID: 19646 RVA: 0x00263CD4 File Offset: 0x00261ED4
		private void RefreshDataSource_datasource_Root(SPInventoryVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2.EventFire -= this.EventListenerOf_widget_2;
				this._widget_2_0.EventFire -= this.EventListenerOf_widget_2_0;
				if (this._datasource_Root_CharacterBannerSlot != null)
				{
					this._widget_1.SetDataSource(null);
					this._widget_3.GetComponent<GeneratedWidgetData>().Data = null;
					this._datasource_Root_CharacterBannerSlot.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._widget_3.EventFire -= this.EventListenerOf_widget_3;
					this._widget_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_3;
					this._widget_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3;
					this._widget_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3;
					this._widget_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3;
					this._widget_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3;
					this._widget_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3;
					this._widget_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3;
					this._widget_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3;
					this._widget_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3;
					if (this._datasource_Root_CharacterBannerSlot_ImageIdentifier != null)
					{
						this._widget_3_1_0.SetDataSource(null);
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._widget_3_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3_1;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier = null;
					}
					this._datasource_Root_CharacterBannerSlot = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2.EventFire += this.EventListenerOf_widget_2;
				this._widget_2_0.EventFire += this.EventListenerOf_widget_2_0;
				this._datasource_Root_CharacterBannerSlot = this._datasource_Root.CharacterBannerSlot;
				if (this._datasource_Root_CharacterBannerSlot != null)
				{
					this._datasource_Root_CharacterBannerSlot.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._datasource_Root_CharacterBannerSlot.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot;
					this._widget_3.ItemType = this._datasource_Root_CharacterBannerSlot.TypeName;
					this._widget_3.IsSelected = this._datasource_Root_CharacterBannerSlot.IsSelected;
					this._widget_3.GetComponent<GeneratedWidgetData>().Data = this._datasource_Root_CharacterBannerSlot;
					this._widget_3.EventFire += this.EventListenerOf_widget_3;
					this._widget_3.PropertyChanged += this.PropertyChangedListenerOf_widget_3;
					this._widget_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_3;
					this._widget_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_3;
					this._widget_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_3;
					this._widget_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_3;
					this._widget_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_3;
					this._widget_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_3;
					this._widget_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_3;
					this._widget_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_3;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier = this._datasource_Root_CharacterBannerSlot.ImageIdentifier;
					if (this._datasource_Root_CharacterBannerSlot_ImageIdentifier != null)
					{
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
						this._widget_3_1.ImageId = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.Id;
						this._widget_3_1.AdditionalArgs = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.AdditionalArgs;
						this._widget_3_1.TextureProviderName = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.TextureProviderName;
						this._widget_3_1.PropertyChanged += this.PropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_3_1;
						this._widget_3_1_0.SetDataSource(this._datasource_Root_CharacterBannerSlot_ImageIdentifier);
					}
					this._widget_1.SetDataSource(this._datasource_Root_CharacterBannerSlot);
				}
			}
		}

		// Token: 0x06004CBF RID: 19647 RVA: 0x002646D0 File Offset: 0x002628D0
		private void RefreshDataSource_datasource_Root_CharacterBannerSlot(SPItemVM newDataSource)
		{
			if (this._datasource_Root_CharacterBannerSlot != null)
			{
				this._widget_1.SetDataSource(null);
				this._widget_3.GetComponent<GeneratedWidgetData>().Data = null;
				this._datasource_Root_CharacterBannerSlot.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._widget_3.EventFire -= this.EventListenerOf_widget_3;
				this._widget_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_3;
				this._widget_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3;
				this._widget_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3;
				this._widget_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3;
				this._widget_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3;
				this._widget_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3;
				this._widget_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3;
				this._widget_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3;
				this._widget_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3;
				if (this._datasource_Root_CharacterBannerSlot_ImageIdentifier != null)
				{
					this._widget_3_1_0.SetDataSource(null);
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._widget_3_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3_1;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier = null;
				}
				this._datasource_Root_CharacterBannerSlot = null;
			}
			this._datasource_Root_CharacterBannerSlot = newDataSource;
			this._datasource_Root_CharacterBannerSlot = this._datasource_Root.CharacterBannerSlot;
			if (this._datasource_Root_CharacterBannerSlot != null)
			{
				this._datasource_Root_CharacterBannerSlot.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._datasource_Root_CharacterBannerSlot.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot;
				this._widget_3.ItemType = this._datasource_Root_CharacterBannerSlot.TypeName;
				this._widget_3.IsSelected = this._datasource_Root_CharacterBannerSlot.IsSelected;
				this._widget_3.GetComponent<GeneratedWidgetData>().Data = this._datasource_Root_CharacterBannerSlot;
				this._widget_3.EventFire += this.EventListenerOf_widget_3;
				this._widget_3.PropertyChanged += this.PropertyChangedListenerOf_widget_3;
				this._widget_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_3;
				this._widget_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_3;
				this._widget_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_3;
				this._widget_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_3;
				this._widget_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_3;
				this._widget_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_3;
				this._widget_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_3;
				this._widget_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_3;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier = this._datasource_Root_CharacterBannerSlot.ImageIdentifier;
				if (this._datasource_Root_CharacterBannerSlot_ImageIdentifier != null)
				{
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
					this._widget_3_1.ImageId = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.Id;
					this._widget_3_1.AdditionalArgs = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.AdditionalArgs;
					this._widget_3_1.TextureProviderName = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.TextureProviderName;
					this._widget_3_1.PropertyChanged += this.PropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_3_1;
					this._widget_3_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_3_1;
					this._widget_3_1_0.SetDataSource(this._datasource_Root_CharacterBannerSlot_ImageIdentifier);
				}
				this._widget_1.SetDataSource(this._datasource_Root_CharacterBannerSlot);
			}
		}

		// Token: 0x06004CC0 RID: 19648 RVA: 0x00264EB8 File Offset: 0x002630B8
		private void RefreshDataSource_datasource_Root_CharacterBannerSlot_ImageIdentifier(ItemImageIdentifierVM newDataSource)
		{
			if (this._datasource_Root_CharacterBannerSlot_ImageIdentifier != null)
			{
				this._widget_3_1_0.SetDataSource(null);
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._widget_3_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3_1;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier = null;
			}
			this._datasource_Root_CharacterBannerSlot_ImageIdentifier = newDataSource;
			this._datasource_Root_CharacterBannerSlot_ImageIdentifier = this._datasource_Root_CharacterBannerSlot.ImageIdentifier;
			if (this._datasource_Root_CharacterBannerSlot_ImageIdentifier != null)
			{
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._datasource_Root_CharacterBannerSlot_ImageIdentifier.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterBannerSlot_ImageIdentifier;
				this._widget_3_1.ImageId = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.Id;
				this._widget_3_1.AdditionalArgs = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.AdditionalArgs;
				this._widget_3_1.TextureProviderName = this._datasource_Root_CharacterBannerSlot_ImageIdentifier.TextureProviderName;
				this._widget_3_1.PropertyChanged += this.PropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_3_1;
				this._widget_3_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_3_1;
				this._widget_3_1_0.SetDataSource(this._datasource_Root_CharacterBannerSlot_ImageIdentifier);
			}
		}

		// Token: 0x04000FC1 RID: 4033
		private Widget _widget;

		// Token: 0x04000FC2 RID: 4034
		private NavigationTargetSwitcher _widget_0;

		// Token: 0x04000FC3 RID: 4035
		private Inventory__TaleWorlds_CampaignSystem_ViewModelCollection_Inventory_SPInventoryVM_Dependency_21_InventoryEquippedItemControls__DependendPrefab _widget_1;

		// Token: 0x04000FC4 RID: 4036
		private BrushWidget _widget_2;

		// Token: 0x04000FC5 RID: 4037
		private HintWidget _widget_2_0;

		// Token: 0x04000FC6 RID: 4038
		private InventoryEquippedItemSlotWidget _widget_3;

		// Token: 0x04000FC7 RID: 4039
		private Widget _widget_3_0;

		// Token: 0x04000FC8 RID: 4040
		private ImageIdentifierWidget _widget_3_1;

		// Token: 0x04000FC9 RID: 4041
		private Inventory__TaleWorlds_CampaignSystem_ViewModelCollection_Inventory_SPInventoryVM_Dependency_22_Standard_CircleLoadingWidget__DependendPrefab _widget_3_1_0;

		// Token: 0x04000FCA RID: 4042
		private SPInventoryVM _datasource_Root;

		// Token: 0x04000FCB RID: 4043
		private SPItemVM _datasource_Root_CharacterBannerSlot;

		// Token: 0x04000FCC RID: 4044
		private ItemImageIdentifierVM _datasource_Root_CharacterBannerSlot_ImageIdentifier;
	}
}
