using System;
using System.ComponentModel;
using System.Numerics;
using SandBox.ViewModelCollection.Tournament;
using TaleWorlds.Core.ViewModelCollection.ImageIdentifiers;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Tournament;
using TaleWorlds.TwoDimension;

namespace SandBox.GauntletUI.AutoGenerated0
{
	// Token: 0x0200018D RID: 397
	public class Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_8_Tournament_Participant__DependendPrefab : Widget
	{
		// Token: 0x060082FA RID: 33530 RVA: 0x00422EB5 File Offset: 0x004210B5
		public Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_8_Tournament_Participant__DependendPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x060082FB RID: 33531 RVA: 0x00422EC0 File Offset: 0x004210C0
		private VisualDefinition CreateVisualDefinitionTournamentParticipant()
		{
			VisualDefinition visualDefinition = new VisualDefinition("TournamentParticipant", 0.2f, 0f, AnimationInterpolation.Type.Linear, AnimationInterpolation.Function.Sine);
			visualDefinition.AddVisualState(new VisualState("Dead")
			{
				PositionXOffset = -450f
			});
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				PositionXOffset = 0f
			});
			visualDefinition.AddVisualState(new VisualState("Current")
			{
				PositionXOffset = 0f
			});
			visualDefinition.AddVisualState(new VisualState("Over")
			{
				PositionXOffset = 0f
			});
			return visualDefinition;
		}

		// Token: 0x060082FC RID: 33532 RVA: 0x00422F58 File Offset: 0x00421158
		private VisualDefinition CreateVisualDefinitionTournamentParticipantChild()
		{
			VisualDefinition visualDefinition = new VisualDefinition("TournamentParticipantChild", 0.4f, 0.2f, AnimationInterpolation.Type.Linear, AnimationInterpolation.Function.Sine);
			visualDefinition.AddVisualState(new VisualState("Dead")
			{
				SuggestedHeight = 0f
			});
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				SuggestedHeight = 30f
			});
			visualDefinition.AddVisualState(new VisualState("Current")
			{
				SuggestedHeight = 30f
			});
			visualDefinition.AddVisualState(new VisualState("Over")
			{
				SuggestedHeight = 30f
			});
			return visualDefinition;
		}

		// Token: 0x060082FD RID: 33533 RVA: 0x00422FF0 File Offset: 0x004211F0
		private VisualDefinition CreateVisualDefinitionTournamentParticipantParent()
		{
			VisualDefinition visualDefinition = new VisualDefinition("TournamentParticipantParent", 0.4f, 0.2f, AnimationInterpolation.Type.Linear, AnimationInterpolation.Function.Sine);
			visualDefinition.AddVisualState(new VisualState("Dead")
			{
				MarginTop = 0f,
				MarginBottom = 0f
			});
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				MarginTop = 2f,
				MarginBottom = 2f
			});
			visualDefinition.AddVisualState(new VisualState("Current")
			{
				MarginTop = 2f,
				MarginBottom = 2f
			});
			visualDefinition.AddVisualState(new VisualState("Over")
			{
				MarginTop = 2f,
				MarginBottom = 2f
			});
			return visualDefinition;
		}

		// Token: 0x060082FE RID: 33534 RVA: 0x004230B4 File Offset: 0x004212B4
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new TournamentParticipantBrushWidget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_0_0 = new ImageIdentifierWidget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_0);
			this._widget_0_0_1 = new ScrollingTextWidget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_1);
			this._widget_0_0_2 = new TextWidget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_2);
			this._widget_0_1 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_1);
		}

		// Token: 0x060082FF RID: 33535 RVA: 0x00423194 File Offset: 0x00421394
		public void SetIds()
		{
			this._widget_0_0.Id = "ParentWidget";
			this._widget_0_0_0.Id = "CharacterImage";
			this._widget_0_0_1.Id = "NameTextWidget";
		}

		// Token: 0x06008300 RID: 33536 RVA: 0x004231C8 File Offset: 0x004213C8
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.CoverChildren;
			base.MarginTop = 2f;
			base.MarginBottom = 2f;
			base.VisualDefinition = this.CreateVisualDefinitionTournamentParticipantParent();
			this._widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.Brush = base.Context.GetBrush("Tournament.Participant");
			this._widget_0.VisualDefinition = this.CreateVisualDefinitionTournamentParticipant();
			this._widget_0.UpdateChildrenStates = true;
			this._widget_0.OnMission = true;
			this._widget_0.DoNotPassEventsToChildren = true;
			this._widget_0.NameTextWidget = this._widget_0_0_1;
			this._widget_0.MainHeroTextBrush = base.Context.GetBrush("Tournament.MainHero.Participant.Text");
			this._widget_0.NormalTextBrush = base.Context.GetBrush("Tournament.Participant.Text");
			this._widget_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.SuggestedHeight = 30f;
			this._widget_0_0.VisualDefinition = this.CreateVisualDefinitionTournamentParticipantChild();
			this._widget_0_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_0.SuggestedWidth = 45f;
			this._widget_0_0_0.SuggestedHeight = 30f;
			this._widget_0_0_0.MarginLeft = 5f;
			this._widget_0_0_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0_1.Brush = base.Context.GetBrush("Tournament.Participant.Text");
			this._widget_0_0_1.MarginLeft = 60f;
			this._widget_0_0_1.MarginRight = 25f;
			this._widget_0_0_2.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_2.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0_2.SuggestedWidth = 25f;
			this._widget_0_0_2.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_0_2.Brush = base.Context.GetBrush("Tournament.Participant.Text");
			this._widget_0_0_2.Brush.TextHorizontalAlignment = TextHorizontalAlignment.Center;
			this._widget_0_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_1.SuggestedHeight = 30f;
		}

		// Token: 0x06008301 RID: 33537 RVA: 0x00423410 File Offset: 0x00421610
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_0.EventFire -= this.EventListenerOf_widget_0;
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1;
				if (this._datasource_Root_Visual != null)
				{
					this._datasource_Root_Visual.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
					this._widget_0_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_0;
					this._datasource_Root_Visual = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06008302 RID: 33538 RVA: 0x00423B9F File Offset: 0x00421D9F
		public void SetDataSource(TournamentParticipantVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06008303 RID: 33539 RVA: 0x00423BA8 File Offset: 0x00421DA8
		private void EventListenerOf_widget_0(Widget widget, string commandName, object[] args)
		{
			if (commandName == "ClickEvent")
			{
				this._datasource_Root.ExecuteOpenEncyclopedia();
			}
		}

		// Token: 0x06008304 RID: 33540 RVA: 0x00423BC2 File Offset: 0x00421DC2
		private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06008305 RID: 33541 RVA: 0x00423BCB File Offset: 0x00421DCB
		private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06008306 RID: 33542 RVA: 0x00423BD4 File Offset: 0x00421DD4
		private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06008307 RID: 33543 RVA: 0x00423BDD File Offset: 0x00421DDD
		private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06008308 RID: 33544 RVA: 0x00423BE6 File Offset: 0x00421DE6
		private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06008309 RID: 33545 RVA: 0x00423BEF File Offset: 0x00421DEF
		private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x0600830A RID: 33546 RVA: 0x00423BF8 File Offset: 0x00421DF8
		private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x0600830B RID: 33547 RVA: 0x00423C01 File Offset: 0x00421E01
		private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x0600830C RID: 33548 RVA: 0x00423C0A File Offset: 0x00421E0A
		private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x0600830D RID: 33549 RVA: 0x00423C13 File Offset: 0x00421E13
		private void HandleWidgetPropertyChangeOf_widget(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsInitialized = this._widget.IsVisible;
				return;
			}
		}

		// Token: 0x0600830E RID: 33550 RVA: 0x00423C39 File Offset: 0x00421E39
		private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x0600830F RID: 33551 RVA: 0x00423C42 File Offset: 0x00421E42
		private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06008310 RID: 33552 RVA: 0x00423C4B File Offset: 0x00421E4B
		private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06008311 RID: 33553 RVA: 0x00423C54 File Offset: 0x00421E54
		private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06008312 RID: 33554 RVA: 0x00423C5D File Offset: 0x00421E5D
		private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06008313 RID: 33555 RVA: 0x00423C66 File Offset: 0x00421E66
		private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06008314 RID: 33556 RVA: 0x00423C6F File Offset: 0x00421E6F
		private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06008315 RID: 33557 RVA: 0x00423C78 File Offset: 0x00421E78
		private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06008316 RID: 33558 RVA: 0x00423C81 File Offset: 0x00421E81
		private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06008317 RID: 33559 RVA: 0x00423C8C File Offset: 0x00421E8C
		private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
		{
			if (propertyName == "Brush.Color")
			{
				this._datasource_Root.TeamColor = this._widget_0.Brush.Color;
				return;
			}
			if (propertyName == "IsDead")
			{
				this._datasource_Root.IsDead = this._widget_0.IsDead;
				return;
			}
			if (propertyName == "IsMainHero")
			{
				this._datasource_Root.IsMainHero = this._widget_0.IsMainHero;
				return;
			}
		}

		// Token: 0x06008318 RID: 33560 RVA: 0x00423D0A File Offset: 0x00421F0A
		private void PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06008319 RID: 33561 RVA: 0x00423D13 File Offset: 0x00421F13
		private void boolPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600831A RID: 33562 RVA: 0x00423D1C File Offset: 0x00421F1C
		private void floatPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600831B RID: 33563 RVA: 0x00423D25 File Offset: 0x00421F25
		private void Vec2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600831C RID: 33564 RVA: 0x00423D2E File Offset: 0x00421F2E
		private void Vector2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600831D RID: 33565 RVA: 0x00423D37 File Offset: 0x00421F37
		private void doublePropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600831E RID: 33566 RVA: 0x00423D40 File Offset: 0x00421F40
		private void intPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600831F RID: 33567 RVA: 0x00423D49 File Offset: 0x00421F49
		private void uintPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06008320 RID: 33568 RVA: 0x00423D52 File Offset: 0x00421F52
		private void ColorPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06008321 RID: 33569 RVA: 0x00423D5B File Offset: 0x00421F5B
		private void HandleWidgetPropertyChangeOf_widget_0_0(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsValid = this._widget_0_0.IsVisible;
				return;
			}
		}

		// Token: 0x06008322 RID: 33570 RVA: 0x00423D81 File Offset: 0x00421F81
		private void PropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x06008323 RID: 33571 RVA: 0x00423D8A File Offset: 0x00421F8A
		private void boolPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x06008324 RID: 33572 RVA: 0x00423D93 File Offset: 0x00421F93
		private void floatPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x06008325 RID: 33573 RVA: 0x00423D9C File Offset: 0x00421F9C
		private void Vec2PropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x06008326 RID: 33574 RVA: 0x00423DA5 File Offset: 0x00421FA5
		private void Vector2PropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x06008327 RID: 33575 RVA: 0x00423DAE File Offset: 0x00421FAE
		private void doublePropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x06008328 RID: 33576 RVA: 0x00423DB7 File Offset: 0x00421FB7
		private void intPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x06008329 RID: 33577 RVA: 0x00423DC0 File Offset: 0x00421FC0
		private void uintPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x0600832A RID: 33578 RVA: 0x00423DC9 File Offset: 0x00421FC9
		private void ColorPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x0600832B RID: 33579 RVA: 0x00423DD2 File Offset: 0x00421FD2
		private void HandleWidgetPropertyChangeOf_widget_0_0_1(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.Name = this._widget_0_0_1.Text;
				return;
			}
		}

		// Token: 0x0600832C RID: 33580 RVA: 0x00423DF8 File Offset: 0x00421FF8
		private void PropertyChangedListenerOf_widget_0_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_2(propertyName);
		}

		// Token: 0x0600832D RID: 33581 RVA: 0x00423E01 File Offset: 0x00422001
		private void boolPropertyChangedListenerOf_widget_0_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_2(propertyName);
		}

		// Token: 0x0600832E RID: 33582 RVA: 0x00423E0A File Offset: 0x0042200A
		private void floatPropertyChangedListenerOf_widget_0_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_2(propertyName);
		}

		// Token: 0x0600832F RID: 33583 RVA: 0x00423E13 File Offset: 0x00422013
		private void Vec2PropertyChangedListenerOf_widget_0_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_2(propertyName);
		}

		// Token: 0x06008330 RID: 33584 RVA: 0x00423E1C File Offset: 0x0042201C
		private void Vector2PropertyChangedListenerOf_widget_0_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_2(propertyName);
		}

		// Token: 0x06008331 RID: 33585 RVA: 0x00423E25 File Offset: 0x00422025
		private void doublePropertyChangedListenerOf_widget_0_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_2(propertyName);
		}

		// Token: 0x06008332 RID: 33586 RVA: 0x00423E2E File Offset: 0x0042202E
		private void intPropertyChangedListenerOf_widget_0_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_2(propertyName);
		}

		// Token: 0x06008333 RID: 33587 RVA: 0x00423E37 File Offset: 0x00422037
		private void uintPropertyChangedListenerOf_widget_0_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_2(propertyName);
		}

		// Token: 0x06008334 RID: 33588 RVA: 0x00423E40 File Offset: 0x00422040
		private void ColorPropertyChangedListenerOf_widget_0_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_2(propertyName);
		}

		// Token: 0x06008335 RID: 33589 RVA: 0x00423E49 File Offset: 0x00422049
		private void HandleWidgetPropertyChangeOf_widget_0_0_2(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.Score = this._widget_0_0_2.Text;
				return;
			}
		}

		// Token: 0x06008336 RID: 33590 RVA: 0x00423E6F File Offset: 0x0042206F
		private void PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06008337 RID: 33591 RVA: 0x00423E78 File Offset: 0x00422078
		private void boolPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06008338 RID: 33592 RVA: 0x00423E81 File Offset: 0x00422081
		private void floatPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06008339 RID: 33593 RVA: 0x00423E8A File Offset: 0x0042208A
		private void Vec2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600833A RID: 33594 RVA: 0x00423E93 File Offset: 0x00422093
		private void Vector2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600833B RID: 33595 RVA: 0x00423E9C File Offset: 0x0042209C
		private void doublePropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600833C RID: 33596 RVA: 0x00423EA5 File Offset: 0x004220A5
		private void intPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600833D RID: 33597 RVA: 0x00423EAE File Offset: 0x004220AE
		private void uintPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600833E RID: 33598 RVA: 0x00423EB7 File Offset: 0x004220B7
		private void ColorPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600833F RID: 33599 RVA: 0x00423EC0 File Offset: 0x004220C0
		private void HandleWidgetPropertyChangeOf_widget_0_1(string propertyName)
		{
			if (propertyName == "IsHidden")
			{
				this._datasource_Root.IsValid = this._widget_0_1.IsHidden;
				return;
			}
		}

		// Token: 0x06008340 RID: 33600 RVA: 0x00423EE6 File Offset: 0x004220E6
		private void PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x06008341 RID: 33601 RVA: 0x00423EEF File Offset: 0x004220EF
		private void boolPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x06008342 RID: 33602 RVA: 0x00423EF8 File Offset: 0x004220F8
		private void floatPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x06008343 RID: 33603 RVA: 0x00423F01 File Offset: 0x00422101
		private void Vec2PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x06008344 RID: 33604 RVA: 0x00423F0A File Offset: 0x0042210A
		private void Vector2PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x06008345 RID: 33605 RVA: 0x00423F13 File Offset: 0x00422113
		private void doublePropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x06008346 RID: 33606 RVA: 0x00423F1C File Offset: 0x0042211C
		private void intPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x06008347 RID: 33607 RVA: 0x00423F25 File Offset: 0x00422125
		private void uintPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x06008348 RID: 33608 RVA: 0x00423F2E File Offset: 0x0042212E
		private void ColorPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x06008349 RID: 33609 RVA: 0x00423F38 File Offset: 0x00422138
		private void HandleWidgetPropertyChangeOf_widget_0_0_0(string propertyName)
		{
			if (propertyName == "ImageId")
			{
				this._datasource_Root_Visual.Id = this._widget_0_0_0.ImageId;
				return;
			}
			if (propertyName == "AdditionalArgs")
			{
				this._datasource_Root_Visual.AdditionalArgs = this._widget_0_0_0.AdditionalArgs;
				return;
			}
			if (propertyName == "TextureProviderName")
			{
				this._datasource_Root_Visual.TextureProviderName = this._widget_0_0_0.TextureProviderName;
				return;
			}
		}

		// Token: 0x0600834A RID: 33610 RVA: 0x00423FB1 File Offset: 0x004221B1
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600834B RID: 33611 RVA: 0x00423FBF File Offset: 0x004221BF
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600834C RID: 33612 RVA: 0x00423FCE File Offset: 0x004221CE
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600834D RID: 33613 RVA: 0x00423FDD File Offset: 0x004221DD
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600834E RID: 33614 RVA: 0x00423FEC File Offset: 0x004221EC
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600834F RID: 33615 RVA: 0x00423FFB File Offset: 0x004221FB
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06008350 RID: 33616 RVA: 0x0042400A File Offset: 0x0042220A
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06008351 RID: 33617 RVA: 0x00424019 File Offset: 0x00422219
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06008352 RID: 33618 RVA: 0x00424028 File Offset: 0x00422228
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06008353 RID: 33619 RVA: 0x00424038 File Offset: 0x00422238
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "Visual")
			{
				this.RefreshDataSource_datasource_Root_Visual(this._datasource_Root.Visual);
				return;
			}
			if (propertyName == "IsInitialized")
			{
				this._widget.IsVisible = this._datasource_Root.IsInitialized;
				return;
			}
			if (propertyName == "TeamColor")
			{
				this._widget_0.Brush.Color = this._datasource_Root.TeamColor;
				return;
			}
			if (propertyName == "IsDead")
			{
				this._widget_0.IsDead = this._datasource_Root.IsDead;
				return;
			}
			if (propertyName == "IsMainHero")
			{
				this._widget_0.IsMainHero = this._datasource_Root.IsMainHero;
				return;
			}
			if (propertyName == "IsValid")
			{
				this._widget_0_0.IsVisible = this._datasource_Root.IsValid;
				this._widget_0_1.IsHidden = this._datasource_Root.IsValid;
				return;
			}
			if (propertyName == "Name")
			{
				this._widget_0_0_1.Text = this._datasource_Root.Name;
				return;
			}
			if (propertyName == "Score")
			{
				this._widget_0_0_2.Text = this._datasource_Root.Score;
				return;
			}
		}

		// Token: 0x06008354 RID: 33620 RVA: 0x0042417B File Offset: 0x0042237B
		private void ViewModelPropertyChangedListenerOf_datasource_Root_Visual(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
		}

		// Token: 0x06008355 RID: 33621 RVA: 0x00424189 File Offset: 0x00422389
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
		}

		// Token: 0x06008356 RID: 33622 RVA: 0x00424198 File Offset: 0x00422398
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
		}

		// Token: 0x06008357 RID: 33623 RVA: 0x004241A7 File Offset: 0x004223A7
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
		}

		// Token: 0x06008358 RID: 33624 RVA: 0x004241B6 File Offset: 0x004223B6
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
		}

		// Token: 0x06008359 RID: 33625 RVA: 0x004241C5 File Offset: 0x004223C5
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
		}

		// Token: 0x0600835A RID: 33626 RVA: 0x004241D4 File Offset: 0x004223D4
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
		}

		// Token: 0x0600835B RID: 33627 RVA: 0x004241E3 File Offset: 0x004223E3
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
		}

		// Token: 0x0600835C RID: 33628 RVA: 0x004241F2 File Offset: 0x004223F2
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
		}

		// Token: 0x0600835D RID: 33629 RVA: 0x00424204 File Offset: 0x00422404
		private void HandleViewModelPropertyChangeOf_datasource_Root_Visual(string propertyName)
		{
			if (propertyName == "Id")
			{
				this._widget_0_0_0.ImageId = this._datasource_Root_Visual.Id;
				return;
			}
			if (propertyName == "AdditionalArgs")
			{
				this._widget_0_0_0.AdditionalArgs = this._datasource_Root_Visual.AdditionalArgs;
				return;
			}
			if (propertyName == "TextureProviderName")
			{
				this._widget_0_0_0.TextureProviderName = this._datasource_Root_Visual.TextureProviderName;
				return;
			}
		}

		// Token: 0x0600835E RID: 33630 RVA: 0x00424280 File Offset: 0x00422480
		private void RefreshDataSource_datasource_Root(TournamentParticipantVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_0.EventFire -= this.EventListenerOf_widget_0;
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1;
				if (this._datasource_Root_Visual != null)
				{
					this._datasource_Root_Visual.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
					this._widget_0_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_0;
					this._datasource_Root_Visual = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.IsVisible = this._datasource_Root.IsInitialized;
				this._widget.PropertyChanged += this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged += this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget;
				this._widget_0.Brush.Color = this._datasource_Root.TeamColor;
				this._widget_0.IsDead = this._datasource_Root.IsDead;
				this._widget_0.IsMainHero = this._datasource_Root.IsMainHero;
				this._widget_0.EventFire += this.EventListenerOf_widget_0;
				this._widget_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_0_0.IsVisible = this._datasource_Root.IsValid;
				this._widget_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0_1.Text = this._datasource_Root.Name;
				this._widget_0_0_1.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_2.Text = this._datasource_Root.Score;
				this._widget_0_0_2.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_0_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_2;
				this._widget_0_1.IsHidden = this._datasource_Root.IsValid;
				this._widget_0_1.PropertyChanged += this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_1;
				this._datasource_Root_Visual = this._datasource_Root.Visual;
				if (this._datasource_Root_Visual != null)
				{
					this._datasource_Root_Visual.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
					this._datasource_Root_Visual.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
					this._widget_0_0_0.ImageId = this._datasource_Root_Visual.Id;
					this._widget_0_0_0.AdditionalArgs = this._datasource_Root_Visual.AdditionalArgs;
					this._widget_0_0_0.TextureProviderName = this._datasource_Root_Visual.TextureProviderName;
					this._widget_0_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_0;
					this._widget_0_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_0;
				}
			}
		}

		// Token: 0x0600835F RID: 33631 RVA: 0x00425294 File Offset: 0x00423494
		private void RefreshDataSource_datasource_Root_Visual(CharacterImageIdentifierVM newDataSource)
		{
			if (this._datasource_Root_Visual != null)
			{
				this._datasource_Root_Visual.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
				this._widget_0_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_0;
				this._datasource_Root_Visual = null;
			}
			this._datasource_Root_Visual = newDataSource;
			this._datasource_Root_Visual = this._datasource_Root.Visual;
			if (this._datasource_Root_Visual != null)
			{
				this._datasource_Root_Visual.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
				this._datasource_Root_Visual.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
				this._widget_0_0_0.ImageId = this._datasource_Root_Visual.Id;
				this._widget_0_0_0.AdditionalArgs = this._datasource_Root_Visual.AdditionalArgs;
				this._widget_0_0_0.TextureProviderName = this._datasource_Root_Visual.TextureProviderName;
				this._widget_0_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_0;
			}
		}

		// Token: 0x04001A34 RID: 6708
		private Widget _widget;

		// Token: 0x04001A35 RID: 6709
		private TournamentParticipantBrushWidget _widget_0;

		// Token: 0x04001A36 RID: 6710
		private Widget _widget_0_0;

		// Token: 0x04001A37 RID: 6711
		private ImageIdentifierWidget _widget_0_0_0;

		// Token: 0x04001A38 RID: 6712
		private ScrollingTextWidget _widget_0_0_1;

		// Token: 0x04001A39 RID: 6713
		private TextWidget _widget_0_0_2;

		// Token: 0x04001A3A RID: 6714
		private Widget _widget_0_1;

		// Token: 0x04001A3B RID: 6715
		private TournamentParticipantVM _datasource_Root;

		// Token: 0x04001A3C RID: 6716
		private CharacterImageIdentifierVM _datasource_Root_Visual;
	}
}
