using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Election
{
	// Token: 0x020002BF RID: 703
	public abstract class KingdomDecision
	{
		// Token: 0x06002542 RID: 9538 RVA: 0x0009B76B File Offset: 0x0009996B
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._kingdom);
			collectedObjects.Add(this.ProposerClan);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.TriggerTime, collectedObjects);
		}

		// Token: 0x06002543 RID: 9539 RVA: 0x0009B796 File Offset: 0x00099996
		internal static object AutoGeneratedGetMemberValueProposerClan(object o)
		{
			return ((KingdomDecision)o).ProposerClan;
		}

		// Token: 0x06002544 RID: 9540 RVA: 0x0009B7A3 File Offset: 0x000999A3
		internal static object AutoGeneratedGetMemberValueTriggerTime(object o)
		{
			return ((KingdomDecision)o).TriggerTime;
		}

		// Token: 0x06002545 RID: 9541 RVA: 0x0009B7B5 File Offset: 0x000999B5
		internal static object AutoGeneratedGetMemberValue_isEnforced(object o)
		{
			return ((KingdomDecision)o)._isEnforced;
		}

		// Token: 0x06002546 RID: 9542 RVA: 0x0009B7C7 File Offset: 0x000999C7
		internal static object AutoGeneratedGetMemberValue_playerExamined(object o)
		{
			return ((KingdomDecision)o)._playerExamined;
		}

		// Token: 0x06002547 RID: 9543 RVA: 0x0009B7D9 File Offset: 0x000999D9
		internal static object AutoGeneratedGetMemberValue_kingdom(object o)
		{
			return ((KingdomDecision)o)._kingdom;
		}

		// Token: 0x1700095E RID: 2398
		// (get) Token: 0x06002548 RID: 9544 RVA: 0x0009B7E6 File Offset: 0x000999E6
		public Kingdom Kingdom
		{
			get
			{
				return this._kingdom ?? this.ProposerClan.Kingdom;
			}
		}

		// Token: 0x1700095F RID: 2399
		// (get) Token: 0x06002549 RID: 9545 RVA: 0x0009B7FD File Offset: 0x000999FD
		// (set) Token: 0x0600254A RID: 9546 RVA: 0x0009B805 File Offset: 0x00099A05
		[SaveableProperty(4)]
		public Clan ProposerClan { get; private set; }

		// Token: 0x17000960 RID: 2400
		// (get) Token: 0x0600254B RID: 9547 RVA: 0x0009B80E File Offset: 0x00099A0E
		// (set) Token: 0x0600254C RID: 9548 RVA: 0x0009B816 File Offset: 0x00099A16
		public bool IsEnforced
		{
			get
			{
				return this._isEnforced;
			}
			set
			{
				this._isEnforced = value;
			}
		}

		// Token: 0x17000961 RID: 2401
		// (get) Token: 0x0600254D RID: 9549 RVA: 0x0009B81F File Offset: 0x00099A1F
		// (set) Token: 0x0600254E RID: 9550 RVA: 0x0009B827 File Offset: 0x00099A27
		public bool PlayerExamined
		{
			get
			{
				return this._playerExamined;
			}
			set
			{
				this._playerExamined = value;
			}
		}

		// Token: 0x17000962 RID: 2402
		// (get) Token: 0x0600254F RID: 9551 RVA: 0x0009B830 File Offset: 0x00099A30
		// (set) Token: 0x06002550 RID: 9552 RVA: 0x0009B842 File Offset: 0x00099A42
		public bool NotifyPlayer
		{
			get
			{
				return this._notifyPlayer || this.IsEnforced;
			}
			set
			{
				this._notifyPlayer = value;
			}
		}

		// Token: 0x17000963 RID: 2403
		// (get) Token: 0x06002551 RID: 9553 RVA: 0x0009B84B File Offset: 0x00099A4B
		public bool IsPlayerParticipant
		{
			get
			{
				return this.Kingdom == Clan.PlayerClan.Kingdom && !Clan.PlayerClan.IsUnderMercenaryService;
			}
		}

		// Token: 0x17000964 RID: 2404
		// (get) Token: 0x06002552 RID: 9554 RVA: 0x0009B86E File Offset: 0x00099A6E
		// (set) Token: 0x06002553 RID: 9555 RVA: 0x0009B876 File Offset: 0x00099A76
		[SaveableProperty(3)]
		public CampaignTime TriggerTime { get; protected set; }

		// Token: 0x06002554 RID: 9556 RVA: 0x0009B87F File Offset: 0x00099A7F
		protected KingdomDecision(Clan proposerClan)
		{
			this.ProposerClan = proposerClan;
			this._kingdom = proposerClan.Kingdom;
			this.TriggerTime = CampaignTime.HoursFromNow((float)this.HoursToWait);
		}

		// Token: 0x17000965 RID: 2405
		// (get) Token: 0x06002555 RID: 9557 RVA: 0x0009B8B7 File Offset: 0x00099AB7
		public virtual bool IsKingsVoteAllowed
		{
			get
			{
				return true;
			}
		}

		// Token: 0x06002556 RID: 9558
		public abstract bool IsAllowed();

		// Token: 0x06002557 RID: 9559 RVA: 0x0009B8BC File Offset: 0x00099ABC
		public int GetInfluenceCost(Clan sponsorClan)
		{
			int proposalInfluenceCost = this.GetProposalInfluenceCost();
			if (sponsorClan != Clan.PlayerClan)
			{
				return proposalInfluenceCost;
			}
			return proposalInfluenceCost;
		}

		// Token: 0x06002558 RID: 9560
		public abstract int GetProposalInfluenceCost();

		// Token: 0x06002559 RID: 9561
		public abstract TextObject GetGeneralTitle();

		// Token: 0x0600255A RID: 9562
		public abstract TextObject GetSupportTitle();

		// Token: 0x0600255B RID: 9563
		public abstract TextObject GetChooseTitle();

		// Token: 0x0600255C RID: 9564
		public abstract TextObject GetSupportDescription();

		// Token: 0x0600255D RID: 9565
		public abstract TextObject GetChooseDescription();

		// Token: 0x0600255E RID: 9566 RVA: 0x0009B8DB File Offset: 0x00099ADB
		public virtual float CalculateMeritOfOutcome(DecisionOutcome candidateOutcome)
		{
			return 1f;
		}

		// Token: 0x0600255F RID: 9567
		public abstract IEnumerable<DecisionOutcome> DetermineInitialCandidates();

		// Token: 0x06002560 RID: 9568 RVA: 0x0009B8E4 File Offset: 0x00099AE4
		public MBList<DecisionOutcome> NarrowDownCandidates(MBList<DecisionOutcome> initialCandidates, int maxCandidateCount)
		{
			foreach (DecisionOutcome decisionOutcome in initialCandidates)
			{
				decisionOutcome.InitialMerit = this.CalculateMeritOfOutcome(decisionOutcome);
			}
			return this.SortDecisionOutcomes(initialCandidates).Take(maxCandidateCount).ToMBList<DecisionOutcome>();
		}

		// Token: 0x06002561 RID: 9569
		public abstract Clan DetermineChooser();

		// Token: 0x06002562 RID: 9570 RVA: 0x0009B94C File Offset: 0x00099B4C
		public IEnumerable<Supporter> DetermineSupporters()
		{
			foreach (Clan clan in this.Kingdom.Clans)
			{
				if (!clan.IsUnderMercenaryService)
				{
					yield return new Supporter(clan);
				}
			}
			List<Clan>.Enumerator enumerator = default(List<Clan>.Enumerator);
			yield break;
			yield break;
		}

		// Token: 0x06002563 RID: 9571 RVA: 0x0009B95C File Offset: 0x00099B5C
		protected virtual bool ShouldBeCancelledInternal()
		{
			return false;
		}

		// Token: 0x06002564 RID: 9572 RVA: 0x0009B95F File Offset: 0x00099B5F
		protected virtual bool CanProposerClanChangeOpinion()
		{
			return false;
		}

		// Token: 0x06002565 RID: 9573 RVA: 0x0009B962 File Offset: 0x00099B62
		public virtual bool CanMakeDecision(out TextObject reason, bool includeReason = false)
		{
			reason = TextObject.GetEmpty();
			return true;
		}

		// Token: 0x06002566 RID: 9574 RVA: 0x0009B96C File Offset: 0x00099B6C
		public bool ShouldBeCancelled()
		{
			if (this.Kingdom.IsEliminated)
			{
				return true;
			}
			if (this.ProposerClan.Kingdom != this.Kingdom)
			{
				return true;
			}
			if (!this.IsAllowed())
			{
				return true;
			}
			if (this.ShouldBeCancelledInternal())
			{
				return true;
			}
			if (this.ProposerClan == Clan.PlayerClan)
			{
				return false;
			}
			MBList<DecisionOutcome> mblist = this.NarrowDownCandidates(this.DetermineInitialCandidates().ToMBList<DecisionOutcome>(), 3);
			DecisionOutcome queriedDecisionOutcome = this.GetQueriedDecisionOutcome(mblist);
			this.DetermineSponsors(mblist);
			Supporter.SupportWeights supportWeights;
			DecisionOutcome decisionOutcome = this.DetermineSupportOption(new Supporter(this.ProposerClan), mblist, out supportWeights, true);
			bool flag = this.ProposerClan.Influence < (float)this.GetInfluenceCostOfSupport(this.ProposerClan, Supporter.SupportWeights.SlightlyFavor) * 1.5f;
			bool flag2 = mblist.Any((DecisionOutcome t) => t.SponsorClan != null && t.SponsorClan.IsEliminated);
			bool flag3 = supportWeights == Supporter.SupportWeights.StayNeutral || decisionOutcome == null;
			bool flag4 = decisionOutcome != queriedDecisionOutcome || (decisionOutcome == queriedDecisionOutcome && flag3);
			return flag2 || (mblist.Any((DecisionOutcome t) => t.SponsorClan == this.ProposerClan) && !flag && ((!this.CanProposerClanChangeOpinion() && flag4) || (this.CanProposerClanChangeOpinion() && flag3)));
		}

		// Token: 0x17000966 RID: 2406
		// (get) Token: 0x06002567 RID: 9575 RVA: 0x0009BA94 File Offset: 0x00099C94
		protected virtual int HoursToWait
		{
			get
			{
				return 48;
			}
		}

		// Token: 0x17000967 RID: 2407
		// (get) Token: 0x06002568 RID: 9576 RVA: 0x0009BA98 File Offset: 0x00099C98
		public bool NeedsPlayerResolution
		{
			get
			{
				return this.Kingdom == Clan.PlayerClan.Kingdom && (this.IsEnforced || (this.TriggerTime.IsPast && this.Kingdom.RulingClan == Clan.PlayerClan));
			}
		}

		// Token: 0x06002569 RID: 9577 RVA: 0x0009BAE8 File Offset: 0x00099CE8
		public DecisionOutcome DetermineSupportOption(Supporter supporter, MBReadOnlyList<DecisionOutcome> possibleOutcomes, out Supporter.SupportWeights supportWeightOfSelectedOutcome, bool calculateRelationshipEffect)
		{
			Supporter.SupportWeights supportWeights = Supporter.SupportWeights.Choose;
			DecisionOutcome decisionOutcome = null;
			DecisionOutcome decisionOutcome2 = null;
			float num = float.MinValue;
			float num2 = 0f;
			int num3 = 0;
			Clan clan = supporter.Clan;
			foreach (DecisionOutcome decisionOutcome3 in possibleOutcomes)
			{
				float num4 = this.DetermineSupport(supporter.Clan, decisionOutcome3);
				if (num4 > num)
				{
					decisionOutcome = decisionOutcome3;
					num = num4;
				}
				if (num4 < num2)
				{
					decisionOutcome2 = decisionOutcome3;
					num2 = num4;
				}
				num3++;
			}
			if (decisionOutcome != null)
			{
				float num5 = num;
				if (decisionOutcome2 != null)
				{
					num5 -= 0.5f * num2;
				}
				float num6 = num5;
				if (clan.Influence < num6 * 2f)
				{
					num6 *= 0.5f;
					if (num6 > clan.Influence * 0.7f)
					{
						num6 = clan.Influence * 0.7f;
					}
				}
				else if (clan.Influence > num6 * 10f)
				{
					num6 *= 1.5f;
				}
				if (decisionOutcome.Likelihood > 0.65f)
				{
					num6 *= 1.6f * (1.2f - decisionOutcome.Likelihood);
				}
				if (calculateRelationshipEffect && decisionOutcome.SponsorClan != null)
				{
					int num7 = (int)(100f - MathF.Clamp((float)clan.Leader.GetRelation(decisionOutcome.SponsorClan.Leader), -100f, 100f));
					float num8 = MathF.Lerp(0.2f, 1.8f, 1f - (float)num7 / 200f, 1E-05f);
					num6 *= num8;
				}
				if (num6 > (float)this.GetInfluenceCostOfSupport(supporter.Clan, Supporter.SupportWeights.FullyPush))
				{
					supportWeights = Supporter.SupportWeights.FullyPush;
				}
				else if (num6 > (float)this.GetInfluenceCostOfSupport(supporter.Clan, Supporter.SupportWeights.StronglyFavor))
				{
					supportWeights = Supporter.SupportWeights.StronglyFavor;
				}
				else if (num6 > (float)this.GetInfluenceCostOfSupport(supporter.Clan, Supporter.SupportWeights.SlightlyFavor))
				{
					supportWeights = Supporter.SupportWeights.SlightlyFavor;
				}
			}
			while (supportWeights >= Supporter.SupportWeights.SlightlyFavor && supporter.Clan != null && supporter.Clan.Influence < (float)this.GetInfluenceCostOfSupport(supporter.Clan, supportWeights))
			{
				supportWeights--;
			}
			supportWeightOfSelectedOutcome = supportWeights;
			if (supportWeights == Supporter.SupportWeights.StayNeutral || supportWeights == Supporter.SupportWeights.Choose)
			{
				return null;
			}
			return decisionOutcome;
		}

		// Token: 0x0600256A RID: 9578
		public abstract float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome);

		// Token: 0x0600256B RID: 9579
		public abstract void DetermineSponsors(MBReadOnlyList<DecisionOutcome> possibleOutcomes);

		// Token: 0x0600256C RID: 9580 RVA: 0x0009BCF8 File Offset: 0x00099EF8
		protected void AssignDefaultSponsor(DecisionOutcome outcome)
		{
			if (outcome.SupporterList.Count > 0)
			{
				Supporter.SupportWeights maxWeight = outcome.SupporterList.Max((Supporter t) => t.SupportWeight);
				Supporter supporter = outcome.SupporterList.First((Supporter t) => t.SupportWeight == maxWeight);
				outcome.SetSponsor(supporter.Clan);
			}
		}

		// Token: 0x0600256D RID: 9581
		public abstract void ApplyChosenOutcome(DecisionOutcome chosenOutcome);

		// Token: 0x0600256E RID: 9582 RVA: 0x0009BD70 File Offset: 0x00099F70
		public int GetInfluenceCost(DecisionOutcome decisionOutcome, Clan clan, Supporter.SupportWeights supportWeight)
		{
			int result = 0;
			switch (supportWeight)
			{
			case Supporter.SupportWeights.Choose:
				result = 0;
				break;
			case Supporter.SupportWeights.StayNeutral:
				result = 0;
				break;
			case Supporter.SupportWeights.SlightlyFavor:
				result = this.GetInfluenceCostOfSupport(clan, Supporter.SupportWeights.SlightlyFavor);
				break;
			case Supporter.SupportWeights.StronglyFavor:
				result = this.GetInfluenceCostOfSupport(clan, Supporter.SupportWeights.StronglyFavor);
				break;
			case Supporter.SupportWeights.FullyPush:
				result = this.GetInfluenceCostOfSupport(clan, Supporter.SupportWeights.FullyPush);
				break;
			default:
				Debug.FailedAssert("false", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Election\\KingdomDecision.cs", "GetInfluenceCost", 345);
				break;
			}
			return result;
		}

		// Token: 0x0600256F RID: 9583
		public abstract TextObject GetSecondaryEffects();

		// Token: 0x06002570 RID: 9584
		public abstract void ApplySecondaryEffects(MBReadOnlyList<DecisionOutcome> possibleOutcomes, DecisionOutcome chosenOutcome);

		// Token: 0x06002571 RID: 9585
		public abstract TextObject GetChosenOutcomeText(DecisionOutcome chosenOutcome, KingdomDecision.SupportStatus supportStatus, bool isShortVersion = false);

		// Token: 0x06002572 RID: 9586 RVA: 0x0009BDDE File Offset: 0x00099FDE
		public MBList<DecisionOutcome> SortDecisionOutcomes(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			return (from k in possibleOutcomes
				orderby k.InitialMerit descending
				select k).ToMBList<DecisionOutcome>();
		}

		// Token: 0x06002573 RID: 9587
		public abstract DecisionOutcome GetQueriedDecisionOutcome(MBReadOnlyList<DecisionOutcome> possibleOutcomes);

		// Token: 0x06002574 RID: 9588 RVA: 0x0009BE0A File Offset: 0x0009A00A
		public bool IsSingleClanDecision()
		{
			return this.Kingdom.Clans.Count == 1;
		}

		// Token: 0x06002575 RID: 9589 RVA: 0x0009BE20 File Offset: 0x0009A020
		public virtual float CalculateRelationshipEffectWithSponsor(Clan clan)
		{
			float num = 0.8f;
			return (float)clan.Leader.GetRelation(this.ProposerClan.Leader) * num;
		}

		// Token: 0x06002576 RID: 9590 RVA: 0x0009BE4C File Offset: 0x0009A04C
		public int GetInfluenceCostOfSupport(Clan clan, Supporter.SupportWeights supportWeight)
		{
			float influenceCostOfSupportInternal = (float)this.GetInfluenceCostOfSupportInternal(supportWeight);
			float num = 1f;
			if (clan.Leader.GetPerkValue(DefaultPerks.Charm.FlexibleEthics))
			{
				num += DefaultPerks.Charm.FlexibleEthics.PrimaryBonus;
			}
			return (int)(influenceCostOfSupportInternal * num);
		}

		// Token: 0x06002577 RID: 9591 RVA: 0x0009BE89 File Offset: 0x0009A089
		protected virtual int GetInfluenceCostOfSupportInternal(Supporter.SupportWeights supportWeight)
		{
			switch (supportWeight)
			{
			case Supporter.SupportWeights.Choose:
			case Supporter.SupportWeights.StayNeutral:
				return 0;
			case Supporter.SupportWeights.SlightlyFavor:
				return 20;
			case Supporter.SupportWeights.StronglyFavor:
				return 60;
			case Supporter.SupportWeights.FullyPush:
				return 150;
			default:
				throw new ArgumentOutOfRangeException("supportWeight", supportWeight, null);
			}
		}

		// Token: 0x06002578 RID: 9592 RVA: 0x0009BEC6 File Offset: 0x0009A0C6
		public virtual bool OnShowDecision()
		{
			return true;
		}

		// Token: 0x06002579 RID: 9593 RVA: 0x0009BEC9 File Offset: 0x0009A0C9
		public virtual KingdomDecision GetFollowUpDecision()
		{
			return null;
		}

		// Token: 0x04000B21 RID: 2849
		[SaveableField(0)]
		private static bool _notificationsEnabled = true;

		// Token: 0x04000B22 RID: 2850
		[SaveableField(1)]
		private bool _isEnforced;

		// Token: 0x04000B23 RID: 2851
		[SaveableField(2)]
		private bool _playerExamined;

		// Token: 0x04000B24 RID: 2852
		private bool _notifyPlayer = KingdomDecision._notificationsEnabled;

		// Token: 0x04000B26 RID: 2854
		[SaveableField(10)]
		private Kingdom _kingdom;

		// Token: 0x04000B27 RID: 2855
		public KingdomDecision.SupportStatus SupportStatusOfFinalDecision;

		// Token: 0x0200064A RID: 1610
		public enum SupportStatus
		{
			// Token: 0x04001972 RID: 6514
			Equal,
			// Token: 0x04001973 RID: 6515
			Majority,
			// Token: 0x04001974 RID: 6516
			Minority
		}
	}
}
