<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PreprocessTopicPromptLab.Core\PreprocessTopicPromptLab.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>AnimusForgePreprocessTopicPromptLab.Cli</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
